// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cloudposse/atmos/pkg/terraform/generate (interfaces: StackProcessor)
//
// Generated by this command:
//
//	mockgen -typed -destination=mock_stack_processor_test.go -package=generate github.com/cloudposse/atmos/pkg/terraform/generate StackProcessor
//

// Package generate is a generated GoMock package.
package generate

import (
	reflect "reflect"

	auth "github.com/cloudposse/atmos/pkg/auth"
	schema "github.com/cloudposse/atmos/pkg/schema"
	gomock "go.uber.org/mock/gomock"
)

// MockStackProcessor is a mock of StackProcessor interface.
type MockStackProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockStackProcessorMockRecorder
	isgomock struct{}
}

// MockStackProcessorMockRecorder is the mock recorder for MockStackProcessor.
type MockStackProcessorMockRecorder struct {
	mock *MockStackProcessor
}

// NewMockStackProcessor creates a new mock instance.
func NewMockStackProcessor(ctrl *gomock.Controller) *MockStackProcessor {
	mock := &MockStackProcessor{ctrl: ctrl}
	mock.recorder = &MockStackProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStackProcessor) EXPECT() *MockStackProcessorMockRecorder {
	return m.recorder
}

// FindStacksMap mocks base method.
func (m *MockStackProcessor) FindStacksMap(atmosConfig *schema.AtmosConfiguration, ignoreMissingFiles bool) (map[string]any, map[string]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindStacksMap", atmosConfig, ignoreMissingFiles)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(map[string]map[string]any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindStacksMap indicates an expected call of FindStacksMap.
func (mr *MockStackProcessorMockRecorder) FindStacksMap(atmosConfig, ignoreMissingFiles any) *MockStackProcessorFindStacksMapCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindStacksMap", reflect.TypeOf((*MockStackProcessor)(nil).FindStacksMap), atmosConfig, ignoreMissingFiles)
	return &MockStackProcessorFindStacksMapCall{Call: call}
}

// MockStackProcessorFindStacksMapCall wrap *gomock.Call
type MockStackProcessorFindStacksMapCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStackProcessorFindStacksMapCall) Return(arg0 map[string]any, arg1 map[string]map[string]any, arg2 error) *MockStackProcessorFindStacksMapCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStackProcessorFindStacksMapCall) Do(f func(*schema.AtmosConfiguration, bool) (map[string]any, map[string]map[string]any, error)) *MockStackProcessorFindStacksMapCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStackProcessorFindStacksMapCall) DoAndReturn(f func(*schema.AtmosConfiguration, bool) (map[string]any, map[string]map[string]any, error)) *MockStackProcessorFindStacksMapCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ProcessStacks mocks base method.
func (m *MockStackProcessor) ProcessStacks(atmosConfig *schema.AtmosConfiguration, info schema.ConfigAndStacksInfo, checkStack, processTemplates, processYamlFunctions bool, skip []string, authManager auth.AuthManager) (schema.ConfigAndStacksInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessStacks", atmosConfig, info, checkStack, processTemplates, processYamlFunctions, skip, authManager)
	ret0, _ := ret[0].(schema.ConfigAndStacksInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessStacks indicates an expected call of ProcessStacks.
func (mr *MockStackProcessorMockRecorder) ProcessStacks(atmosConfig, info, checkStack, processTemplates, processYamlFunctions, skip, authManager any) *MockStackProcessorProcessStacksCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessStacks", reflect.TypeOf((*MockStackProcessor)(nil).ProcessStacks), atmosConfig, info, checkStack, processTemplates, processYamlFunctions, skip, authManager)
	return &MockStackProcessorProcessStacksCall{Call: call}
}

// MockStackProcessorProcessStacksCall wrap *gomock.Call
type MockStackProcessorProcessStacksCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStackProcessorProcessStacksCall) Return(arg0 schema.ConfigAndStacksInfo, arg1 error) *MockStackProcessorProcessStacksCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStackProcessorProcessStacksCall) Do(f func(*schema.AtmosConfiguration, schema.ConfigAndStacksInfo, bool, bool, bool, []string, auth.AuthManager) (schema.ConfigAndStacksInfo, error)) *MockStackProcessorProcessStacksCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStackProcessorProcessStacksCall) DoAndReturn(f func(*schema.AtmosConfiguration, schema.ConfigAndStacksInfo, bool, bool, bool, []string, auth.AuthManager) (schema.ConfigAndStacksInfo, error)) *MockStackProcessorProcessStacksCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
