// Code generated by MockGen. DO NOT EDIT.
// Source: eks.go
//
// Generated by this command:
//
//	mockgen -destination=mock_eks_client_test.go -package=aws -source=eks.go EKSClient
//

// Package aws is a generated GoMock package.
package aws

import (
	context "context"
	reflect "reflect"

	eks "github.com/aws/aws-sdk-go-v2/service/eks"
	gomock "go.uber.org/mock/gomock"
)

// MockEKSClient is a mock of EKSClient interface.
type MockEKSClient struct {
	ctrl     *gomock.Controller
	recorder *MockEKSClientMockRecorder
	isgomock struct{}
}

// MockEKSClientMockRecorder is the mock recorder for MockEKSClient.
type MockEKSClientMockRecorder struct {
	mock *MockEKSClient
}

// NewMockEKSClient creates a new mock instance.
func NewMockEKSClient(ctrl *gomock.Controller) *MockEKSClient {
	mock := &MockEKSClient{ctrl: ctrl}
	mock.recorder = &MockEKSClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEKSClient) EXPECT() *MockEKSClientMockRecorder {
	return m.recorder
}

// DescribeCluster mocks base method.
func (m *MockEKSClient) DescribeCluster(ctx context.Context, input *eks.DescribeClusterInput, opts ...func(*eks.Options)) (*eks.DescribeClusterOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeCluster", varargs...)
	ret0, _ := ret[0].(*eks.DescribeClusterOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeCluster indicates an expected call of DescribeCluster.
func (mr *MockEKSClientMockRecorder) DescribeCluster(ctx, input any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeCluster", reflect.TypeOf((*MockEKSClient)(nil).DescribeCluster), varargs...)
}
