// Code generated by MockGen. DO NOT EDIT.
// Source: executor.go
//
// Generated by this command:
//
//	mockgen -source=executor.go -destination=mock_executor_test.go -package=output
//

// Package output is a generated GoMock package.
package output

import (
	context "context"
	io "io"
	reflect "reflect"

	tfexec "github.com/hashicorp/terraform-exec/tfexec"
	gomock "go.uber.org/mock/gomock"
)

// MockTerraformRunner is a mock of TerraformRunner interface.
type MockTerraformRunner struct {
	ctrl     *gomock.Controller
	recorder *MockTerraformRunnerMockRecorder
	isgomock struct{}
}

// MockTerraformRunnerMockRecorder is the mock recorder for MockTerraformRunner.
type MockTerraformRunnerMockRecorder struct {
	mock *MockTerraformRunner
}

// NewMockTerraformRunner creates a new mock instance.
func NewMockTerraformRunner(ctrl *gomock.Controller) *MockTerraformRunner {
	mock := &MockTerraformRunner{ctrl: ctrl}
	mock.recorder = &MockTerraformRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTerraformRunner) EXPECT() *MockTerraformRunnerMockRecorder {
	return m.recorder
}

// Init mocks base method.
func (m *MockTerraformRunner) Init(ctx context.Context, opts ...tfexec.InitOption) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Init", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockTerraformRunnerMockRecorder) Init(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockTerraformRunner)(nil).Init), varargs...)
}

// Output mocks base method.
func (m *MockTerraformRunner) Output(ctx context.Context, opts ...tfexec.OutputOption) (map[string]tfexec.OutputMeta, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Output", varargs...)
	ret0, _ := ret[0].(map[string]tfexec.OutputMeta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Output indicates an expected call of Output.
func (mr *MockTerraformRunnerMockRecorder) Output(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Output", reflect.TypeOf((*MockTerraformRunner)(nil).Output), varargs...)
}

// SetEnv mocks base method.
func (m *MockTerraformRunner) SetEnv(env map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEnv", env)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetEnv indicates an expected call of SetEnv.
func (mr *MockTerraformRunnerMockRecorder) SetEnv(env any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEnv", reflect.TypeOf((*MockTerraformRunner)(nil).SetEnv), env)
}

// SetStderr mocks base method.
func (m *MockTerraformRunner) SetStderr(w io.Writer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStderr", w)
}

// SetStderr indicates an expected call of SetStderr.
func (mr *MockTerraformRunnerMockRecorder) SetStderr(w any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStderr", reflect.TypeOf((*MockTerraformRunner)(nil).SetStderr), w)
}

// SetStdout mocks base method.
func (m *MockTerraformRunner) SetStdout(w io.Writer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStdout", w)
}

// SetStdout indicates an expected call of SetStdout.
func (mr *MockTerraformRunnerMockRecorder) SetStdout(w any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStdout", reflect.TypeOf((*MockTerraformRunner)(nil).SetStdout), w)
}

// WorkspaceNew mocks base method.
func (m *MockTerraformRunner) WorkspaceNew(ctx context.Context, workspace string, opts ...tfexec.WorkspaceNewCmdOption) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, workspace}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WorkspaceNew", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// WorkspaceNew indicates an expected call of WorkspaceNew.
func (mr *MockTerraformRunnerMockRecorder) WorkspaceNew(ctx, workspace any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, workspace}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WorkspaceNew", reflect.TypeOf((*MockTerraformRunner)(nil).WorkspaceNew), varargs...)
}

// WorkspaceSelect mocks base method.
func (m *MockTerraformRunner) WorkspaceSelect(ctx context.Context, workspace string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WorkspaceSelect", ctx, workspace)
	ret0, _ := ret[0].(error)
	return ret0
}

// WorkspaceSelect indicates an expected call of WorkspaceSelect.
func (mr *MockTerraformRunnerMockRecorder) WorkspaceSelect(ctx, workspace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WorkspaceSelect", reflect.TypeOf((*MockTerraformRunner)(nil).WorkspaceSelect), ctx, workspace)
}

// MockComponentDescriber is a mock of ComponentDescriber interface.
type MockComponentDescriber struct {
	ctrl     *gomock.Controller
	recorder *MockComponentDescriberMockRecorder
	isgomock struct{}
}

// MockComponentDescriberMockRecorder is the mock recorder for MockComponentDescriber.
type MockComponentDescriberMockRecorder struct {
	mock *MockComponentDescriber
}

// NewMockComponentDescriber creates a new mock instance.
func NewMockComponentDescriber(ctrl *gomock.Controller) *MockComponentDescriber {
	mock := &MockComponentDescriber{ctrl: ctrl}
	mock.recorder = &MockComponentDescriberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockComponentDescriber) EXPECT() *MockComponentDescriberMockRecorder {
	return m.recorder
}

// DescribeComponent mocks base method.
func (m *MockComponentDescriber) DescribeComponent(params *DescribeComponentParams) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeComponent", params)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeComponent indicates an expected call of DescribeComponent.
func (mr *MockComponentDescriberMockRecorder) DescribeComponent(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeComponent", reflect.TypeOf((*MockComponentDescriber)(nil).DescribeComponent), params)
}

// MockStaticRemoteStateGetter is a mock of StaticRemoteStateGetter interface.
type MockStaticRemoteStateGetter struct {
	ctrl     *gomock.Controller
	recorder *MockStaticRemoteStateGetterMockRecorder
	isgomock struct{}
}

// MockStaticRemoteStateGetterMockRecorder is the mock recorder for MockStaticRemoteStateGetter.
type MockStaticRemoteStateGetterMockRecorder struct {
	mock *MockStaticRemoteStateGetter
}

// NewMockStaticRemoteStateGetter creates a new mock instance.
func NewMockStaticRemoteStateGetter(ctrl *gomock.Controller) *MockStaticRemoteStateGetter {
	mock := &MockStaticRemoteStateGetter{ctrl: ctrl}
	mock.recorder = &MockStaticRemoteStateGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStaticRemoteStateGetter) EXPECT() *MockStaticRemoteStateGetterMockRecorder {
	return m.recorder
}

// GetStaticRemoteStateOutputs mocks base method.
func (m *MockStaticRemoteStateGetter) GetStaticRemoteStateOutputs(sections *map[string]any) map[string]any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStaticRemoteStateOutputs", sections)
	ret0, _ := ret[0].(map[string]any)
	return ret0
}

// GetStaticRemoteStateOutputs indicates an expected call of GetStaticRemoteStateOutputs.
func (mr *MockStaticRemoteStateGetterMockRecorder) GetStaticRemoteStateOutputs(sections any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStaticRemoteStateOutputs", reflect.TypeOf((*MockStaticRemoteStateGetter)(nil).GetStaticRemoteStateOutputs), sections)
}
