apiVersion: vendir.k14s.io/v1alpha1
kind: Config

directories:

  # Terraform components
  - path: components/terraform
    contents:

      - path: vpc
        git:
          url: https://github.com/cloudposse/terraform-aws-components
          ref: 0.140.0
        newRootPath: modules/vpc
        includePaths:
          - modules/vpc/**/*

      - path: eks
        git:
          url: https://github.com/cloudposse/terraform-aws-components
          ref: 0.140.0
        newRootPath: modules/eks
        includePaths:
          - modules/eks/**/*

  # Helmfile components
  - path: components/helmfile
    contents:

      - path: nginx-ingress
        git:
          url: https://github.com/cloudposse/helmfiles
          ref: 0.121.0
        newRootPath: releases/nginx-ingress
        includePaths:
          - releases/nginx-ingress/**/*
