projects:
  globals:
    stage: prod

  terraform:
    vpc:
      vars:
        cidr_block: "10.102.0.0/18"
        # ...

    eks:
      command: "/usr/bin/terraform-0.13"
      vars:
        cluster_kubernetes_version: "1.17"
        # ...

  helmfile:
    ingress-nginx:
      vars:
        installed: true
