workflows:
  istio-init:
    description: Run 'istioctl operator init' and then install 'istio' helmfile to specified environment and stage (provided as command-line arguments)
    steps:
      - job: istioctl operator-init
      - job: helmfile deploy istio

  istio-destroy:
    description: Destroy 'istio' helmfile and remove 'istioctl' operator from specified environment and stage (provided as command-line arguments)
    steps:
      - job: helmfile destroy istio
      - job: istioctl operator-remove

  istio-init-all:
    description: Install 'istio' to all environments/stages
    steps:
      - job: istioctl operator-init
        environment: ue2
        stage: dev
      - job: helmfile deploy istio
        environment: ue2
        stage: dev
      - job: istioctl operator-init
        environment: ue2
        stage: staging
      - job: helmfile deploy istio
        environment: ue2
        stage: staging
      - job: istioctl operator-init
        environment: ue2
        stage: prod
      - job: helmfile deploy istio
        environment: ue2
        stage: prod

  istio-destroy-all:
    description: Remove 'istio' from all environments/stages
    steps:
      - job: helmfile destroy istio
        environment: ue2
        stage: dev
      - job: istioctl operator-remove
        environment: ue2
        stage: dev
      - job: helmfile destroy istio
        environment: ue2
        stage: staging
      - job: istioctl operator-remove
        environment: ue2
        stage: staging
      - job: helmfile destroy istio
        environment: ue2
        stage: prod
      - job: istioctl operator-remove
        environment: ue2
        stage: prod
