# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
tone_instructions: "Maintain a conversational spartan tone that is supportive in all responses."
early_access: true
enable_free_tier: true
reviews:
  profile: "chill"
  request_changes_workflow: true
  high_level_summary: true
  high_level_summary_placeholder: "@auto-summary"
  auto_title_placeholder: "@auto-title"
  review_status: true
  commit_status: true
  poem: false
  collapse_walkthrough: true
  sequence_diagrams: true
  changed_files_summary: true
  labeling_instructions:
    - label: "patch"
      instructions: "Apply when the PR contains changes that fix existing functionality."
    - label: "minor"
      instructions: "Apply when changes introduces new functionality but is non-breaking."
    - label: "major"
      instructions: "Apply when changes introduces new functionality that causes breaking changes requiring the user to update their configuration."
    - label: "no-release"
      instructions: "Apply when the PR contains changes only to documentation."
  #path_filters:
  #  - "!dist/**"
  #  - "src/**"
  #path_instructions:
  #  - path: "**/*.js"
  #    instructions: "Check for consistent coding styles and ES6+ syntax adherence."
  abort_on_close: true
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords:
      - "WIP"
      - "test"
    labels:
      - "ready-for-review"
    drafts: false
    base_branches:
      - "main"
  tools:
    ast-grep:
      rule_dirs:
        - "rules"
      util_dirs:
        - "utils"
      essential_rules: true
      packages:
        - "javascript"
        - "typescript"
    shellcheck:
      enabled: true
    ruff:
      enabled: true
    markdownlint:
      enabled: true
    github-checks:
      enabled: true
      timeout_ms: 90000
    languagetool:
      enabled: true
      enabled_rules:
        - "EN_QUOTES"
      level: "picky"
    biome:
      enabled: true
    hadolint:
      enabled: true
    swiftlint:
      enabled: true
      config_file: ".swiftlint.yml"
    phpstan:
      enabled: true
      level: "max"
    golangci-lint:
      enabled: true
      config_file: ".golangci.yaml"
    yamllint:
      enabled: true
    gitleaks:
      enabled: true
    checkov:
      enabled: true
    detekt:
      enabled: true
      config_file: "detekt.yml"
    eslint:
      enabled: true
    rubocop:
      enabled: true
    buf:
      enabled: true
    regal:
      enabled: true
    actionlint:
      enabled: true
    pmd:
      enabled: true
      config_file: "pmd.xml"
    cppcheck:
      enabled: true
    semgrep:
      enabled: true
      config_file: ".semgrep.yaml"
    circleci:
      enabled: false
chat:
  auto_reply: true
knowledge_base:
  opt_out: false
  learnings:
    scope: "auto"
  issues:
    scope: "auto"
  linear:
    team_keys:
      - "DEV"
  pull_requests:
    scope: "auto"
