codecov:
  require_ci_to_pass: true

coverage:
  status:
    project: false  # Disable project coverage status
    patch:
      default:
        # Only report coverage on changed lines
        target: auto
        threshold: 0%
        base: auto
        informational: true

comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  behavior: default
  require_changes: true  # Only post if coverage changes
  hide_project_coverage: true