codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: auto      # Automatically use the base branch's coverage
        threshold: 0%     # Do not allow any drop in overall project coverage
        base: auto
        if_not_found: success  # Don't fail if base coverage is missing
        paths:            # Only track Go files for coverage calculations
          - "**/*.go"
    patch:
      default:
        target: 80% # Target at least 80% test coverage on new/changed lines
        informational: true # Make patch coverage informational only
        base: auto
        paths:            # Only track Go files for coverage calculations
          - "**/*.go"
  ignore:
    - "**/mock_*.go"  # Adjust this pattern based on your project structure
    - "mock_*.go"  # Adjust this pattern based on your project structure
    - "**/mock/*.go" # Adjust interface required for mocking

comment:
  layout: "reach,diff,flags,tree"  # Display different coverage views
  behavior: default                # Default PR comment behavior
  require_changes: true             # Only post if coverage changes
  require_base: true                # Compare against base branch coverage

github_checks:
  annotations: true    # Enable GitHub Checks Annotations
