codecov:
  require_ci_to_pass: true

coverage:
  status:
    patch:
      default:
        target: 80% # Require at least 80% test coverage on new/changed lines
        threshold: 2% # Allow a small drop in coverage
        base: auto
        informational: false # Fail the PR check if coverage is too low

comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  behavior: default
  require_changes: true  # Only post if coverage changes
  hide_project_coverage: true