// Code generated by MockGen. DO NOT EDIT.
// Source: scoped_test.go
//
// Generated by this command:
//
//	mockgen -source=scoped_test.go -destination=mock_scoped_test.go -package=deferred
//

// Package deferred is a generated GoMock package.
package deferred

import (
	reflect "reflect"

	store "github.com/cloudposse/atmos/pkg/store"
	gomock "go.uber.org/mock/gomock"
)

// MockrawIdentityStore is a mock of rawIdentityStore interface.
type MockrawIdentityStore struct {
	ctrl     *gomock.Controller
	recorder *MockrawIdentityStoreMockRecorder
	isgomock struct{}
}

// MockrawIdentityStoreMockRecorder is the mock recorder for MockrawIdentityStore.
type MockrawIdentityStoreMockRecorder struct {
	mock *MockrawIdentityStore
}

// NewMockrawIdentityStore creates a new mock instance.
func NewMockrawIdentityStore(ctrl *gomock.Controller) *MockrawIdentityStore {
	mock := &MockrawIdentityStore{ctrl: ctrl}
	mock.recorder = &MockrawIdentityStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockrawIdentityStore) EXPECT() *MockrawIdentityStoreMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockrawIdentityStore) Get(stack, component, key string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", stack, component, key)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockrawIdentityStoreMockRecorder) Get(stack, component, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockrawIdentityStore)(nil).Get), stack, component, key)
}

// GetKey mocks base method.
func (m *MockrawIdentityStore) GetKey(key string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKey", key)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKey indicates an expected call of GetKey.
func (mr *MockrawIdentityStoreMockRecorder) GetKey(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKey", reflect.TypeOf((*MockrawIdentityStore)(nil).GetKey), key)
}

// GetRaw mocks base method.
func (m *MockrawIdentityStore) GetRaw(stack, component, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRaw", stack, component, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRaw indicates an expected call of GetRaw.
func (mr *MockrawIdentityStoreMockRecorder) GetRaw(stack, component, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRaw", reflect.TypeOf((*MockrawIdentityStore)(nil).GetRaw), stack, component, key)
}

// ResetAuthContext mocks base method.
func (m *MockrawIdentityStore) ResetAuthContext() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ResetAuthContext")
}

// ResetAuthContext indicates an expected call of ResetAuthContext.
func (mr *MockrawIdentityStoreMockRecorder) ResetAuthContext() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetAuthContext", reflect.TypeOf((*MockrawIdentityStore)(nil).ResetAuthContext))
}

// Set mocks base method.
func (m *MockrawIdentityStore) Set(stack, component, key string, value any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", stack, component, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockrawIdentityStoreMockRecorder) Set(stack, component, key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockrawIdentityStore)(nil).Set), stack, component, key, value)
}

// SetAuthContext mocks base method.
func (m *MockrawIdentityStore) SetAuthContext(resolver store.AuthContextResolver, identityName string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetAuthContext", resolver, identityName)
}

// SetAuthContext indicates an expected call of SetAuthContext.
func (mr *MockrawIdentityStoreMockRecorder) SetAuthContext(resolver, identityName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAuthContext", reflect.TypeOf((*MockrawIdentityStore)(nil).SetAuthContext), resolver, identityName)
}
