source:
  # Supports all protocols (local files, Git, Mercurial, HTTP, HTTPS, Amazon S3, Google GCP),
  # URL and archive formats described in https://github.com/hashicorp/go-getter
  uri: github.com/cloudposse/terraform-aws-components.git//modules/vpc-flow-logs-bucket?ref=0.193.1

# https://github.com/hashicorp/go-getter/issues/98
mixins:
  - uri: https://raw.githubusercontent.com/cloudposse/terraform-null-label/0.25.0/exports/context.tf
    filename: context.tf
