# yaml-language-server: $schema=https://atmos.tools/schemas/atmos/atmos-manifest/1.0/atmos-manifest.json

vars:
  stage: staging

import:
  - catalog/mycomponent

components:
  terraform:
    mycomponent:
      vars:
        foo: "custom-foo-staging"
        baz: "custom-baz-staging"

