// Code generated by MockGen. DO NOT EDIT.
// Source: ratelimit.go
//
// Generated by this command:
//
//	mockgen -source=ratelimit.go -destination=mock_ratelimit_test.go -package=github
//

// Package github is a generated GoMock package.
package github

import (
	context "context"
	reflect "reflect"

	github "github.com/google/go-github/v59/github"
	gomock "go.uber.org/mock/gomock"
)

// MockRateLimitService is a mock of RateLimitService interface.
type MockRateLimitService struct {
	ctrl     *gomock.Controller
	recorder *MockRateLimitServiceMockRecorder
	isgomock struct{}
}

// MockRateLimitServiceMockRecorder is the mock recorder for MockRateLimitService.
type MockRateLimitServiceMockRecorder struct {
	mock *MockRateLimitService
}

// NewMockRateLimitService creates a new mock instance.
func NewMockRateLimitService(ctrl *gomock.Controller) *MockRateLimitService {
	mock := &MockRateLimitService{ctrl: ctrl}
	mock.recorder = &MockRateLimitServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRateLimitService) EXPECT() *MockRateLimitServiceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockRateLimitService) Get(ctx context.Context) (*github.RateLimits, *github.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx)
	ret0, _ := ret[0].(*github.RateLimits)
	ret1, _ := ret[1].(*github.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockRateLimitServiceMockRecorder) Get(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRateLimitService)(nil).Get), ctx)
}
