// Code generated by MockGen. DO NOT EDIT.
// Source: identity_interface.go
//
// Generated by this command:
//
//	mockgen -source=identity_interface.go -destination=mock_identity_test.go -package=devcontainer
//

// Package devcontainer is a generated GoMock package.
package devcontainer

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIdentityManager is a mock of IdentityManager interface.
type MockIdentityManager struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityManagerMockRecorder
	isgomock struct{}
}

// MockIdentityManagerMockRecorder is the mock recorder for MockIdentityManager.
type MockIdentityManagerMockRecorder struct {
	mock *MockIdentityManager
}

// NewMockIdentityManager creates a new mock instance.
func NewMockIdentityManager(ctrl *gomock.Controller) *MockIdentityManager {
	mock := &MockIdentityManager{ctrl: ctrl}
	mock.recorder = &MockIdentityManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityManager) EXPECT() *MockIdentityManagerMockRecorder {
	return m.recorder
}

// InjectIdentityEnvironment mocks base method.
func (m *MockIdentityManager) InjectIdentityEnvironment(ctx context.Context, config *Config, identityName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InjectIdentityEnvironment", ctx, config, identityName)
	ret0, _ := ret[0].(error)
	return ret0
}

// InjectIdentityEnvironment indicates an expected call of InjectIdentityEnvironment.
func (mr *MockIdentityManagerMockRecorder) InjectIdentityEnvironment(ctx, config, identityName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InjectIdentityEnvironment", reflect.TypeOf((*MockIdentityManager)(nil).InjectIdentityEnvironment), ctx, config, identityName)
}
