import:
  - globals/tenant1-globals
  - globals/ue2-globals
  - catalog/terraform/top-level-component1
  - catalog/terraform/test-component
  - catalog/terraform/test-component-override
  - catalog/terraform/vpc
  - catalog/helmfile/echo-server
  - catalog/helmfile/infra-server

vars:
  stage: prod

terraform:
  vars: {}

helmfile:
  vars: {}

components:
  terraform:
    "infra/vpc":
      vars:
        cidr_block: 10.8.0.0/18
