import:
  - globals/tenant1-globals
  - globals/ue2-globals
  - catalog/terraform/test-component
  - catalog/terraform/test-component-override
  - catalog/terraform/vpc
  - catalog/helmfile/echo-server

vars:
  stage: staging

terraform:
  vars: {}

helmfile:
  vars: {}

components:
  terraform:
    "infra/vpc":
      vars:
        cidr_block: 10.9.0.0/18
