// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cloudposse/atmos/pkg/toolchain/registry (interfaces: ToolRegistry)
//
// Generated by this command:
//
//	mockgen -destination=mock_registry_test.go -package=toolchain github.com/cloudposse/atmos/pkg/toolchain/registry ToolRegistry
//

// Package toolchain is a generated GoMock package.
package toolchain

import (
	context "context"
	reflect "reflect"

	registry "github.com/cloudposse/atmos/pkg/toolchain/registry"
	gomock "go.uber.org/mock/gomock"
)

// MockToolRegistry is a mock of ToolRegistry interface.
type MockToolRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockToolRegistryMockRecorder
	isgomock struct{}
}

// MockToolRegistryMockRecorder is the mock recorder for MockToolRegistry.
type MockToolRegistryMockRecorder struct {
	mock *MockToolRegistry
}

// NewMockToolRegistry creates a new mock instance.
func NewMockToolRegistry(ctrl *gomock.Controller) *MockToolRegistry {
	mock := &MockToolRegistry{ctrl: ctrl}
	mock.recorder = &MockToolRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockToolRegistry) EXPECT() *MockToolRegistryMockRecorder {
	return m.recorder
}

// GetLatestVersion mocks base method.
func (m *MockToolRegistry) GetLatestVersion(owner, repo string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestVersion", owner, repo)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestVersion indicates an expected call of GetLatestVersion.
func (mr *MockToolRegistryMockRecorder) GetLatestVersion(owner, repo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestVersion", reflect.TypeOf((*MockToolRegistry)(nil).GetLatestVersion), owner, repo)
}

// GetMetadata mocks base method.
func (m *MockToolRegistry) GetMetadata(ctx context.Context) (*registry.RegistryMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetadata", ctx)
	ret0, _ := ret[0].(*registry.RegistryMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetadata indicates an expected call of GetMetadata.
func (mr *MockToolRegistryMockRecorder) GetMetadata(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadata", reflect.TypeOf((*MockToolRegistry)(nil).GetMetadata), ctx)
}

// GetTool mocks base method.
func (m *MockToolRegistry) GetTool(owner, repo string) (*registry.Tool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTool", owner, repo)
	ret0, _ := ret[0].(*registry.Tool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTool indicates an expected call of GetTool.
func (mr *MockToolRegistryMockRecorder) GetTool(owner, repo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTool", reflect.TypeOf((*MockToolRegistry)(nil).GetTool), owner, repo)
}

// GetToolWithVersion mocks base method.
func (m *MockToolRegistry) GetToolWithVersion(owner, repo, version string) (*registry.Tool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetToolWithVersion", owner, repo, version)
	ret0, _ := ret[0].(*registry.Tool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetToolWithVersion indicates an expected call of GetToolWithVersion.
func (mr *MockToolRegistryMockRecorder) GetToolWithVersion(owner, repo, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetToolWithVersion", reflect.TypeOf((*MockToolRegistry)(nil).GetToolWithVersion), owner, repo, version)
}

// ListAll mocks base method.
func (m *MockToolRegistry) ListAll(ctx context.Context, opts ...registry.ListOption) ([]*registry.Tool, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListAll", varargs...)
	ret0, _ := ret[0].([]*registry.Tool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll.
func (mr *MockToolRegistryMockRecorder) ListAll(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockToolRegistry)(nil).ListAll), varargs...)
}

// LoadLocalConfig mocks base method.
func (m *MockToolRegistry) LoadLocalConfig(configPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadLocalConfig", configPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadLocalConfig indicates an expected call of LoadLocalConfig.
func (mr *MockToolRegistryMockRecorder) LoadLocalConfig(configPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadLocalConfig", reflect.TypeOf((*MockToolRegistry)(nil).LoadLocalConfig), configPath)
}

// Search mocks base method.
func (m *MockToolRegistry) Search(ctx context.Context, query string, opts ...registry.SearchOption) ([]*registry.Tool, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, query}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Search", varargs...)
	ret0, _ := ret[0].([]*registry.Tool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockToolRegistryMockRecorder) Search(ctx, query any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, query}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockToolRegistry)(nil).Search), varargs...)
}
