import:
  - globals/tenant2-globals
  - globals/ue2-globals
  - catalog/terraform/test-component
  - catalog/terraform/test-component-override
  - catalog/terraform/vpc
  - catalog/helmfile/echo-server

vars:
  stage: prod

terraform:
  vars: {}

helmfile:
  vars: {}

components:
  terraform:
    vpc:
      vars:
        cidr_block: 10.8.0.0/18
