# yaml-language-server: $schema=https://atmos.tools/schemas/atmos/atmos-manifest/1.0/atmos-manifest.json

import:
- ../_defaults
- catalog/demo
- mixins/east-coast


terraform:
  providers:
    context:
      values:
        environment: prod
        support_email: prod-support@acme.com

components:
  terraform:
    demo:
      metadata:
        type: real
      vars:
        size: 10
        pet: "alien"
