import * as vscode from "vscode";
import { AtmosClient } from "./atmos-client";

export const RENDERED_YAML_SCHEME = "atmos-rendered";

export class RenderedYamlProvider implements vscode.TextDocumentContentProvider {
  private _onDidChange = new vscode.EventEmitter<vscode.Uri>();
  readonly onDidChange = this._onDidChange.event;

  constructor(private client: AtmosClient) {}

  async provideTextDocumentContent(uri: vscode.Uri): Promise<string> {
    const component = uri.authority;
    const stack = uri.query.replace("stack=", "");

    if (!component || !stack) {
      return "# Error: Missing component or stack parameter";
    }

    try {
      const yaml = await this.client.describeComponent(component, stack);
      return formatRenderedOutput(component, stack, yaml);
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      return `# Error describing component '${component}' in stack '${stack}'\n# ${message}`;
    }
  }

  /**
   * Refresh the content for a specific component/stack.
   */
  refreshUri(component: string, stack: string): void {
    const uri = buildRenderedYamlUri(component, stack);
    this._onDidChange.fire(uri);
  }

  dispose(): void {
    this._onDidChange.dispose();
  }
}

/**
 * Build a URI for the rendered YAML virtual document.
 */
export function buildRenderedYamlUri(
  component: string,
  stack: string
): vscode.Uri {
  return vscode.Uri.parse(
    `${RENDERED_YAML_SCHEME}://${component}/rendered.yaml?stack=${stack}`
  );
}

/**
 * Format the rendered output with a header comment.
 */
function formatRenderedOutput(
  component: string,
  stack: string,
  yaml: string
): string {
  const header = [
    `# Atmos Rendered Component Configuration`,
    `# Component: ${component}`,
    `# Stack: ${stack}`,
    `# Generated by: atmos describe component ${component} --stack ${stack}`,
    `#`,
    `# This is a read-only view. Edit the source stack files to make changes.`,
    ``,
  ].join("\n");

  return header + yaml;
}

/**
 * Open a rendered YAML document for a component in a stack.
 */
export async function showRenderedYaml(
  component: string,
  stack: string
): Promise<void> {
  const uri = buildRenderedYamlUri(component, stack);

  const doc = await vscode.workspace.openTextDocument(uri);
  await vscode.window.showTextDocument(doc, {
    preview: true,
    viewColumn: vscode.ViewColumn.Beside,
  });

  // Force YAML language mode for syntax highlighting.
  await vscode.languages.setTextDocumentLanguage(doc, "yaml");
}
