# yaml-language-server: $schema=https://atmos.tools/schemas/atmos/atmos-manifest/1.0/atmos-manifest.json

vars:
  stage: test

components:
  terraform:
    hello-world:
      hooks:
        announce-apply:
          kind: step
          type: say
          events:
            - after.terraform.apply
          when: always
          with:
            print: always
            content: >-
              {{ if eq .status "success" -}}
              Terraform apply for {{ .atmos_component }} in {{ .stack }} was successful.
              {{- else -}}
              Terraform apply for {{ .atmos_component }} in {{ .stack }} was not successful.
              {{- if .error }} {{ .error }}{{ end -}}
              {{- end }}
