import:
  - catalog/script/deploy-app
  - catalog/hello/world

vars:
  stage: dev

components:
  script:
    deploy-app:
      vars:
        replicas: 1  # Override for dev
  hello:
    world:
      vars:
        greeting: "hello from dev"  # Override for dev
