// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hashicorp/go-getter (interfaces: ProgressTracker)
//
// Generated by this command:
//
//	mockgen -destination=pkg/downloader/mock_progress_test.go -package=downloader github.com/hashicorp/go-getter ProgressTracker
//

// Package downloader is a generated GoMock package.
package downloader

import (
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProgressTracker is a mock of ProgressTracker interface.
type MockProgressTracker struct {
	ctrl     *gomock.Controller
	recorder *MockProgressTrackerMockRecorder
	isgomock struct{}
}

// MockProgressTrackerMockRecorder is the mock recorder for MockProgressTracker.
type MockProgressTrackerMockRecorder struct {
	mock *MockProgressTracker
}

// NewMockProgressTracker creates a new mock instance.
func NewMockProgressTracker(ctrl *gomock.Controller) *MockProgressTracker {
	mock := &MockProgressTracker{ctrl: ctrl}
	mock.recorder = &MockProgressTrackerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProgressTracker) EXPECT() *MockProgressTrackerMockRecorder {
	return m.recorder
}

// TrackProgress mocks base method.
func (m *MockProgressTracker) TrackProgress(src string, currentSize, totalSize int64, stream io.ReadCloser) io.ReadCloser {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackProgress", src, currentSize, totalSize, stream)
	ret0, _ := ret[0].(io.ReadCloser)
	return ret0
}

// TrackProgress indicates an expected call of TrackProgress.
func (mr *MockProgressTrackerMockRecorder) TrackProgress(src, currentSize, totalSize, stream any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackProgress", reflect.TypeOf((*MockProgressTracker)(nil).TrackProgress), src, currentSize, totalSize, stream)
}
