package aks

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"time"

	"github.com/spf13/cobra"

	errUtils "github.com/cloudposse/atmos/errors"
	"github.com/cloudposse/atmos/pkg/auth"
	azureCloud "github.com/cloudposse/atmos/pkg/auth/cloud/azure"
	"github.com/cloudposse/atmos/pkg/auth/credentials"
	"github.com/cloudposse/atmos/pkg/auth/types"
	"github.com/cloudposse/atmos/pkg/auth/validation"
	cfg "github.com/cloudposse/atmos/pkg/config"
	"github.com/cloudposse/atmos/pkg/data"
	log "github.com/cloudposse/atmos/pkg/logger"
	"github.com/cloudposse/atmos/pkg/perf"
	"github.com/cloudposse/atmos/pkg/schema"
)

// execCredentialAPIVersion is the Kubernetes exec credential plugin API version.
const execCredentialAPIVersion = "client.authentication.k8s.io/v1beta1"

// initCliConfigFn loads Atmos CLI configuration. Overridable in tests.
var initCliConfigFn = cfg.InitCliConfig

// authenticateForTokenFn authenticates an identity and returns credentials. Overridable in tests.
var authenticateForTokenFn = authenticateForToken

// getAKSTokenFn returns the AKS-scoped bearer token. Overridable in tests.
var getAKSTokenFn = azureCloud.GetToken

// tokenCmd generates a short-lived AKS bearer token for kubectl.
var tokenCmd = &cobra.Command{
	Use:   "token",
	Short: "Generate an AKS bearer token for kubectl",
	Long: `Generate a short-lived AKS bearer token from the identity's AAD credentials.

This command is designed to be used as a kubectl exec credential plugin.
It authenticates using the specified identity and outputs an ExecCredential
JSON object to stdout.

The kubeconfig generated by 'atmos azure aks update-kubeconfig' automatically
configures kubectl to call this command for token generation.

Examples:
  # Generate token for a cluster (typically called by kubectl)
  atmos azure aks token --cluster-name my-cluster --resource-group my-rg

  # Generate token using a specific identity
  atmos azure aks token --cluster-name my-cluster --resource-group my-rg --identity dev-admin`,

	FParseErrWhitelist: struct{ UnknownFlags bool }{UnknownFlags: false},
	Args:               cobra.NoArgs,
	RunE:               executeTokenCommand,
	// Suppress usage on errors since kubectl invokes this automatically.
	SilenceUsage: true,
}

// execCredential represents the Kubernetes ExecCredential response.
type execCredential struct {
	APIVersion string               `json:"apiVersion"`
	Kind       string               `json:"kind"`
	Status     execCredentialStatus `json:"status"`
}

// execCredentialStatus contains the token and expiration.
type execCredentialStatus struct {
	ExpirationTimestamp string `json:"expirationTimestamp,omitempty"`
	Token               string `json:"token"`
}

func executeTokenCommand(cmd *cobra.Command, _ []string) error {
	// Load atmos config.
	atmosConfig, err := initCliConfigFn(schema.ConfigAndStacksInfo{}, false)
	if err != nil {
		return fmt.Errorf(errUtils.ErrWrapFormat, errUtils.ErrFailedToInitConfig, err)
	}
	defer perf.Track(&atmosConfig, "aks.executeTokenCommand")()

	req, err := parseTokenRequest(cmd)
	if err != nil {
		return err
	}

	log.Debug("Generating AKS token", "cluster", req.clusterName, "resource_group", req.resourceGroup, "subscription_id", req.subscriptionID, "identity", req.identityName)

	// Authenticate to get credentials.
	// Skip integrations to avoid rewriting the kubeconfig during token generation.
	ctx := auth.ContextWithSkipIntegrations(context.Background())
	creds, err := authenticateForTokenFn(ctx, &atmosConfig.Auth, atmosConfig.CliConfigPath, req.identityName)
	if err != nil {
		return fmt.Errorf("%w: %w", errUtils.ErrAKSTokenGeneration, err)
	}

	// Generate token.
	token, expiresAt, err := getAKSTokenFn(creds)
	if err != nil {
		return fmt.Errorf("%w: %w", errUtils.ErrAKSTokenGeneration, err)
	}

	return writeExecCredential(token, expiresAt)
}

// tokenRequest bundles the parsed cluster-name/resource-group/subscription-id/
// identity flags for the token command, returned by parseTokenRequest.
type tokenRequest struct {
	clusterName    string
	resourceGroup  string
	subscriptionID string
	identityName   string
}

// parseTokenRequest extracts and validates the cluster-name/resource-group/
// subscription-id/identity flags for the token command.
// --cluster-name/--resource-group/--subscription-id are accepted (and
// required to parse successfully) because the kubeconfig exec plugin always
// passes them, but the current token generation path (GetToken) only needs
// the already-authenticated identity's cached AKS-scoped token — they're
// surfaced here for debug logging only.
func parseTokenRequest(cmd *cobra.Command) (tokenRequest, error) {
	clusterName, _ := cmd.Flags().GetString("cluster-name")
	resourceGroup, _ := cmd.Flags().GetString("resource-group")
	subscriptionID, _ := cmd.Flags().GetString("subscription-id")

	if clusterName == "" {
		return tokenRequest{}, fmt.Errorf("%w: --cluster-name is required", errUtils.ErrAKSTokenGeneration)
	}

	if resourceGroup == "" {
		return tokenRequest{}, fmt.Errorf("%w: --resource-group is required", errUtils.ErrAKSTokenGeneration)
	}

	// Resolve identity: flag > env var > default.
	identityName := resolveIdentity(cmd)

	return tokenRequest{
		clusterName:    clusterName,
		resourceGroup:  resourceGroup,
		subscriptionID: subscriptionID,
		identityName:   identityName,
	}, nil
}

// writeExecCredential builds the Kubernetes ExecCredential JSON payload for
// a generated token and writes it to stdout.
func writeExecCredential(token string, expiresAt time.Time) error {
	status := execCredentialStatus{Token: token}
	if !expiresAt.IsZero() {
		status.ExpirationTimestamp = expiresAt.UTC().Format(time.RFC3339)
	}

	credential := execCredential{
		APIVersion: execCredentialAPIVersion,
		Kind:       "ExecCredential",
		Status:     status,
	}

	output, err := json.Marshal(credential)
	if err != nil {
		return fmt.Errorf("%w: failed to marshal ExecCredential: %w", errUtils.ErrAKSTokenGeneration, err)
	}

	return data.Write(string(output))
}

// resolveIdentity resolves the identity name from flag, env var, or returns empty.
func resolveIdentity(cmd *cobra.Command) string {
	// Check flag first.
	identity, _ := cmd.Flags().GetString("identity")
	if identity != "" {
		return identity
	}

	// Fall back to environment variable.
	if envIdentity := os.Getenv("ATMOS_IDENTITY"); envIdentity != "" { //nolint:forbidigo // Direct env var read to avoid viper config pollution
		return envIdentity
	}

	return ""
}

// authenticateForToken authenticates an identity and returns credentials.
func authenticateForToken(ctx context.Context, authConfig *schema.AuthConfig, cliConfigPath, identityName string) (types.ICredentials, error) {
	defer perf.Track(nil, "aks.authenticateForToken")()

	authStackInfo := &schema.ConfigAndStacksInfo{
		AuthContext: &schema.AuthContext{},
	}

	credStore := credentials.NewCredentialStoreWithConfig(authConfig)
	validator := validation.NewValidator()

	mgr, err := auth.NewAuthManager(authConfig, credStore, validator, authStackInfo, cliConfigPath)
	if err != nil {
		return nil, fmt.Errorf(errUtils.ErrWrapFormat, errUtils.ErrFailedToInitializeAuthManager, err)
	}

	// If no identity specified, try to resolve default.
	if identityName == "" {
		identityName = resolveDefaultIdentity(authConfig)
		if identityName == "" {
			return nil, fmt.Errorf("%w: no identity specified and no default identity found", errUtils.ErrAKSTokenGeneration)
		}
	}

	whoami, err := mgr.Authenticate(ctx, identityName)
	if err != nil {
		return nil, fmt.Errorf(errUtils.ErrWrapWithNameAndCauseFormat, errUtils.ErrIdentityAuthFailed, identityName, err)
	}

	if whoami.Credentials == nil {
		return nil, fmt.Errorf(errUtils.ErrWrapWithNameAndCauseFormat, errUtils.ErrIdentityAuthFailed, identityName, errUtils.ErrIdentityCredentialsNone)
	}

	return whoami.Credentials, nil
}

// resolveDefaultIdentity finds a default identity from the auth config.
func resolveDefaultIdentity(authConfig *schema.AuthConfig) string {
	if authConfig == nil || len(authConfig.Identities) == 0 {
		return ""
	}

	// If there's only one identity, use it.
	if len(authConfig.Identities) == 1 {
		for name := range authConfig.Identities {
			return name
		}
	}

	return ""
}

func init() {
	tokenCmd.Flags().String("cluster-name", "", "AKS cluster name (required)")
	tokenCmd.Flags().String("resource-group", "", "Azure resource group (required)")
	tokenCmd.Flags().String("subscription-id", "", "Azure subscription ID (optional, falls back to identity's subscription)")
	tokenCmd.Flags().StringP("identity", "i", "", "Atmos identity to authenticate with")
	AksCmd.AddCommand(tokenCmd)
}
