// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mock_interfaces_test.go -package=workflow
//

// Package workflow is a generated GoMock package.
package workflow

import (
	context "context"
	reflect "reflect"

	schema "github.com/cloudposse/atmos/pkg/schema"
	gomock "go.uber.org/mock/gomock"
)

// MockCommandRunner is a mock of CommandRunner interface.
type MockCommandRunner struct {
	ctrl     *gomock.Controller
	recorder *MockCommandRunnerMockRecorder
	isgomock struct{}
}

// MockCommandRunnerMockRecorder is the mock recorder for MockCommandRunner.
type MockCommandRunnerMockRecorder struct {
	mock *MockCommandRunner
}

// NewMockCommandRunner creates a new mock instance.
func NewMockCommandRunner(ctrl *gomock.Controller) *MockCommandRunner {
	mock := &MockCommandRunner{ctrl: ctrl}
	mock.recorder = &MockCommandRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandRunner) EXPECT() *MockCommandRunnerMockRecorder {
	return m.recorder
}

// RunAtmos mocks base method.
func (m *MockCommandRunner) RunAtmos(params *AtmosExecParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunAtmos", params)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunAtmos indicates an expected call of RunAtmos.
func (mr *MockCommandRunnerMockRecorder) RunAtmos(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunAtmos", reflect.TypeOf((*MockCommandRunner)(nil).RunAtmos), params)
}

// RunShell mocks base method.
func (m *MockCommandRunner) RunShell(command, name, dir string, env []string, dryRun bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunShell", command, name, dir, env, dryRun)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunShell indicates an expected call of RunShell.
func (mr *MockCommandRunnerMockRecorder) RunShell(command, name, dir, env, dryRun any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunShell", reflect.TypeOf((*MockCommandRunner)(nil).RunShell), command, name, dir, env, dryRun)
}

// MockAuthProvider is a mock of AuthProvider interface.
type MockAuthProvider struct {
	ctrl     *gomock.Controller
	recorder *MockAuthProviderMockRecorder
	isgomock struct{}
}

// MockAuthProviderMockRecorder is the mock recorder for MockAuthProvider.
type MockAuthProviderMockRecorder struct {
	mock *MockAuthProvider
}

// NewMockAuthProvider creates a new mock instance.
func NewMockAuthProvider(ctrl *gomock.Controller) *MockAuthProvider {
	mock := &MockAuthProvider{ctrl: ctrl}
	mock.recorder = &MockAuthProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthProvider) EXPECT() *MockAuthProviderMockRecorder {
	return m.recorder
}

// Authenticate mocks base method.
func (m *MockAuthProvider) Authenticate(ctx context.Context, identity string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate", ctx, identity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Authenticate indicates an expected call of Authenticate.
func (mr *MockAuthProviderMockRecorder) Authenticate(ctx, identity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockAuthProvider)(nil).Authenticate), ctx, identity)
}

// GetCachedCredentials mocks base method.
func (m *MockAuthProvider) GetCachedCredentials(ctx context.Context, identity string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCachedCredentials", ctx, identity)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCachedCredentials indicates an expected call of GetCachedCredentials.
func (mr *MockAuthProviderMockRecorder) GetCachedCredentials(ctx, identity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCachedCredentials", reflect.TypeOf((*MockAuthProvider)(nil).GetCachedCredentials), ctx, identity)
}

// NeedsAuth mocks base method.
func (m *MockAuthProvider) NeedsAuth(steps []schema.WorkflowStep, commandLineIdentity string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NeedsAuth", steps, commandLineIdentity)
	ret0, _ := ret[0].(bool)
	return ret0
}

// NeedsAuth indicates an expected call of NeedsAuth.
func (mr *MockAuthProviderMockRecorder) NeedsAuth(steps, commandLineIdentity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NeedsAuth", reflect.TypeOf((*MockAuthProvider)(nil).NeedsAuth), steps, commandLineIdentity)
}

// PrepareEnvironment mocks base method.
func (m *MockAuthProvider) PrepareEnvironment(ctx context.Context, identity string, baseEnv []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareEnvironment", ctx, identity, baseEnv)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrepareEnvironment indicates an expected call of PrepareEnvironment.
func (mr *MockAuthProviderMockRecorder) PrepareEnvironment(ctx, identity, baseEnv any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareEnvironment", reflect.TypeOf((*MockAuthProvider)(nil).PrepareEnvironment), ctx, identity, baseEnv)
}

// MockWorkflowLoader is a mock of WorkflowLoader interface.
type MockWorkflowLoader struct {
	ctrl     *gomock.Controller
	recorder *MockWorkflowLoaderMockRecorder
	isgomock struct{}
}

// MockWorkflowLoaderMockRecorder is the mock recorder for MockWorkflowLoader.
type MockWorkflowLoaderMockRecorder struct {
	mock *MockWorkflowLoader
}

// NewMockWorkflowLoader creates a new mock instance.
func NewMockWorkflowLoader(ctrl *gomock.Controller) *MockWorkflowLoader {
	mock := &MockWorkflowLoader{ctrl: ctrl}
	mock.recorder = &MockWorkflowLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkflowLoader) EXPECT() *MockWorkflowLoaderMockRecorder {
	return m.recorder
}

// ListWorkflows mocks base method.
func (m *MockWorkflowLoader) ListWorkflows(atmosConfig *schema.AtmosConfiguration) ([]schema.DescribeWorkflowsItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWorkflows", atmosConfig)
	ret0, _ := ret[0].([]schema.DescribeWorkflowsItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWorkflows indicates an expected call of ListWorkflows.
func (mr *MockWorkflowLoaderMockRecorder) ListWorkflows(atmosConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWorkflows", reflect.TypeOf((*MockWorkflowLoader)(nil).ListWorkflows), atmosConfig)
}

// LoadWorkflow mocks base method.
func (m *MockWorkflowLoader) LoadWorkflow(atmosConfig *schema.AtmosConfiguration, workflowPath, workflowName string) (*schema.WorkflowDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadWorkflow", atmosConfig, workflowPath, workflowName)
	ret0, _ := ret[0].(*schema.WorkflowDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadWorkflow indicates an expected call of LoadWorkflow.
func (mr *MockWorkflowLoaderMockRecorder) LoadWorkflow(atmosConfig, workflowPath, workflowName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadWorkflow", reflect.TypeOf((*MockWorkflowLoader)(nil).LoadWorkflow), atmosConfig, workflowPath, workflowName)
}

// MockUIProvider is a mock of UIProvider interface.
type MockUIProvider struct {
	ctrl     *gomock.Controller
	recorder *MockUIProviderMockRecorder
	isgomock struct{}
}

// MockUIProviderMockRecorder is the mock recorder for MockUIProvider.
type MockUIProviderMockRecorder struct {
	mock *MockUIProvider
}

// NewMockUIProvider creates a new mock instance.
func NewMockUIProvider(ctrl *gomock.Controller) *MockUIProvider {
	mock := &MockUIProvider{ctrl: ctrl}
	mock.recorder = &MockUIProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUIProvider) EXPECT() *MockUIProviderMockRecorder {
	return m.recorder
}

// PrintError mocks base method.
func (m *MockUIProvider) PrintError(err error, title, explanation string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PrintError", err, title, explanation)
}

// PrintError indicates an expected call of PrintError.
func (mr *MockUIProviderMockRecorder) PrintError(err, title, explanation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrintError", reflect.TypeOf((*MockUIProvider)(nil).PrintError), err, title, explanation)
}

// PrintMessage mocks base method.
func (m *MockUIProvider) PrintMessage(format string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "PrintMessage", varargs...)
}

// PrintMessage indicates an expected call of PrintMessage.
func (mr *MockUIProviderMockRecorder) PrintMessage(format any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrintMessage", reflect.TypeOf((*MockUIProvider)(nil).PrintMessage), varargs...)
}
