package installer

import (
	"os"
	"path/filepath"
	"runtime"
	"time"

	"gopkg.in/yaml.v3"

	"github.com/cloudposse/atmos/pkg/schema"
	"github.com/cloudposse/atmos/pkg/toolchain/registry"
	"github.com/cloudposse/atmos/pkg/toolchain/verification"
)

func resolveLockFilePath(config *schema.AtmosConfiguration) string {
	if config == nil {
		return ""
	}
	if config.Toolchain.LockFile != "" {
		return config.Toolchain.LockFile
	}
	installPath := config.Toolchain.InstallPath
	if installPath == "" {
		installPath = ".tools"
	}
	return filepath.Join(installPath, "toolchain.lock.yaml")
}

func (i *Installer) updateLockFile(tool *registry.Tool, version, assetURL string, result *verification.Result) error {
	if !i.useLockFile || i.lockFilePath == "" || result == nil || result.Checksum == "" {
		return nil
	}
	lf, err := loadInstallerLockFile(i.lockFilePath)
	if err != nil {
		if !os.IsNotExist(err) {
			return err
		}
		lf = newInstallerLockFile()
	}
	toolName := tool.RepoOwner + "/" + tool.RepoName
	entry := lf.getOrCreateTool(toolName)
	entry.Version = version
	entry.Source = tool.Registry
	entry.BinaryName = tool.BinaryName
	platform := runtime.GOOS + "_" + runtime.GOARCH
	entry.Platforms[platform] = &installerLockPlatform{
		URL:               assetURL,
		Checksum:          result.Checksum,
		Size:              result.AssetSize,
		ChecksumAlgorithm: result.ChecksumAlgorithm,
		Verification:      result.SignatureMethods,
	}
	return saveInstallerLockFile(i.lockFilePath, lf)
}

type installerLockFile struct {
	Version  int                           `yaml:"version"`
	Tools    map[string]*installerLockTool `yaml:"tools"`
	Metadata installerLockFileMetadata     `yaml:"metadata"`
}

type installerLockTool struct {
	Version     string                            `yaml:"version"`
	Source      string                            `yaml:"source,omitempty"`
	Platforms   map[string]*installerLockPlatform `yaml:"platforms"`
	BinaryName  string                            `yaml:"binary_name,omitempty"`
	InstalledAt string                            `yaml:"installed_at"`
}

type installerLockPlatform struct {
	URL               string   `yaml:"url"`
	Checksum          string   `yaml:"checksum"`
	Size              int64    `yaml:"size"`
	ChecksumAlgorithm string   `yaml:"checksum_algorithm,omitempty"`
	Verification      []string `yaml:"verification,omitempty"`
}

type installerLockFileMetadata struct {
	GeneratedAt     string `yaml:"generated_at"`
	AtmosVersion    string `yaml:"atmos_version"`
	Platform        string `yaml:"platform"`
	LockFileVersion int    `yaml:"lock_file_version"`
}

func newInstallerLockFile() *installerLockFile {
	return &installerLockFile{
		Version: 1,
		Tools:   make(map[string]*installerLockTool),
		Metadata: installerLockFileMetadata{
			GeneratedAt:     time.Now().UTC().Format(time.RFC3339),
			AtmosVersion:    "unknown",
			Platform:        runtime.GOOS + "_" + runtime.GOARCH,
			LockFileVersion: 1,
		},
	}
}

func loadInstallerLockFile(filePath string) (*installerLockFile, error) {
	data, err := os.ReadFile(filePath)
	if err != nil {
		return nil, err
	}
	var lf installerLockFile
	if err := yaml.Unmarshal(data, &lf); err != nil {
		return nil, err
	}
	if lf.Tools == nil {
		lf.Tools = make(map[string]*installerLockTool)
	}
	return &lf, nil
}

func saveInstallerLockFile(filePath string, lf *installerLockFile) error {
	lf.Metadata.GeneratedAt = time.Now().UTC().Format(time.RFC3339)
	lf.Metadata.Platform = runtime.GOOS + "_" + runtime.GOARCH
	if lf.Metadata.LockFileVersion == 0 {
		lf.Metadata.LockFileVersion = 1
	}
	if lf.Version == 0 {
		lf.Version = 1
	}
	data, err := yaml.Marshal(lf)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(filePath), defaultMkdirPermissions); err != nil {
		return err
	}
	header := "# Generated by Atmos Toolchain\n# This file locks tool versions and checksums for reproducible installations\n# Do not edit manually - run 'atmos toolchain lock' to update\n\n"
	return os.WriteFile(filePath, []byte(header+string(data)), defaultFileWritePermissions)
}

func (lf *installerLockFile) getOrCreateTool(name string) *installerLockTool {
	if lf.Tools == nil {
		lf.Tools = make(map[string]*installerLockTool)
	}
	if tool, ok := lf.Tools[name]; ok {
		if tool.Platforms == nil {
			tool.Platforms = make(map[string]*installerLockPlatform)
		}
		return tool
	}
	tool := &installerLockTool{
		Platforms:   make(map[string]*installerLockPlatform),
		InstalledAt: time.Now().UTC().Format(time.RFC3339),
	}
	lf.Tools[name] = tool
	return tool
}
