// Package hooks implements Atmos-managed Git hook shims: writing shim scripts
// into .git/hooks that delegate to `atmos git hooks run`, removing them, and
// executing the configured command for a named hook.
package hooks

import (
	"os"
	"path/filepath"
	"sort"
	"strings"

	errUtils "github.com/cloudposse/atmos/errors"
	"github.com/cloudposse/atmos/pkg/schema"
)

const (
	// ShimMarker is the unique string embedded in generated shim files.
	// Its presence identifies a file as Atmos-managed.
	ShimMarker = "# Generated by Atmos. Do not edit."

	// Permission for generated hook shim files (rwxr-xr-x).
	shimPerm = 0o755

	// Permission for the .git/hooks directory.
	hooksDirPerm = 0o755
)

// ShimContent returns the generated shim content for a given hook name. The shim finds atmos on
// PATH.
func ShimContent(hookName string) string {
	return ShimContentFor(hookName, "")
}

// ShimContentFor returns the generated shim content for a hook, pinned to the atmos binary that
// installed it. The shim runs that absolute path when it is still executable, so a hook keeps
// working from an IDE, a GUI Git client, or a cron job whose PATH does not include atmos, and it
// falls back to PATH when the binary has moved or been removed. An empty atmosPath yields the
// PATH-only shim.
func ShimContentFor(hookName, atmosPath string) string {
	if atmosPath == "" {
		return "#!/bin/sh\n" + ShimMarker + "\nexec atmos git hooks run " + hookName + " \"$@\"\n"
	}
	return "#!/bin/sh\n" + ShimMarker + "\n" +
		"atmos_bin=" + shellSingleQuote(atmosPath) + "\n" +
		"[ -x \"$atmos_bin\" ] || atmos_bin=atmos\n" +
		"exec \"$atmos_bin\" git hooks run " + hookName + " \"$@\"\n"
}

// shellSingleQuote quotes value for a POSIX shell.
func shellSingleQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", `'\''`) + "'"
}

// installedAtmosPath returns the absolute path of the running atmos binary for the shim, or "" when
// it cannot be determined (the shim then relies on PATH). It is a variable so tests can fix it.
var installedAtmosPath = func() string {
	path, err := os.Executable()
	if err != nil {
		return ""
	}
	abs, err := filepath.Abs(path)
	if err != nil {
		return ""
	}
	// Forward slashes keep a Windows path valid for the POSIX shell that runs the shim.
	return filepath.ToSlash(abs)
}

// NotConfiguredError builds an ErrGitHookNotConfigured error with a hint
// listing configured hook names.
func NotConfiguredError(hookName string, hooks map[string]schema.GitHookEntry) error {
	b := errUtils.Build(errUtils.ErrGitHookNotConfigured).
		WithHintf("Hook %q is not configured under git.hooks in atmos.yaml.", hookName).
		WithExitCode(2)

	if len(hooks) == 0 {
		b = b.WithHint("No hooks are currently configured under git.hooks.")
	} else {
		b = b.WithHintf("Configured hooks: %s.", strings.Join(SortedNames(hooks), ", "))
	}

	return b.Err()
}

// SortedNames returns the configured hook names in ascending order.
func SortedNames(m map[string]schema.GitHookEntry) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// ValidateShimName rejects hook names that could escape .git/hooks.
func ValidateShimName(hookName string) error {
	if hookName == "" || hookName == "." || hookName == ".." || filepath.IsAbs(hookName) || strings.ContainsAny(hookName, `/\`) {
		return invalidShimNameErr(hookName)
	}

	for _, r := range hookName {
		if !isShimNameChar(r) {
			return invalidShimNameErr(hookName)
		}
	}

	return nil
}

func isShimNameChar(r rune) bool {
	return r == '.' || r == '_' || r == '-' ||
		(r >= 'a' && r <= 'z') ||
		(r >= 'A' && r <= 'Z') ||
		(r >= '0' && r <= '9')
}

func invalidShimNameErr(hookName string) error {
	return errUtils.Build(errUtils.ErrInvalidConfig).
		WithHintf("Hook name %q must be a simple filename using only letters, digits, '.', '_' or '-'.", hookName).
		WithHint("Hook names must not be absolute paths, '.', '..', or contain path separators.").
		WithExitCode(2).
		Err()
}

// hookNamesOrConfigured returns names, falling back to all configured hooks.
func hookNamesOrConfigured(names []string, cfg *schema.GitConfig) []string {
	if len(names) > 0 || cfg == nil {
		return names
	}
	return SortedNames(cfg.Hooks)
}
