package hooks

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	errUtils "github.com/cloudposse/atmos/errors"
	atmosgit "github.com/cloudposse/atmos/pkg/git"
	"github.com/cloudposse/atmos/pkg/perf"
	"github.com/cloudposse/atmos/pkg/schema"
	"github.com/cloudposse/atmos/pkg/ui"
)

// Install writes shim scripts into .git/hooks for the named hooks (all
// configured hooks when names is empty). Existing non-Atmos files are only
// overwritten when force is set.
func Install(ctx context.Context, cfg *schema.GitConfig, names []string, force bool) error {
	defer perf.Track(nil, "hooks.Install")()

	// Validate requested names against config before touching the filesystem.
	if err := validateHookNames(names, cfg); err != nil {
		return err
	}

	// Warn when core.hooksPath is set; Git ignores .git/hooks in that case.
	warnIfHooksPathSet(ctx)

	hooksDir, err := resolveHooksDir(ctx)
	if err != nil {
		return err
	}

	hookNames := hookNamesOrConfigured(names, cfg)
	if len(hookNames) == 0 {
		ui.Info("No hooks configured under git.hooks in atmos.yaml.")
		return nil
	}

	for _, name := range hookNames {
		if err := installHook(hooksDir, name, force); err != nil {
			return err
		}
	}

	return nil
}

// installHook writes a single shim file for hookName into hooksDir.
func installHook(hooksDir, hookName string, force bool) error {
	if err := ValidateShimName(hookName); err != nil {
		return err
	}

	dest := filepath.Join(hooksDir, hookName)
	shim := ShimContent(hookName)

	// Check if the file already exists.
	existing, err := os.ReadFile(dest)
	if err == nil {
		// File exists; overwrite only if Atmos-managed or --force is set.
		if !strings.Contains(string(existing), ShimMarker) && !force {
			return errUtils.Build(errUtils.ErrInvalidConfig).
				WithHintf("Hook file %q already exists and was not generated by Atmos.", dest).
				WithHint("Pass --force to overwrite it.").
				WithExitCode(2).
				Err()
		}
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("checking existing hook %q: %w", dest, err)
	}

	// Ensure the hooks directory exists.
	if mkErr := os.MkdirAll(hooksDir, hooksDirPerm); mkErr != nil {
		return fmt.Errorf("creating hooks directory %q: %w", hooksDir, mkErr)
	}

	if writeErr := os.WriteFile(dest, []byte(shim), shimPerm); writeErr != nil {
		return fmt.Errorf("writing hook shim %q: %w", dest, writeErr)
	}
	if chmodErr := os.Chmod(dest, shimPerm); chmodErr != nil {
		return fmt.Errorf("setting executable permission on hook shim %q: %w", dest, chmodErr)
	}

	ui.Successf("Installed hook shim: %s", dest)
	return nil
}

// resolveHooksDir returns the absolute path to the .git/hooks directory,
// correctly handling linked worktrees where hooks live in the common dir.
func resolveHooksDir(ctx context.Context) (string, error) {
	defer perf.Track(nil, "hooks.resolveHooksDir")()

	runner := atmosgit.NewExecRunner()
	result, err := runner.Run(ctx, "git", []string{"rev-parse", "--git-path", "hooks"}, atmosgit.RunOptions{})
	if err != nil {
		return "", errUtils.Build(errUtils.ErrNotInGitRepository).
			WithHint("Run 'atmos git hooks install' from inside a Git repository.").
			WithExitCode(2).
			Err()
	}

	dir := strings.TrimSpace(result.Stdout)
	if dir == "" {
		return "", errUtils.Build(errUtils.ErrNotInGitRepository).
			WithHint("'git rev-parse --git-path hooks' returned an empty path.").
			WithExitCode(2).
			Err()
	}

	abs, err := filepath.Abs(dir)
	if err != nil {
		return "", fmt.Errorf("resolving hooks directory path %q: %w", dir, err)
	}

	return abs, nil
}

// warnIfHooksPathSet emits a ui.Warning when core.hooksPath is configured,
// because Git ignores .git/hooks when that setting is present.
// Returns without warning when core.hooksPath is not configured.
func warnIfHooksPathSet(ctx context.Context) {
	runner := atmosgit.NewExecRunner()
	result, err := runner.Run(ctx, "git", []string{"config", "--get", "core.hooksPath"}, atmosgit.RunOptions{})
	if err != nil {
		// Non-zero exit from git config --get means the key is not set.
		return
	}

	hooksPath := strings.TrimSpace(result.Stdout)
	if hooksPath != "" {
		ui.Warningf(
			"core.hooksPath is set to %q (e.g. by Husky). Git will ignore .git/hooks shims; install them into %q instead, or remove core.hooksPath.",
			hooksPath, hooksPath,
		)
	}
}

// validateHookNames ensures all requested hook names are configured.
func validateHookNames(names []string, cfg *schema.GitConfig) error {
	if len(names) == 0 {
		return nil
	}

	for _, name := range names {
		if cfg == nil || cfg.Hooks == nil {
			return NotConfiguredError(name, nil)
		}
		if _, ok := cfg.Hooks[name]; !ok {
			return NotConfiguredError(name, cfg.Hooks)
		}
	}

	return nil
}
