package git

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"

	"github.com/cloudposse/atmos/pkg/perf"
	"github.com/cloudposse/atmos/pkg/ui"
)

// hooksUninstallCmd is the `atmos git hooks uninstall` subcommand.
var hooksUninstallCmd = &cobra.Command{
	Use:   "uninstall [hook-name...]",
	Short: "Remove Atmos-managed Git hook shims",
	Long: `Remove .git/hooks shim scripts that were generated by Atmos.

Without hook names, removes shims for all configured hooks.
With hook names, removes only the named hooks.

Only files containing the Atmos marker line are removed. User-authored hooks
are left unchanged and a warning is emitted.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		defer perf.Track(atmosConfigPtr, "git.hooks.uninstall.RunE")()

		return runHooksUninstall(cmd.Context(), args)
	},
}

// runHooksUninstall implements `atmos git hooks uninstall`.
func runHooksUninstall(ctx context.Context, names []string) error {
	defer perf.Track(nil, "git.runHooksUninstall")()

	cfg := gitConfig()

	hooksDir, err := resolveHooksDir(ctx)
	if err != nil {
		return err
	}

	// Determine which hooks to uninstall.
	hookNames := names
	if len(hookNames) == 0 && cfg != nil {
		hookNames = sortedKeys(cfg.Hooks)
	}

	if len(hookNames) == 0 {
		ui.Info("No hooks configured under git.hooks in atmos.yaml.")
		return nil
	}

	for _, name := range hookNames {
		if err := uninstallHook(hooksDir, name); err != nil {
			return err
		}
	}

	return nil
}

// uninstallHook removes the shim for hookName from hooksDir, only if it is
// an Atmos-generated file. User-authored hooks are never deleted.
func uninstallHook(hooksDir, hookName string) error {
	if err := validateHookShimName(hookName); err != nil {
		return err
	}

	dest := filepath.Join(hooksDir, hookName)

	content, err := os.ReadFile(dest)
	if os.IsNotExist(err) {
		// Already gone; treat as a no-op.
		return nil
	}
	if err != nil {
		return fmt.Errorf("reading hook file %q: %w", dest, err)
	}

	if !strings.Contains(string(content), atmosShimMarker) {
		ui.Warningf(
			"Skipping %q: not an Atmos-generated shim (marker not found). Remove it manually if needed.",
			dest,
		)
		return nil
	}

	if err := os.Remove(dest); err != nil {
		return fmt.Errorf("removing hook shim %q: %w", dest, err)
	}

	ui.Successf("Removed hook shim: %s", dest)
	return nil
}
