// Code generated by MockGen. DO NOT EDIT.
// Source: backend_helpers.go
//
// Generated by this command:
//
//	mockgen -source=backend_helpers.go -destination=mock_backend_helpers_test.go -package=backend
//

// Package backend is a generated GoMock package.
package backend

import (
	context "context"
	reflect "reflect"

	schema "github.com/cloudposse/atmos/pkg/schema"
	gomock "go.uber.org/mock/gomock"
)

// MockConfigInitializer is a mock of ConfigInitializer interface.
type MockConfigInitializer struct {
	ctrl     *gomock.Controller
	recorder *MockConfigInitializerMockRecorder
	isgomock struct{}
}

// MockConfigInitializerMockRecorder is the mock recorder for MockConfigInitializer.
type MockConfigInitializerMockRecorder struct {
	mock *MockConfigInitializer
}

// NewMockConfigInitializer creates a new mock instance.
func NewMockConfigInitializer(ctrl *gomock.Controller) *MockConfigInitializer {
	mock := &MockConfigInitializer{ctrl: ctrl}
	mock.recorder = &MockConfigInitializerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigInitializer) EXPECT() *MockConfigInitializerMockRecorder {
	return m.recorder
}

// DescribeComponent mocks base method.
func (m *MockConfigInitializer) DescribeComponent(atmosConfig *schema.AtmosConfiguration, info *schema.ConfigAndStacksInfo, component, stack string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeComponent", atmosConfig, info, component, stack)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeComponent indicates an expected call of DescribeComponent.
func (mr *MockConfigInitializerMockRecorder) DescribeComponent(atmosConfig, info, component, stack any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeComponent", reflect.TypeOf((*MockConfigInitializer)(nil).DescribeComponent), atmosConfig, info, component, stack)
}

// InitConfigAndAuth mocks base method.
func (m *MockConfigInitializer) InitConfigAndAuth(component, stack, identity string) (*schema.AtmosConfiguration, *schema.ConfigAndStacksInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitConfigAndAuth", component, stack, identity)
	ret0, _ := ret[0].(*schema.AtmosConfiguration)
	ret1, _ := ret[1].(*schema.ConfigAndStacksInfo)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// InitConfigAndAuth indicates an expected call of InitConfigAndAuth.
func (mr *MockConfigInitializerMockRecorder) InitConfigAndAuth(component, stack, identity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitConfigAndAuth", reflect.TypeOf((*MockConfigInitializer)(nil).InitConfigAndAuth), component, stack, identity)
}

// MockProvisioner is a mock of Provisioner interface.
type MockProvisioner struct {
	ctrl     *gomock.Controller
	recorder *MockProvisionerMockRecorder
	isgomock struct{}
}

// MockProvisionerMockRecorder is the mock recorder for MockProvisioner.
type MockProvisionerMockRecorder struct {
	mock *MockProvisioner
}

// NewMockProvisioner creates a new mock instance.
func NewMockProvisioner(ctrl *gomock.Controller) *MockProvisioner {
	mock := &MockProvisioner{ctrl: ctrl}
	mock.recorder = &MockProvisionerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvisioner) EXPECT() *MockProvisionerMockRecorder {
	return m.recorder
}

// CreateBackend mocks base method.
func (m *MockProvisioner) CreateBackend(ctx context.Context, params *CreateBackendParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBackend", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBackend indicates an expected call of CreateBackend.
func (mr *MockProvisionerMockRecorder) CreateBackend(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBackend", reflect.TypeOf((*MockProvisioner)(nil).CreateBackend), ctx, params)
}

// DeleteBackend mocks base method.
func (m *MockProvisioner) DeleteBackend(ctx context.Context, params *DeleteBackendParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBackend", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBackend indicates an expected call of DeleteBackend.
func (mr *MockProvisionerMockRecorder) DeleteBackend(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBackend", reflect.TypeOf((*MockProvisioner)(nil).DeleteBackend), ctx, params)
}

// DescribeBackend mocks base method.
func (m *MockProvisioner) DescribeBackend(ctx context.Context, params *DescribeBackendParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeBackend", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// DescribeBackend indicates an expected call of DescribeBackend.
func (mr *MockProvisionerMockRecorder) DescribeBackend(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeBackend", reflect.TypeOf((*MockProvisioner)(nil).DescribeBackend), ctx, params)
}

// ListBackends mocks base method.
func (m *MockProvisioner) ListBackends(ctx context.Context, params *ListBackendsParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBackends", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// ListBackends indicates an expected call of ListBackends.
func (mr *MockProvisionerMockRecorder) ListBackends(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBackends", reflect.TypeOf((*MockProvisioner)(nil).ListBackends), ctx, params)
}
