# VHS Defaults

Set Theme "Monokai Vivid"

Set FontFamily "FiraCode Nerd Font"
#Set FontFamily "Hack Nerd Font"
Set FontSize 14

Set TypingSpeed 40ms

Set WindowBar Colorful

Set BorderRadius 8

Set Margin 0

Set Padding 10

Set Width 1400
Set Height 800

Set Shell "bash"

# VHS Defaults for Recordings

Set Framerate 30
Set CursorBlink true
Set Margin 20
Set MarginFill "#674EFF"

Set Width 1400
Set Height 800

Set PlaybackSpeed 1

Set Framerate 30
