// Code generated by MockGen. DO NOT EDIT.
// Source: describe_locals.go
//
// Generated by this command:
//
//	mockgen -source=describe_locals.go -destination=mock_describe_locals.go -package=exec
//

// Package exec is a generated GoMock package.
package exec

import (
	reflect "reflect"

	schema "github.com/cloudposse/atmos/pkg/schema"
	gomock "go.uber.org/mock/gomock"
)

// MockDescribeLocalsExec is a mock of DescribeLocalsExec interface.
type MockDescribeLocalsExec struct {
	ctrl     *gomock.Controller
	recorder *MockDescribeLocalsExecMockRecorder
	isgomock struct{}
}

// MockDescribeLocalsExecMockRecorder is the mock recorder for MockDescribeLocalsExec.
type MockDescribeLocalsExecMockRecorder struct {
	mock *MockDescribeLocalsExec
}

// NewMockDescribeLocalsExec creates a new mock instance.
func NewMockDescribeLocalsExec(ctrl *gomock.Controller) *MockDescribeLocalsExec {
	mock := &MockDescribeLocalsExec{ctrl: ctrl}
	mock.recorder = &MockDescribeLocalsExecMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDescribeLocalsExec) EXPECT() *MockDescribeLocalsExecMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockDescribeLocalsExec) Execute(atmosConfig *schema.AtmosConfiguration, args *DescribeLocalsArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", atmosConfig, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockDescribeLocalsExecMockRecorder) Execute(atmosConfig, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockDescribeLocalsExec)(nil).Execute), atmosConfig, args)
}
