// Code generated by MockGen. DO NOT EDIT.
// Source: template_funcs_component.go
//
// Generated by this command:
//
//	mockgen -source=template_funcs_component.go -destination=mock_template_funcs_component.go -package=exec
//

// Package exec is a generated GoMock package.
package exec

import (
	reflect "reflect"

	schema "github.com/cloudposse/atmos/pkg/schema"
	gomock "go.uber.org/mock/gomock"
)

// MockComponentFuncOutputsExecutor is a mock of ComponentFuncOutputsExecutor interface.
type MockComponentFuncOutputsExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockComponentFuncOutputsExecutorMockRecorder
	isgomock struct{}
}

// MockComponentFuncOutputsExecutorMockRecorder is the mock recorder for MockComponentFuncOutputsExecutor.
type MockComponentFuncOutputsExecutorMockRecorder struct {
	mock *MockComponentFuncOutputsExecutor
}

// NewMockComponentFuncOutputsExecutor creates a new mock instance.
func NewMockComponentFuncOutputsExecutor(ctrl *gomock.Controller) *MockComponentFuncOutputsExecutor {
	mock := &MockComponentFuncOutputsExecutor{ctrl: ctrl}
	mock.recorder = &MockComponentFuncOutputsExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockComponentFuncOutputsExecutor) EXPECT() *MockComponentFuncOutputsExecutorMockRecorder {
	return m.recorder
}

// ExecuteWithSections mocks base method.
func (m *MockComponentFuncOutputsExecutor) ExecuteWithSections(atmosConfig *schema.AtmosConfiguration, component, stack string, sections map[string]any, authContext *schema.AuthContext) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteWithSections", atmosConfig, component, stack, sections, authContext)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteWithSections indicates an expected call of ExecuteWithSections.
func (mr *MockComponentFuncOutputsExecutorMockRecorder) ExecuteWithSections(atmosConfig, component, stack, sections, authContext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteWithSections", reflect.TypeOf((*MockComponentFuncOutputsExecutor)(nil).ExecuteWithSections), atmosConfig, component, stack, sections, authContext)
}
