// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cloudposse/atmos/pkg/terraform/output (interfaces: BackendGenerator)
//
// Generated by this command:
//
//	mockgen -destination=mock_terraform_output_backend_test.go -package=exec github.com/cloudposse/atmos/pkg/terraform/output BackendGenerator
//

// Package exec is a generated GoMock package.
package exec

import (
	reflect "reflect"

	schema "github.com/cloudposse/atmos/pkg/schema"
	output "github.com/cloudposse/atmos/pkg/terraform/output"
	gomock "go.uber.org/mock/gomock"
)

// MockBackendGenerator is a mock of BackendGenerator interface.
type MockBackendGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockBackendGeneratorMockRecorder
	isgomock struct{}
}

// MockBackendGeneratorMockRecorder is the mock recorder for MockBackendGenerator.
type MockBackendGeneratorMockRecorder struct {
	mock *MockBackendGenerator
}

// NewMockBackendGenerator creates a new mock instance.
func NewMockBackendGenerator(ctrl *gomock.Controller) *MockBackendGenerator {
	mock := &MockBackendGenerator{ctrl: ctrl}
	mock.recorder = &MockBackendGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackendGenerator) EXPECT() *MockBackendGeneratorMockRecorder {
	return m.recorder
}

// GenerateBackendIfNeeded mocks base method.
func (m *MockBackendGenerator) GenerateBackendIfNeeded(config *output.ComponentConfig, component, stack string, authContext *schema.AuthContext) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateBackendIfNeeded", config, component, stack, authContext)
	ret0, _ := ret[0].(error)
	return ret0
}

// GenerateBackendIfNeeded indicates an expected call of GenerateBackendIfNeeded.
func (mr *MockBackendGeneratorMockRecorder) GenerateBackendIfNeeded(config, component, stack, authContext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateBackendIfNeeded", reflect.TypeOf((*MockBackendGenerator)(nil).GenerateBackendIfNeeded), config, component, stack, authContext)
}

// GenerateProvidersIfNeeded mocks base method.
func (m *MockBackendGenerator) GenerateProvidersIfNeeded(config *output.ComponentConfig, authContext *schema.AuthContext) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateProvidersIfNeeded", config, authContext)
	ret0, _ := ret[0].(error)
	return ret0
}

// GenerateProvidersIfNeeded indicates an expected call of GenerateProvidersIfNeeded.
func (mr *MockBackendGeneratorMockRecorder) GenerateProvidersIfNeeded(config, authContext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateProvidersIfNeeded", reflect.TypeOf((*MockBackendGenerator)(nil).GenerateProvidersIfNeeded), config, authContext)
}
