// Code generated by MockGen. DO NOT EDIT.
// Source: describe_component.go
//
// Generated by this command:
//
//	mockgen -source=describe_component.go -destination=mock_describe_component.go -package=exec
//

// Package exec is a generated GoMock package.
package exec

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDescribeComponentCmdExec is a mock of DescribeComponentCmdExec interface.
type MockDescribeComponentCmdExec struct {
	ctrl     *gomock.Controller
	recorder *MockDescribeComponentCmdExecMockRecorder
	isgomock struct{}
}

// MockDescribeComponentCmdExecMockRecorder is the mock recorder for MockDescribeComponentCmdExec.
type MockDescribeComponentCmdExecMockRecorder struct {
	mock *MockDescribeComponentCmdExec
}

// NewMockDescribeComponentCmdExec creates a new mock instance.
func NewMockDescribeComponentCmdExec(ctrl *gomock.Controller) *MockDescribeComponentCmdExec {
	mock := &MockDescribeComponentCmdExec{ctrl: ctrl}
	mock.recorder = &MockDescribeComponentCmdExecMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDescribeComponentCmdExec) EXPECT() *MockDescribeComponentCmdExecMockRecorder {
	return m.recorder
}

// ExecuteDescribeComponentCmd mocks base method.
func (m *MockDescribeComponentCmdExec) ExecuteDescribeComponentCmd(describeComponentParams DescribeComponentParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteDescribeComponentCmd", describeComponentParams)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecuteDescribeComponentCmd indicates an expected call of ExecuteDescribeComponentCmd.
func (mr *MockDescribeComponentCmdExecMockRecorder) ExecuteDescribeComponentCmd(describeComponentParams any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteDescribeComponentCmd", reflect.TypeOf((*MockDescribeComponentCmdExec)(nil).ExecuteDescribeComponentCmd), describeComponentParams)
}
