// Code generated by MockGen. DO NOT EDIT.
// Source: cloudformation_output_getter.go
//
// Generated by this command:
//
//	mockgen -source=cloudformation_output_getter.go -destination=mock_cloudformation_output_getter.go -package=exec
//

// Package exec is a generated GoMock package.
package exec

import (
	context "context"
	reflect "reflect"

	schema "github.com/cloudposse/atmos/pkg/schema"
	gomock "go.uber.org/mock/gomock"
)

// MockCloudFormationOutputsGetter is a mock of CloudFormationOutputsGetter interface.
type MockCloudFormationOutputsGetter struct {
	ctrl     *gomock.Controller
	recorder *MockCloudFormationOutputsGetterMockRecorder
	isgomock struct{}
}

// MockCloudFormationOutputsGetterMockRecorder is the mock recorder for MockCloudFormationOutputsGetter.
type MockCloudFormationOutputsGetterMockRecorder struct {
	mock *MockCloudFormationOutputsGetter
}

// NewMockCloudFormationOutputsGetter creates a new mock instance.
func NewMockCloudFormationOutputsGetter(ctrl *gomock.Controller) *MockCloudFormationOutputsGetter {
	mock := &MockCloudFormationOutputsGetter{ctrl: ctrl}
	mock.recorder = &MockCloudFormationOutputsGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCloudFormationOutputsGetter) EXPECT() *MockCloudFormationOutputsGetterMockRecorder {
	return m.recorder
}

// GetOutputs mocks base method.
func (m *MockCloudFormationOutputsGetter) GetOutputs(ctx context.Context, region, stackName string, authContext *schema.AWSAuthContext) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOutputs", ctx, region, stackName, authContext)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOutputs indicates an expected call of GetOutputs.
func (mr *MockCloudFormationOutputsGetterMockRecorder) GetOutputs(ctx, region, stackName, authContext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOutputs", reflect.TypeOf((*MockCloudFormationOutputsGetter)(nil).GetOutputs), ctx, region, stackName, authContext)
}
