// Code generated by MockGen. DO NOT EDIT.
// Source: describe_affected.go
//
// Generated by this command:
//
//	mockgen -source=describe_affected.go -destination=mock_describe_affected.go -package=exec
//

// Package exec is a generated GoMock package.
package exec

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDescribeAffectedExec is a mock of DescribeAffectedExec interface.
type MockDescribeAffectedExec struct {
	ctrl     *gomock.Controller
	recorder *MockDescribeAffectedExecMockRecorder
	isgomock struct{}
}

// MockDescribeAffectedExecMockRecorder is the mock recorder for MockDescribeAffectedExec.
type MockDescribeAffectedExecMockRecorder struct {
	mock *MockDescribeAffectedExec
}

// NewMockDescribeAffectedExec creates a new mock instance.
func NewMockDescribeAffectedExec(ctrl *gomock.Controller) *MockDescribeAffectedExec {
	mock := &MockDescribeAffectedExec{ctrl: ctrl}
	mock.recorder = &MockDescribeAffectedExecMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDescribeAffectedExec) EXPECT() *MockDescribeAffectedExecMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockDescribeAffectedExec) Execute(arg0 *DescribeAffectedCmdArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockDescribeAffectedExecMockRecorder) Execute(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockDescribeAffectedExec)(nil).Execute), arg0)
}
