// Code generated by MockGen. DO NOT EDIT.
// Source: user.go

// Package github is a generated GoMock package.
package github

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDeviceFlowClient is a mock of DeviceFlowClient interface.
type MockDeviceFlowClient struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceFlowClientMockRecorder
}

// MockDeviceFlowClientMockRecorder is the mock recorder for MockDeviceFlowClient.
type MockDeviceFlowClientMockRecorder struct {
	mock *MockDeviceFlowClient
}

// NewMockDeviceFlowClient creates a new mock instance.
func NewMockDeviceFlowClient(ctrl *gomock.Controller) *MockDeviceFlowClient {
	mock := &MockDeviceFlowClient{ctrl: ctrl}
	mock.recorder = &MockDeviceFlowClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceFlowClient) EXPECT() *MockDeviceFlowClientMockRecorder {
	return m.recorder
}

// PollForToken mocks base method.
func (m *MockDeviceFlowClient) PollForToken(ctx context.Context, deviceCode string, interval int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PollForToken", ctx, deviceCode, interval)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PollForToken indicates an expected call of PollForToken.
func (mr *MockDeviceFlowClientMockRecorder) PollForToken(ctx, deviceCode, interval interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PollForToken", reflect.TypeOf((*MockDeviceFlowClient)(nil).PollForToken), ctx, deviceCode, interval)
}

// StartDeviceFlow mocks base method.
func (m *MockDeviceFlowClient) StartDeviceFlow(ctx context.Context) (*DeviceFlowResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartDeviceFlow", ctx)
	ret0, _ := ret[0].(*DeviceFlowResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartDeviceFlow indicates an expected call of StartDeviceFlow.
func (mr *MockDeviceFlowClientMockRecorder) StartDeviceFlow(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartDeviceFlow", reflect.TypeOf((*MockDeviceFlowClient)(nil).StartDeviceFlow), ctx)
}
