name: Check Markdown File Size
description: Validates that markdown files do not exceed size limits (supports single file or directory)
inputs:
  file-path:
    description: 'Path to markdown file or directory containing markdown files'
    required: false
    default: 'CLAUDE.md'
  max-size:
    description: 'Maximum file size in bytes'
    required: false
    default: '40000'
  exclude-pattern:
    description: 'Pattern to exclude files (e.g., "README.md")'
    required: false
    default: 'README.md'
  github-token:
    description: 'GitHub token for posting comments'
    required: true
outputs:
  size:
    description: 'Current file size in bytes (for single file mode)'
    value: ${{ steps.check.outputs.size }}
  exceeds-limit:
    description: 'Whether any file exceeds the size limit (true/false)'
    value: ${{ steps.check.outputs.exceeds_limit }}
  usage-percent:
    description: 'Percentage of limit used (for single file mode)'
    value: ${{ steps.check.outputs.usage_percent }}
  all-files-ok:
    description: 'Whether all files pass size check (true/false)'
    value: ${{ steps.check.outputs.all_files_ok }}

runs:
  using: composite
  steps:
    - name: Check file size
      id: check
      shell: bash
      run: |
        FILE_PATH="${{ inputs.file-path }}"
        MAX_SIZE="${{ inputs.max-size }}"
        EXCLUDE_PATTERN="${{ inputs.exclude-pattern }}"

        if [ ! -e "$FILE_PATH" ]; then
          echo "✅ $FILE_PATH does not exist - skipping check"
          echo "exists=false" >> $GITHUB_OUTPUT
          echo "all_files_ok=true" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Determine if path is a file or directory
        if [ -f "$FILE_PATH" ]; then
          # Single file mode
          FILES="$FILE_PATH"
          MODE="single"
        elif [ -d "$FILE_PATH" ]; then
          # Directory mode - find all .md files except excluded pattern
          FILES=$(find "$FILE_PATH" -name "*.md" -type f ! -name "$EXCLUDE_PATTERN")
          MODE="directory"

          if [ -z "$FILES" ]; then
            echo "✅ No markdown files found in $FILE_PATH - skipping check"
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "all_files_ok=true" >> $GITHUB_OUTPUT
            exit 0
          fi
        else
          echo "❌ $FILE_PATH is neither a file nor a directory"
          exit 1
        fi

        echo "exists=true" >> $GITHUB_OUTPUT
        echo "max_size=$MAX_SIZE" >> $GITHUB_OUTPUT
        echo "mode=$MODE" >> $GITHUB_OUTPUT

        # Check file sizes
        ALL_OK=true
        OVERSIZED_FILES=""
        TOTAL_FILES=0
        TOTAL_SIZE=0

        while IFS= read -r FILE; do
          [ -z "$FILE" ] && continue

          SIZE=$(wc -c < "$FILE" | tr -d ' ')
          USAGE_PERCENT=$((SIZE * 100 / MAX_SIZE))
          FILENAME=$(basename "$FILE")
          TOTAL_FILES=$((TOTAL_FILES + 1))
          TOTAL_SIZE=$((TOTAL_SIZE + SIZE))

          if [ "$SIZE" -gt "$MAX_SIZE" ]; then
            EXCESS=$((SIZE - MAX_SIZE))
            EXCESS_PERCENT=$((EXCESS * 100 / MAX_SIZE))
            echo "❌ $FILENAME: $SIZE bytes (over by $EXCESS bytes, ${EXCESS_PERCENT}%)"
            OVERSIZED_FILES="${OVERSIZED_FILES}${FILE}:${SIZE},"
            ALL_OK=false
          else
            echo "✅ $FILENAME: $SIZE bytes (${USAGE_PERCENT}% of limit)"
          fi
        done <<< "$FILES"

        # Set outputs
        if [ "$MODE" = "single" ]; then
          echo "size=$TOTAL_SIZE" >> $GITHUB_OUTPUT
          echo "usage_percent=$((TOTAL_SIZE * 100 / MAX_SIZE))" >> $GITHUB_OUTPUT
        fi

        echo "all_files_ok=$ALL_OK" >> $GITHUB_OUTPUT
        echo "total_files=$TOTAL_FILES" >> $GITHUB_OUTPUT
        echo "oversized_files=$OVERSIZED_FILES" >> $GITHUB_OUTPUT

        if [ "$ALL_OK" = "false" ]; then
          echo "exceeds_limit=true" >> $GITHUB_OUTPUT
        else
          echo "exceeds_limit=false" >> $GITHUB_OUTPUT
        fi

    - name: Post PR comment if file too large
      if: steps.check.outputs.exists == 'true' && steps.check.outputs.exceeds_limit == 'true'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        if [ -z "${{ github.event.pull_request.number }}" ]; then
          echo "ℹ️ Not a pull request - skipping comment"
          exit 0
        fi

        PR_NUMBER="${{ github.event.pull_request.number }}"
        SIZE="${{ steps.check.outputs.size }}"
        MAX_SIZE="${{ steps.check.outputs.max_size }}"
        EXCESS=$((SIZE - MAX_SIZE))
        EXCESS_PERCENT=$((EXCESS * 100 / MAX_SIZE))

        EXISTING_COMMENT=$(gh pr view $PR_NUMBER --json comments --jq '.comments[] | select(.body | contains("<!-- claude-md-size-check -->")) | .id' | head -1)

        MODE="${{ steps.check.outputs.mode }}"
        OVERSIZED="${{ steps.check.outputs.oversized_files }}"

        # Build list of oversized files
        FILE_LIST=""
        IFS=',' read -ra FILES_ARRAY <<< "$OVERSIZED"
        for FILE_ENTRY in "${FILES_ARRAY[@]}"; do
          [ -z "$FILE_ENTRY" ] && continue
          FILE_NAME=$(echo "$FILE_ENTRY" | cut -d: -f1 | xargs basename)
          FILE_SIZE=$(echo "$FILE_ENTRY" | cut -d: -f2)
          FILE_EXCESS=$((FILE_SIZE - MAX_SIZE))
          FILE_EXCESS_PERCENT=$((FILE_EXCESS * 100 / MAX_SIZE))
          FILE_LIST="${FILE_LIST}- \`${FILE_NAME}\`: **${FILE_SIZE} bytes** (over by ${FILE_EXCESS} bytes, ~${FILE_EXCESS_PERCENT}%)
        "
        done

        if [ "$MODE" = "single" ]; then
          TITLE="File Too Large"
          DESCRIPTION="The file is **${SIZE} bytes** but must not exceed **${MAX_SIZE} bytes**."
        else
          TITLE="Files Too Large"
          DESCRIPTION="The following files exceed the **${MAX_SIZE} byte** size limit:"
        fi

        COMMENT_BODY="<!-- claude-md-size-check -->
        > [!WARNING]
        > #### ${TITLE}
        >
        > ${DESCRIPTION}
        >
        ${FILE_LIST}
        >
        > **Action needed:** Please compress the oversized files. Consider:
        > - Removing verbose explanations
        > - Consolidating redundant examples
        > - Keeping only essential requirements
        > - Moving detailed guides to separate docs in \`docs/\` or \`docs/prd/\`
        >
        > All MANDATORY requirements must be preserved."

        if [ -n "$EXISTING_COMMENT" ]; then
          echo "Updating existing comment..."
          gh api -X PATCH "/repos/${{ github.repository }}/issues/comments/$EXISTING_COMMENT" \
            -f body="$COMMENT_BODY"
        else
          echo "Creating new comment..."
          gh pr comment $PR_NUMBER --body "$COMMENT_BODY"
        fi

    - name: Update comment with success if size is OK
      if: steps.check.outputs.exists == 'true' && steps.check.outputs.exceeds_limit == 'false'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        if [ -z "${{ github.event.pull_request.number }}" ]; then
          echo "ℹ️ Not a pull request - skipping comment"
          exit 0
        fi

        PR_NUMBER="${{ github.event.pull_request.number }}"
        SIZE="${{ steps.check.outputs.size }}"
        MAX_SIZE="${{ steps.check.outputs.max_size }}"
        USAGE_PERCENT="${{ steps.check.outputs.usage_percent }}"

        EXISTING_COMMENT=$(gh pr view $PR_NUMBER --json comments --jq '.comments[] | select(.body | contains("<!-- claude-md-size-check -->")) | .id' | head -1)

        if [ -z "$EXISTING_COMMENT" ]; then
          echo "ℹ️ No existing comment to update"
          exit 0
        fi

        EXISTING_COMMENT_BODY=$(gh pr view $PR_NUMBER --json comments --jq '.comments[] | select(.body | contains("<!-- claude-md-size-check -->")) | .body' | head -1)

        MODE="${{ steps.check.outputs.mode }}"
        TOTAL_FILES="${{ steps.check.outputs.total_files }}"

        if [ "$MODE" = "single" ]; then
          SUCCESS_COMMENT_BODY="<!-- claude-md-size-check -->
        > [!NOTE]
        > #### File Size OK ✅
        >
        > **Size:** ${SIZE} bytes
        > **Limit:** ${MAX_SIZE} bytes
        > **Usage:** ${USAGE_PERCENT}%
        >
        > Thank you for keeping the file optimized!"
        else
          SUCCESS_COMMENT_BODY="<!-- claude-md-size-check -->
        > [!NOTE]
        > #### All Files Size OK ✅
        >
        > **Files checked:** ${TOTAL_FILES}
        > **Limit:** ${MAX_SIZE} bytes per file
        >
        > Thank you for keeping all files optimized!"
        fi

        if echo "$EXISTING_COMMENT_BODY" | grep -q "CLAUDE.md Size OK ✅"; then
          echo "ℹ️ Comment already shows success - no update needed"
        else
          echo "Updating existing comment with success message..."
          gh api -X PATCH "/repos/${{ github.repository }}/issues/comments/$EXISTING_COMMENT" \
            -f body="$SUCCESS_COMMENT_BODY" || {
            echo "⚠️ Failed to update comment (it may have been deleted)"
          }
          echo "✅ Comment updated from warning to success"
        fi

    - name: Fail if file too large
      if: steps.check.outputs.exists == 'true' && steps.check.outputs.exceeds_limit == 'true'
      shell: bash
      run: |
        SIZE="${{ steps.check.outputs.size }}"
        MAX_SIZE="${{ steps.check.outputs.max_size }}"
        EXCESS=$((SIZE - MAX_SIZE))
        EXCESS_PERCENT=$((EXCESS * 100 / MAX_SIZE))

        MODE="${{ steps.check.outputs.mode }}"
        OVERSIZED="${{ steps.check.outputs.oversized_files }}"

        echo "❌ ERROR: One or more files exceed the size limit"
        echo ""
        echo "Maximum size: $MAX_SIZE bytes"
        echo ""
        echo "Oversized files:"

        IFS=',' read -ra FILES_ARRAY <<< "$OVERSIZED"
        for FILE_ENTRY in "${FILES_ARRAY[@]}"; do
          [ -z "$FILE_ENTRY" ] && continue
          FILE_NAME=$(echo "$FILE_ENTRY" | cut -d: -f1 | xargs basename)
          FILE_SIZE=$(echo "$FILE_ENTRY" | cut -d: -f2)
          FILE_EXCESS=$((FILE_SIZE - MAX_SIZE))
          echo "  - $FILE_NAME: $FILE_SIZE bytes (over by $FILE_EXCESS bytes)"
        done

        echo ""
        echo "Please compress the files by:"
        echo "  - Removing verbose explanations"
        echo "  - Consolidating redundant examples"
        echo "  - Keeping only essential requirements"
        echo "  - Moving detailed guides to docs/ or docs/prd/"
        echo ""
        echo "All MANDATORY requirements must be preserved."
        exit 1
