# yaml-language-server: $schema=https://atmos.tools/schemas/atmos/atmos-manifest/1.0/atmos-manifest.json

import:
  - mixins/floci
  - catalog/bucket

vars:
  stage: dev

components:
  terraform:
    bucket:
      metadata:
        type: real
