# yaml-language-server: $schema=https://atmos.tools/schemas/atmos/atmos-manifest/1.0/atmos-manifest.json

components:
  helmfile:
    demo:
      metadata:
        type: abstract
        component: nginx
      vars:
        image:
          tag: "latest"
        service:
          type: ClusterIP
          port: 80
        replicaCount: 1
        ingress:
          enabled: true
          hostname: fbi.com
          paths:
            - /
          extraHosts:
            - name: '*.app.github.dev'
              path: /
            - name: 'localhost'
              path: /
        readinessProbe:
          initialDelaySeconds: 1
          periodSeconds: 2
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        persistence:
          enabled: false
        extraVolumes:
          - name: custom-html
            configMap:
              name: custom-html
        extraVolumeMounts:
          - name: custom-html
            mountPath: /app/index.html
            subPath: index.html
            readOnly: true
