#include:
#  - path: "../examples/demo-localstack/docker-compose.yml"

services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace:cached
#    links:
#      - localstack
    command: sleep infinity
