package hooks

import (
	"github.com/spf13/cobra"

	githooks "github.com/cloudposse/atmos/pkg/git/hooks"
	"github.com/cloudposse/atmos/pkg/perf"
)

// uninstallCmd is the `atmos git hooks uninstall` subcommand.
var uninstallCmd = &cobra.Command{
	Use:   "uninstall [hook-name...]",
	Short: "Remove Atmos-managed Git hook shims",
	Long: `Remove .git/hooks shim scripts that were generated by Atmos.

Without hook names, removes shims for all configured hooks.
With hook names, removes only the named hooks.

Only files containing the Atmos marker line are removed. User-authored hooks
are left unchanged and a warning is emitted.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		defer perf.Track(atmosConfigPtr, "git.hooks.uninstall.RunE")()

		return githooks.Uninstall(cmd.Context(), gitConfig(), args)
	},
}
