// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cloudposse/atmos/pkg/vendoring/version (interfaces: RemoteLister)
//
// Generated by this command:
//
//	mockgen -destination=pkg/vendoring/update_remote_mock_test.go -package=vendoring github.com/cloudposse/atmos/pkg/vendoring/version RemoteLister
//

// Package vendoring is a generated GoMock package.
package vendoring

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRemoteLister is a mock of RemoteLister interface.
type MockRemoteLister struct {
	ctrl     *gomock.Controller
	recorder *MockRemoteListerMockRecorder
	isgomock struct{}
}

// MockRemoteListerMockRecorder is the mock recorder for MockRemoteLister.
type MockRemoteListerMockRecorder struct {
	mock *MockRemoteLister
}

// NewMockRemoteLister creates a new mock instance.
func NewMockRemoteLister(ctrl *gomock.Controller) *MockRemoteLister {
	mock := &MockRemoteLister{ctrl: ctrl}
	mock.recorder = &MockRemoteListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRemoteLister) EXPECT() *MockRemoteListerMockRecorder {
	return m.recorder
}

// ListTags mocks base method.
func (m *MockRemoteLister) ListTags(ctx context.Context, gitURI string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTags", ctx, gitURI)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTags indicates an expected call of ListTags.
func (mr *MockRemoteListerMockRecorder) ListTags(ctx, gitURI any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTags", reflect.TypeOf((*MockRemoteLister)(nil).ListTags), ctx, gitURI)
}
