// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/vendoring/archived.go
//
// Generated by this command:
//
//	mockgen -source=pkg/vendoring/archived.go -destination=pkg/vendoring/update_archived_mock_test.go -package=vendoring
//

// Package vendoring is a generated GoMock package.
package vendoring

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockArchivedChecker is a mock of ArchivedChecker interface.
type MockArchivedChecker struct {
	ctrl     *gomock.Controller
	recorder *MockArchivedCheckerMockRecorder
	isgomock struct{}
}

// MockArchivedCheckerMockRecorder is the mock recorder for MockArchivedChecker.
type MockArchivedCheckerMockRecorder struct {
	mock *MockArchivedChecker
}

// NewMockArchivedChecker creates a new mock instance.
func NewMockArchivedChecker(ctrl *gomock.Controller) *MockArchivedChecker {
	mock := &MockArchivedChecker{ctrl: ctrl}
	mock.recorder = &MockArchivedCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArchivedChecker) EXPECT() *MockArchivedCheckerMockRecorder {
	return m.recorder
}

// IsArchived mocks base method.
func (m *MockArchivedChecker) IsArchived(ctx context.Context, gitURI string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsArchived", ctx, gitURI)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsArchived indicates an expected call of IsArchived.
func (mr *MockArchivedCheckerMockRecorder) IsArchived(ctx, gitURI any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsArchived", reflect.TypeOf((*MockArchivedChecker)(nil).IsArchived), ctx, gitURI)
}
