// Code generated by MockGen. DO NOT EDIT.
// Source: utils.go
//
// Generated by this command:
//
//	mockgen -source=utils.go -destination=mock_utils.go -package=list
//

// Package list is a generated GoMock package.
package list

import (
	reflect "reflect"

	auth "github.com/cloudposse/atmos/pkg/auth"
	schema "github.com/cloudposse/atmos/pkg/schema"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthManagerFactory is a mock of AuthManagerFactory interface.
type MockAuthManagerFactory struct {
	ctrl     *gomock.Controller
	recorder *MockAuthManagerFactoryMockRecorder
	isgomock struct{}
}

// MockAuthManagerFactoryMockRecorder is the mock recorder for MockAuthManagerFactory.
type MockAuthManagerFactoryMockRecorder struct {
	mock *MockAuthManagerFactory
}

// NewMockAuthManagerFactory creates a new mock instance.
func NewMockAuthManagerFactory(ctrl *gomock.Controller) *MockAuthManagerFactory {
	mock := &MockAuthManagerFactory{ctrl: ctrl}
	mock.recorder = &MockAuthManagerFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthManagerFactory) EXPECT() *MockAuthManagerFactoryMockRecorder {
	return m.recorder
}

// CreateWithStackScan mocks base method.
func (m *MockAuthManagerFactory) CreateWithStackScan(identity string, authConfig *schema.AuthConfig, selectValue string, atmosConfig *schema.AtmosConfiguration) (auth.AuthManager, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithStackScan", identity, authConfig, selectValue, atmosConfig)
	ret0, _ := ret[0].(auth.AuthManager)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWithStackScan indicates an expected call of CreateWithStackScan.
func (mr *MockAuthManagerFactoryMockRecorder) CreateWithStackScan(identity, authConfig, selectValue, atmosConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithStackScan", reflect.TypeOf((*MockAuthManagerFactory)(nil).CreateWithStackScan), identity, authConfig, selectValue, atmosConfig)
}
