// Code generated by MockGen. DO NOT EDIT.
// Source: backend_helpers.go
//
// Generated by this command:
//
//	mockgen -source=backend_helpers.go -destination=mock_backend_helpers_test.go -package=backend
//

// Package backend is a generated GoMock package.
package backend

import (
	reflect "reflect"

	schema "github.com/cloudposse/atmos/pkg/schema"
	gomock "go.uber.org/mock/gomock"
)

// MockConfigInitializer is a mock of ConfigInitializer interface.
type MockConfigInitializer struct {
	ctrl     *gomock.Controller
	recorder *MockConfigInitializerMockRecorder
	isgomock struct{}
}

// MockConfigInitializerMockRecorder is the mock recorder for MockConfigInitializer.
type MockConfigInitializerMockRecorder struct {
	mock *MockConfigInitializer
}

// NewMockConfigInitializer creates a new mock instance.
func NewMockConfigInitializer(ctrl *gomock.Controller) *MockConfigInitializer {
	mock := &MockConfigInitializer{ctrl: ctrl}
	mock.recorder = &MockConfigInitializerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigInitializer) EXPECT() *MockConfigInitializerMockRecorder {
	return m.recorder
}

// InitConfigAndAuth mocks base method.
func (m *MockConfigInitializer) InitConfigAndAuth(component, stack, identity string) (*schema.AtmosConfiguration, *schema.AuthContext, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitConfigAndAuth", component, stack, identity)
	ret0, _ := ret[0].(*schema.AtmosConfiguration)
	ret1, _ := ret[1].(*schema.AuthContext)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// InitConfigAndAuth indicates an expected call of InitConfigAndAuth.
func (mr *MockConfigInitializerMockRecorder) InitConfigAndAuth(component, stack, identity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitConfigAndAuth", reflect.TypeOf((*MockConfigInitializer)(nil).InitConfigAndAuth), component, stack, identity)
}

// MockProvisioner is a mock of Provisioner interface.
type MockProvisioner struct {
	ctrl     *gomock.Controller
	recorder *MockProvisionerMockRecorder
	isgomock struct{}
}

// MockProvisionerMockRecorder is the mock recorder for MockProvisioner.
type MockProvisionerMockRecorder struct {
	mock *MockProvisioner
}

// NewMockProvisioner creates a new mock instance.
func NewMockProvisioner(ctrl *gomock.Controller) *MockProvisioner {
	mock := &MockProvisioner{ctrl: ctrl}
	mock.recorder = &MockProvisionerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvisioner) EXPECT() *MockProvisionerMockRecorder {
	return m.recorder
}

// CreateBackend mocks base method.
func (m *MockProvisioner) CreateBackend(atmosConfig *schema.AtmosConfiguration, component, stack string, describeFunc func(string, string) (map[string]any, error), authContext *schema.AuthContext) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBackend", atmosConfig, component, stack, describeFunc, authContext)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBackend indicates an expected call of CreateBackend.
func (mr *MockProvisionerMockRecorder) CreateBackend(atmosConfig, component, stack, describeFunc, authContext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBackend", reflect.TypeOf((*MockProvisioner)(nil).CreateBackend), atmosConfig, component, stack, describeFunc, authContext)
}

// DeleteBackend mocks base method.
func (m *MockProvisioner) DeleteBackend(atmosConfig *schema.AtmosConfiguration, component, stack string, force bool, describeFunc func(string, string) (map[string]any, error), authContext *schema.AuthContext) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBackend", atmosConfig, component, stack, force, describeFunc, authContext)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBackend indicates an expected call of DeleteBackend.
func (mr *MockProvisionerMockRecorder) DeleteBackend(atmosConfig, component, stack, force, describeFunc, authContext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBackend", reflect.TypeOf((*MockProvisioner)(nil).DeleteBackend), atmosConfig, component, stack, force, describeFunc, authContext)
}

// DescribeBackend mocks base method.
func (m *MockProvisioner) DescribeBackend(atmosConfig *schema.AtmosConfiguration, component string, opts any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeBackend", atmosConfig, component, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// DescribeBackend indicates an expected call of DescribeBackend.
func (mr *MockProvisionerMockRecorder) DescribeBackend(atmosConfig, component, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeBackend", reflect.TypeOf((*MockProvisioner)(nil).DescribeBackend), atmosConfig, component, opts)
}

// ListBackends mocks base method.
func (m *MockProvisioner) ListBackends(atmosConfig *schema.AtmosConfiguration, opts any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBackends", atmosConfig, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// ListBackends indicates an expected call of ListBackends.
func (mr *MockProvisionerMockRecorder) ListBackends(atmosConfig, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBackends", reflect.TypeOf((*MockProvisioner)(nil).ListBackends), atmosConfig, opts)
}
