package checksum

import (
	"errors"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestParseChecksumsFile(t *testing.T) {
	// Compile-time guard against accidental renames of the sentinel errors this test asserts on.
	_ = ErrEmptyChecksumFile

	tests := []struct {
		name    string
		input   string
		want    map[string]string
		wantErr error
	}{
		{
			name: "GNU sha256sum two-space format",
			input: "" +
				"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  kubectl_linux_amd64.tar.gz\n" +
				"4f2dcfc1f0a9bfedf3d8cabb7c1ec3d7e6f3a4c6c5d8b9e0f1a2b3c4d5e6f7a8  kubectl_darwin_arm64.tar.gz\n",
			want: map[string]string{
				"kubectl_linux_amd64.tar.gz":  "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
				"kubectl_darwin_arm64.tar.gz": "4f2dcfc1f0a9bfedf3d8cabb7c1ec3d7e6f3a4c6c5d8b9e0f1a2b3c4d5e6f7a8",
			},
		},
		{
			name:  "GNU sha256sum binary marker (asterisk) is stripped from filename",
			input: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 *kubectl_linux_amd64.tar.gz\n",
			want: map[string]string{
				"kubectl_linux_amd64.tar.gz": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
			},
		},
		{
			name: "BSD shasum format",
			input: "" +
				"SHA256 (kubectl_linux_amd64.tar.gz) = e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\n" +
				"SHA256 (kubectl_darwin_arm64.tar.gz) = 4f2dcfc1f0a9bfedf3d8cabb7c1ec3d7e6f3a4c6c5d8b9e0f1a2b3c4d5e6f7a8\n",
			want: map[string]string{
				"kubectl_linux_amd64.tar.gz":  "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
				"kubectl_darwin_arm64.tar.gz": "4f2dcfc1f0a9bfedf3d8cabb7c1ec3d7e6f3a4c6c5d8b9e0f1a2b3c4d5e6f7a8",
			},
		},
		{
			name:  "single bare hash line",
			input: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\n",
			want: map[string]string{
				"": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
			},
		},
		{
			name: "comment lines and blanks are skipped",
			input: "" +
				"# Generated by goreleaser v1.0.0\n" +
				"\n" +
				"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  kubectl_linux_amd64.tar.gz\n" +
				"#another comment\n",
			want: map[string]string{
				"kubectl_linux_amd64.tar.gz": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
			},
		},
		{
			name: "mixed GNU and BSD lines parse together",
			input: "" +
				"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  kubectl_linux_amd64.tar.gz\n" +
				"SHA256 (kubectl_darwin_arm64.tar.gz) = 4f2dcfc1f0a9bfedf3d8cabb7c1ec3d7e6f3a4c6c5d8b9e0f1a2b3c4d5e6f7a8\n",
			want: map[string]string{
				"kubectl_linux_amd64.tar.gz":  "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
				"kubectl_darwin_arm64.tar.gz": "4f2dcfc1f0a9bfedf3d8cabb7c1ec3d7e6f3a4c6c5d8b9e0f1a2b3c4d5e6f7a8",
			},
		},
		{
			name:  "uppercase hashes are normalized to lowercase",
			input: "E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855  kubectl.tar.gz\n",
			want: map[string]string{
				"kubectl.tar.gz": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
			},
		},
		{
			name:  "filenames with spaces survive intact",
			input: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  my tool v1.0.tar.gz\n",
			want: map[string]string{
				"my tool v1.0.tar.gz": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
			},
		},
		{
			name:  "CRLF line endings work",
			input: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  kubectl.tar.gz\r\n",
			want: map[string]string{
				"kubectl.tar.gz": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
			},
		},
		{
			name:    "empty input returns ErrEmptyChecksumFile",
			input:   "",
			wantErr: ErrEmptyChecksumFile,
		},
		{
			name:    "only comments returns ErrEmptyChecksumFile",
			input:   "# this is a comment\n#another\n",
			wantErr: ErrEmptyChecksumFile,
		},
		{
			name: "malformed lines are skipped, valid ones survive",
			input: "" +
				"this is not a checksum line\n" +
				"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  kubectl.tar.gz\n" +
				"deadbeef short hash\n",
			want: map[string]string{
				"kubectl.tar.gz": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
			},
		},
		{
			name:    "all-malformed input returns ErrEmptyChecksumFile",
			input:   "garbage\nmore garbage\n",
			wantErr: ErrEmptyChecksumFile,
		},
		{
			name:  "hash with wrong length is rejected",
			input: "deadbeef  kubectl.tar.gz\n",
			// 8 hex chars, not 64 → not a valid SHA-256 entry. No other lines parse → empty.
			wantErr: ErrEmptyChecksumFile,
		},
		{
			name:    "BSD line with wrong-length hash is rejected",
			input:   "SHA256 (kubectl.tar.gz) = deadbeef\n",
			wantErr: ErrEmptyChecksumFile,
		},
		{
			name: "GNU-shaped line with hash-only-asterisk (no filename after marker) is rejected",
			// hash + space + `*` only (no filename after the binary-mode marker). After trimming the
			// asterisk, `rest` is empty so the GNU branch rejects. Other branches don't match either.
			input:   "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 *\n",
			wantErr: ErrEmptyChecksumFile,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			got, err := ParseChecksumsFile([]byte(tc.input))
			if tc.wantErr != nil {
				require.Error(t, err)
				assert.ErrorIs(t, err, tc.wantErr)
				return
			}
			require.NoError(t, err)
			assert.Equal(t, tc.want, got)
		})
	}
}

func TestLookupAsset(t *testing.T) {
	tests := []struct {
		name     string
		entries  map[string]string
		filename string
		wantHash string
		wantOK   bool
	}{
		{
			name:     "exact match",
			entries:  map[string]string{"kubectl.tar.gz": "abc123"},
			filename: "kubectl.tar.gz",
			wantHash: "abc123",
			wantOK:   true,
		},
		{
			name:     "basename match — entry has path prefix",
			entries:  map[string]string{"dist/kubectl_linux_amd64.tar.gz": "abc123"},
			filename: "kubectl_linux_amd64.tar.gz",
			wantHash: "abc123",
			wantOK:   true,
		},
		{
			name:     "basename match — query has path prefix",
			entries:  map[string]string{"kubectl_linux_amd64.tar.gz": "abc123"},
			filename: "./kubectl_linux_amd64.tar.gz",
			wantHash: "abc123",
			wantOK:   true,
		},
		{
			name:     "single-entry bare-hash manifest matches any filename",
			entries:  map[string]string{"": "abc123"},
			filename: "kubectl_linux_amd64.tar.gz",
			wantHash: "abc123",
			wantOK:   true,
		},
		{
			name:     "bare-hash key with other entries — no fallback (would be ambiguous)",
			entries:  map[string]string{"": "abc123", "other.tar.gz": "def456"},
			filename: "kubectl.tar.gz",
			wantOK:   false,
		},
		{
			name:     "no match returns ok=false",
			entries:  map[string]string{"different.tar.gz": "abc123"},
			filename: "kubectl.tar.gz",
			wantOK:   false,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			hash, ok := lookupAsset(tc.entries, tc.filename)
			assert.Equal(t, tc.wantOK, ok)
			if tc.wantOK {
				assert.Equal(t, tc.wantHash, hash)
			}
		})
	}
}

func TestIsHex(t *testing.T) {
	tests := []struct {
		input string
		want  bool
	}{
		{"abcdef0123456789", true},
		{"ABCDEF0123456789", true},
		{"deadBEEF", true},
		{"", true}, // Empty string is technically hex-clean; callers gate by length separately.
		{"xyz", false},
		{"abc 123", false},
		{"abc-123", false},
	}
	for _, tc := range tests {
		t.Run(tc.input, func(t *testing.T) {
			assert.Equal(t, tc.want, isHex(tc.input))
		})
	}
}

// TestParseChecksumsFile_ErrorIsWiring asserts that wrapped errors remain detectable via errors.Is.
// Per CLAUDE.md error handling rules.
func TestParseChecksumsFile_ErrorIsWiring(t *testing.T) {
	_, err := ParseChecksumsFile([]byte(""))
	require.Error(t, err)
	assert.True(t, errors.Is(err, ErrEmptyChecksumFile), "must be detectable via errors.Is")
}

// TestParseChecksumsFile_LongLine exercises the scanner buffer expansion. Some checksum
// manifests include very long signature lines alongside hashes; we should still parse the hashes.
func TestParseChecksumsFile_LongLine(t *testing.T) {
	longLine := "# " + strings.Repeat("x", 200_000)
	input := longLine + "\n" +
		"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  kubectl.tar.gz\n"
	got, err := ParseChecksumsFile([]byte(input))
	require.NoError(t, err)
	assert.Equal(t, "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", got["kubectl.tar.gz"])
}
