package workdir

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
	"github.com/spf13/viper"

	errUtils "github.com/cloudposse/atmos/errors"
	cfg "github.com/cloudposse/atmos/pkg/config"
	"github.com/cloudposse/atmos/pkg/flags"
	"github.com/cloudposse/atmos/pkg/perf"
	"github.com/cloudposse/atmos/pkg/schema"
	"github.com/cloudposse/atmos/pkg/ui/theme"
)

var cleanParser *flags.StandardParser

var cleanCmd = &cobra.Command{
	Use:   "clean [component]",
	Short: "Clean workdir(s)",
	Long: `Remove component working directories.

Use --all to clean all workdirs, or specify a component and stack to clean a specific workdir.
Workdirs are ephemeral and can be regenerated by running 'atmos terraform init'.`,
	Example: `  # Clean a specific workdir
  atmos terraform workdir clean vpc --stack dev

  # Clean all workdirs
  atmos terraform workdir clean --all`,
	Args: cobra.MaximumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		defer perf.Track(atmosConfigPtr, "workdir.clean.RunE")()

		v := viper.GetViper()
		all := v.GetBool("all")
		stack := v.GetString("stack")

		// Validate arguments.
		if all && len(args) > 0 {
			return errUtils.Build(errUtils.ErrWorkdirClean).
				WithExplanation("Cannot specify both --all and a component").
				WithHint("Use --all alone to clean all workdirs, or specify a component and stack").
				Err()
		}

		if !all && len(args) == 0 {
			return errUtils.Build(errUtils.ErrWorkdirClean).
				WithExplanation("Either --all or a component is required").
				WithHint("Use --all to clean all workdirs, or specify a component with --stack").
				Err()
		}

		if !all && stack == "" {
			return errUtils.Build(errUtils.ErrWorkdirClean).
				WithExplanation("Stack is required when cleaning a specific workdir").
				WithHint("Use --stack to specify the stack").
				Err()
		}

		// Initialize config with global flags (--base-path, --config, etc.).
		configInfo := buildConfigAndStacksInfo(cmd, v)
		atmosConfig, err := cfg.InitCliConfig(configInfo, false)
		if err != nil {
			return errUtils.Build(errUtils.ErrWorkdirClean).
				WithCause(err).
				WithExplanation("Failed to load atmos configuration").
				Err()
		}

		// Clean workdirs.
		if all {
			return cleanAllWorkdirs(&atmosConfig)
		}

		component := args[0]
		return cleanSpecificWorkdir(&atmosConfig, component, stack)
	},
}

func cleanAllWorkdirs(atmosConfig *schema.AtmosConfiguration) error {
	if err := workdirManager.CleanAllWorkdirs(atmosConfig); err != nil {
		return err
	}

	fmt.Fprintf(os.Stderr, "%s All workdirs cleaned\n", theme.Styles.Checkmark.String())
	return nil
}

func cleanSpecificWorkdir(atmosConfig *schema.AtmosConfiguration, component, stack string) error {
	if err := workdirManager.CleanWorkdir(atmosConfig, component, stack); err != nil {
		return err
	}

	fmt.Fprintf(os.Stderr, "%s Workdir cleaned for %s in %s\n", theme.Styles.Checkmark.String(), component, stack)
	return nil
}

func init() {
	cleanCmd.DisableFlagParsing = false

	// Create parser with functional options.
	cleanParser = flags.NewStandardParser(
		flags.WithStackFlag(),
		flags.WithBoolFlag("all", "a", false, "Clean all workdirs"),
		flags.WithEnvVars("all", "ATMOS_WORKDIR_CLEAN_ALL"),
	)

	// Register flags with the command.
	cleanParser.RegisterFlags(cleanCmd)

	// Bind flags to Viper.
	if err := cleanParser.BindToViper(viper.GetViper()); err != nil {
		panic(err)
	}
}
