package cmd

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"time"

	"github.com/spf13/cobra"

	errUtils "github.com/cloudposse/atmos/errors"
	"github.com/cloudposse/atmos/pkg/auth"
	awsCloud "github.com/cloudposse/atmos/pkg/auth/cloud/aws"
	"github.com/cloudposse/atmos/pkg/auth/credentials"
	"github.com/cloudposse/atmos/pkg/auth/types"
	"github.com/cloudposse/atmos/pkg/auth/validation"
	cfg "github.com/cloudposse/atmos/pkg/config"
	"github.com/cloudposse/atmos/pkg/data"
	log "github.com/cloudposse/atmos/pkg/logger"
	"github.com/cloudposse/atmos/pkg/perf"
	"github.com/cloudposse/atmos/pkg/schema"
)

// execCredentialAPIVersion is the Kubernetes exec credential plugin API version.
const execCredentialAPIVersion = "client.authentication.k8s.io/v1beta1"

// authEKSTokenCmd generates a short-lived EKS bearer token for kubectl.
var authEKSTokenCmd = &cobra.Command{
	Use:   "eks-token",
	Short: "Generate an EKS bearer token for kubectl",
	Long: `Generate a short-lived EKS bearer token using STS pre-signed GetCallerIdentity URL.

This command is designed to be used as a kubectl exec credential plugin.
It authenticates using the specified identity and outputs an ExecCredential
JSON object to stdout.

The kubeconfig generated by 'atmos auth login' automatically configures
kubectl to call this command for token generation.

Examples:
  # Generate token for a cluster (typically called by kubectl)
  atmos auth eks-token --cluster-name my-cluster --region us-east-2

  # Generate token using a specific identity
  atmos auth eks-token --cluster-name my-cluster --region us-east-2 --identity dev-admin`,

	FParseErrWhitelist: struct{ UnknownFlags bool }{UnknownFlags: false},
	Args:               cobra.NoArgs,
	RunE:               executeAuthEKSTokenCommand,
	// Suppress usage on errors since kubectl invokes this automatically.
	SilenceUsage: true,
}

// execCredential represents the Kubernetes ExecCredential response.
type execCredential struct {
	APIVersion string               `json:"apiVersion"`
	Kind       string               `json:"kind"`
	Status     execCredentialStatus `json:"status"`
}

// execCredentialStatus contains the token and expiration.
type execCredentialStatus struct {
	ExpirationTimestamp string `json:"expirationTimestamp"`
	Token               string `json:"token"`
}

func executeAuthEKSTokenCommand(cmd *cobra.Command, args []string) error {
	handleHelpRequest(cmd, args)

	// Load atmos config.
	atmosConfig, err := cfg.InitCliConfig(schema.ConfigAndStacksInfo{}, false)
	if err != nil {
		return fmt.Errorf(errUtils.ErrWrapFormat, errUtils.ErrFailedToInitConfig, err)
	}
	defer perf.Track(&atmosConfig, "cmd.executeAuthEKSTokenCommand")()

	ctx := context.Background()

	// Get flag values.
	clusterName, _ := cmd.Flags().GetString("cluster-name")
	region, _ := cmd.Flags().GetString("region")

	if clusterName == "" {
		return fmt.Errorf("%w: --cluster-name is required", errUtils.ErrEKSTokenGeneration)
	}

	if region == "" {
		return fmt.Errorf("%w: --region is required", errUtils.ErrEKSTokenGeneration)
	}

	// Resolve identity: flag > env var > default.
	identityName := GetIdentityFromFlags(cmd, os.Args)

	log.Debug("Generating EKS token", "cluster", clusterName, "region", region, "identity", identityName)

	// Authenticate to get credentials.
	creds, err := authenticateForEKSToken(ctx, &atmosConfig.Auth, atmosConfig.CliConfigPath, identityName)
	if err != nil {
		return fmt.Errorf("%w: %w", errUtils.ErrEKSTokenGeneration, err)
	}

	// Generate token.
	token, expiresAt, err := awsCloud.GetToken(ctx, creds, clusterName, region)
	if err != nil {
		return err
	}

	// Output ExecCredential JSON to stdout.
	credential := execCredential{
		APIVersion: execCredentialAPIVersion,
		Kind:       "ExecCredential",
		Status: execCredentialStatus{
			ExpirationTimestamp: expiresAt.UTC().Format(time.RFC3339),
			Token:               token,
		},
	}

	output, err := json.Marshal(credential)
	if err != nil {
		return fmt.Errorf("%w: failed to marshal ExecCredential: %w", errUtils.ErrEKSTokenGeneration, err)
	}

	return data.Write(string(output))
}

// authenticateForEKSToken authenticates an identity and returns credentials.
func authenticateForEKSToken(ctx context.Context, authConfig *schema.AuthConfig, cliConfigPath, identityName string) (types.ICredentials, error) {
	defer perf.Track(nil, "cmd.authenticateForEKSToken")()

	authStackInfo := &schema.ConfigAndStacksInfo{
		AuthContext: &schema.AuthContext{},
	}

	credStore := credentials.NewCredentialStore()
	validator := validation.NewValidator()

	mgr, err := auth.NewAuthManager(authConfig, credStore, validator, authStackInfo, cliConfigPath)
	if err != nil {
		return nil, fmt.Errorf(errUtils.ErrWrapFormat, errUtils.ErrFailedToInitializeAuthManager, err)
	}

	// If no identity specified, try to resolve default.
	if identityName == "" {
		identityName = resolveDefaultIdentity(authConfig)
		if identityName == "" {
			return nil, fmt.Errorf("%w: no identity specified and no default identity found", errUtils.ErrEKSTokenGeneration)
		}
	}

	whoami, err := mgr.Authenticate(ctx, identityName)
	if err != nil {
		return nil, fmt.Errorf(errUtils.ErrWrapWithNameAndCauseFormat, errUtils.ErrIdentityAuthFailed, identityName, err)
	}

	if whoami.Credentials == nil {
		return nil, fmt.Errorf(errUtils.ErrWrapWithNameAndCauseFormat, errUtils.ErrIdentityAuthFailed, identityName, errUtils.ErrIdentityCredentialsNone)
	}

	return whoami.Credentials, nil
}

// resolveDefaultIdentity finds a default identity from the auth config.
func resolveDefaultIdentity(authConfig *schema.AuthConfig) string {
	if authConfig == nil || len(authConfig.Identities) == 0 {
		return ""
	}

	// If there's only one identity, use it.
	if len(authConfig.Identities) == 1 {
		for name := range authConfig.Identities {
			return name
		}
	}

	return ""
}

func init() {
	authEKSTokenCmd.Flags().String("cluster-name", "", "EKS cluster name (required)")
	authEKSTokenCmd.Flags().String("region", "", "AWS region (required)")
	authCmd.AddCommand(authEKSTokenCmd)
}
