// Code generated by MockGen. DO NOT EDIT.
// Source: standalone.go
//
// Generated by this command:
//
//	mockgen -source=standalone.go -destination=mock_standalone.go -package=types
//

// Package types is a generated GoMock package.
package types

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStandaloneIdentity is a mock of StandaloneIdentity interface.
type MockStandaloneIdentity struct {
	ctrl     *gomock.Controller
	recorder *MockStandaloneIdentityMockRecorder
	isgomock struct{}
}

// MockStandaloneIdentityMockRecorder is the mock recorder for MockStandaloneIdentity.
type MockStandaloneIdentityMockRecorder struct {
	mock *MockStandaloneIdentity
}

// NewMockStandaloneIdentity creates a new mock instance.
func NewMockStandaloneIdentity(ctrl *gomock.Controller) *MockStandaloneIdentity {
	mock := &MockStandaloneIdentity{ctrl: ctrl}
	mock.recorder = &MockStandaloneIdentityMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStandaloneIdentity) EXPECT() *MockStandaloneIdentityMockRecorder {
	return m.recorder
}

// AuthenticateStandalone mocks base method.
func (m *MockStandaloneIdentity) AuthenticateStandalone(ctx context.Context) (ICredentials, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthenticateStandalone", ctx)
	ret0, _ := ret[0].(ICredentials)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthenticateStandalone indicates an expected call of AuthenticateStandalone.
func (mr *MockStandaloneIdentityMockRecorder) AuthenticateStandalone(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthenticateStandalone", reflect.TypeOf((*MockStandaloneIdentity)(nil).AuthenticateStandalone), ctx)
}

// IsStandalone mocks base method.
func (m *MockStandaloneIdentity) IsStandalone() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsStandalone")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsStandalone indicates an expected call of IsStandalone.
func (mr *MockStandaloneIdentityMockRecorder) IsStandalone() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsStandalone", reflect.TypeOf((*MockStandaloneIdentity)(nil).IsStandalone))
}
