bases:
- ../helm-defaults.yaml
- ../environments.yaml
---

repositories:
# Kubernetes incubator repo of helm charts
- name: "kubernetes-incubator"
  url: "https://kubernetes-charts-incubator.storage.googleapis.com"

releases:

- name: 'istio'
  chart: "kubernetes-incubator/raw"
  namespace: "istio-system"
  version: {{ .Values.chart_version | quote }}
  wait: true
  timeout: 60
  atomic: true
  cleanupOnFail: true
  installed: {{ .Values.installed }}
  createNamespace: true
  values:
    - istio-operator.yaml.gotmpl
