bases:
- ../helm-defaults.yaml
- ../environments.yaml
---

repositories:
- name: "kubernetes-incubator"
  url: "https://kubernetes-charts-incubator.storage.googleapis.com"

releases:

- name: 'istio'
  chart: "kubernetes-incubator/raw"

# ...
