// Code generated by MockGen. DO NOT EDIT.
// Source: provider.go
//
// Generated by this command:
//
//	mockgen -source=provider.go -destination=mock_provider.go -package=source
//

// Package source is a generated GoMock package.
package source

import (
	reflect "reflect"

	schema "github.com/cloudposse/atmos/pkg/schema"
	gomock "go.uber.org/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// GetAvailableVersions mocks base method.
func (m *MockProvider) GetAvailableVersions(source string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableVersions", source)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableVersions indicates an expected call of GetAvailableVersions.
func (mr *MockProviderMockRecorder) GetAvailableVersions(source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableVersions", reflect.TypeOf((*MockProvider)(nil).GetAvailableVersions), source)
}

// GetDiff mocks base method.
func (m *MockProvider) GetDiff(atmosConfig *schema.AtmosConfiguration, source, fromVersion, toVersion, filePath string, contextLines int, noColor bool) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiff", atmosConfig, source, fromVersion, toVersion, filePath, contextLines, noColor)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDiff indicates an expected call of GetDiff.
func (mr *MockProviderMockRecorder) GetDiff(atmosConfig, source, fromVersion, toVersion, filePath, contextLines, noColor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiff", reflect.TypeOf((*MockProvider)(nil).GetDiff), atmosConfig, source, fromVersion, toVersion, filePath, contextLines, noColor)
}

// SupportsOperation mocks base method.
func (m *MockProvider) SupportsOperation(operation Operation) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SupportsOperation", operation)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SupportsOperation indicates an expected call of SupportsOperation.
func (mr *MockProviderMockRecorder) SupportsOperation(operation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SupportsOperation", reflect.TypeOf((*MockProvider)(nil).SupportsOperation), operation)
}

// VerifyVersion mocks base method.
func (m *MockProvider) VerifyVersion(source, version string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyVersion", source, version)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyVersion indicates an expected call of VerifyVersion.
func (mr *MockProviderMockRecorder) VerifyVersion(source, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyVersion", reflect.TypeOf((*MockProvider)(nil).VerifyVersion), source, version)
}
