package eks

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"time"

	"github.com/spf13/cobra"

	errUtils "github.com/cloudposse/atmos/errors"
	"github.com/cloudposse/atmos/pkg/auth"
	awsCloud "github.com/cloudposse/atmos/pkg/auth/cloud/aws"
	"github.com/cloudposse/atmos/pkg/auth/credentials"
	"github.com/cloudposse/atmos/pkg/auth/types"
	"github.com/cloudposse/atmos/pkg/auth/validation"
	cfg "github.com/cloudposse/atmos/pkg/config"
	"github.com/cloudposse/atmos/pkg/data"
	log "github.com/cloudposse/atmos/pkg/logger"
	"github.com/cloudposse/atmos/pkg/perf"
	"github.com/cloudposse/atmos/pkg/schema"
)

// execCredentialAPIVersion is the Kubernetes exec credential plugin API version.
const execCredentialAPIVersion = "client.authentication.k8s.io/v1beta1"

// tokenCmd generates a short-lived EKS bearer token for kubectl.
var tokenCmd = &cobra.Command{
	Use:   "token",
	Short: "Generate an EKS bearer token for kubectl",
	Long: `Generate a short-lived EKS bearer token using STS pre-signed GetCallerIdentity URL.

This command is designed to be used as a kubectl exec credential plugin.
It authenticates using the specified identity and outputs an ExecCredential
JSON object to stdout.

The kubeconfig generated by 'atmos auth login' automatically configures
kubectl to call this command for token generation.

Examples:
  # Generate token for a cluster (typically called by kubectl)
  atmos aws eks token --cluster-name my-cluster --region us-east-2

  # Generate token using a specific identity
  atmos aws eks token --cluster-name my-cluster --region us-east-2 --identity dev-admin`,

	FParseErrWhitelist: struct{ UnknownFlags bool }{UnknownFlags: false},
	Args:               cobra.NoArgs,
	RunE:               executeTokenCommand,
	// Suppress usage on errors since kubectl invokes this automatically.
	SilenceUsage: true,
}

// execCredential represents the Kubernetes ExecCredential response.
type execCredential struct {
	APIVersion string               `json:"apiVersion"`
	Kind       string               `json:"kind"`
	Status     execCredentialStatus `json:"status"`
}

// execCredentialStatus contains the token and expiration.
type execCredentialStatus struct {
	ExpirationTimestamp string `json:"expirationTimestamp"`
	Token               string `json:"token"`
}

func executeTokenCommand(cmd *cobra.Command, args []string) error {
	// Load atmos config.
	atmosConfig, err := cfg.InitCliConfig(schema.ConfigAndStacksInfo{}, false)
	if err != nil {
		return fmt.Errorf(errUtils.ErrWrapFormat, errUtils.ErrFailedToInitConfig, err)
	}
	defer perf.Track(&atmosConfig, "eks.executeTokenCommand")()

	ctx := context.Background()

	// Get flag values.
	clusterName, _ := cmd.Flags().GetString("cluster-name")
	region, _ := cmd.Flags().GetString("region")

	if clusterName == "" {
		return fmt.Errorf("%w: --cluster-name is required", errUtils.ErrEKSTokenGeneration)
	}

	if region == "" {
		return fmt.Errorf("%w: --region is required", errUtils.ErrEKSTokenGeneration)
	}

	// Resolve identity: flag > env var > default.
	identityName := resolveIdentity(cmd)

	log.Debug("Generating EKS token", "cluster", clusterName, "region", region, "identity", identityName)

	// Authenticate to get credentials.
	// Skip integrations to avoid rewriting the kubeconfig during token generation.
	ctx = auth.ContextWithSkipIntegrations(ctx)
	creds, err := authenticateForToken(ctx, &atmosConfig.Auth, atmosConfig.CliConfigPath, identityName)
	if err != nil {
		return fmt.Errorf("%w: %w", errUtils.ErrEKSTokenGeneration, err)
	}

	// Export AWS credentials to process environment so the AWS SDK can use them
	// for the STS presign call. This ensures credentials are available regardless
	// of how the exec plugin is invoked (e.g., by kubectl).
	if err := exportAWSCredsToEnv(creds); err != nil {
		log.Warn("eks token: failed to export AWS credentials to environment", "error", err)
	}

	// Generate token.
	token, expiresAt, err := awsCloud.GetToken(ctx, creds, clusterName, region)
	if err != nil {
		return fmt.Errorf("%w: %w", errUtils.ErrEKSTokenGeneration, err)
	}

	// Output ExecCredential JSON to stdout.
	credential := execCredential{
		APIVersion: execCredentialAPIVersion,
		Kind:       "ExecCredential",
		Status: execCredentialStatus{
			ExpirationTimestamp: expiresAt.UTC().Format(time.RFC3339),
			Token:               token,
		},
	}

	output, err := json.Marshal(credential)
	if err != nil {
		return fmt.Errorf("%w: failed to marshal ExecCredential: %w", errUtils.ErrEKSTokenGeneration, err)
	}

	return data.Write(string(output))
}

// resolveIdentity resolves the identity name from flag, env var, or returns empty.
func resolveIdentity(cmd *cobra.Command) string {
	// Check flag first.
	identity, _ := cmd.Flags().GetString("identity")
	if identity != "" {
		return identity
	}

	// Fall back to environment variable.
	if envIdentity := os.Getenv("ATMOS_IDENTITY"); envIdentity != "" {
		return envIdentity
	}

	return ""
}

// authenticateForToken authenticates an identity and returns credentials.
func authenticateForToken(ctx context.Context, authConfig *schema.AuthConfig, cliConfigPath, identityName string) (types.ICredentials, error) {
	defer perf.Track(nil, "eks.authenticateForToken")()

	authStackInfo := &schema.ConfigAndStacksInfo{
		AuthContext: &schema.AuthContext{},
	}

	credStore := credentials.NewCredentialStore()
	validator := validation.NewValidator()

	mgr, err := auth.NewAuthManager(authConfig, credStore, validator, authStackInfo, cliConfigPath)
	if err != nil {
		return nil, fmt.Errorf(errUtils.ErrWrapFormat, errUtils.ErrFailedToInitializeAuthManager, err)
	}

	// If no identity specified, try to resolve default.
	if identityName == "" {
		identityName = resolveDefaultIdentity(authConfig)
		if identityName == "" {
			return nil, fmt.Errorf("%w: no identity specified and no default identity found", errUtils.ErrEKSTokenGeneration)
		}
	}

	whoami, err := mgr.Authenticate(ctx, identityName)
	if err != nil {
		return nil, fmt.Errorf(errUtils.ErrWrapWithNameAndCauseFormat, errUtils.ErrIdentityAuthFailed, identityName, err)
	}

	if whoami.Credentials == nil {
		return nil, fmt.Errorf(errUtils.ErrWrapWithNameAndCauseFormat, errUtils.ErrIdentityAuthFailed, identityName, errUtils.ErrIdentityCredentialsNone)
	}

	return whoami.Credentials, nil
}

// resolveDefaultIdentity finds a default identity from the auth config.
func resolveDefaultIdentity(authConfig *schema.AuthConfig) string {
	if authConfig == nil || len(authConfig.Identities) == 0 {
		return ""
	}

	// If there's only one identity, use it.
	if len(authConfig.Identities) == 1 {
		for name := range authConfig.Identities {
			return name
		}
	}

	return ""
}

// exportAWSCredsToEnv sets AWS credential environment variables in the current process.
// This ensures the AWS SDK can authenticate for the STS presign call used in token generation.
func exportAWSCredsToEnv(creds types.ICredentials) error {
	defer perf.Track(nil, "eks.exportAWSCredsToEnv")()

	awsCreds, ok := creds.(*types.AWSCredentials)
	if !ok {
		return fmt.Errorf("%w: expected AWS credentials for environment export", errUtils.ErrEKSTokenGeneration)
	}

	if awsCreds.AccessKeyID != "" {
		os.Setenv("AWS_ACCESS_KEY_ID", awsCreds.AccessKeyID)
	}
	if awsCreds.SecretAccessKey != "" {
		os.Setenv("AWS_SECRET_ACCESS_KEY", awsCreds.SecretAccessKey)
	}
	if awsCreds.SessionToken != "" {
		os.Setenv("AWS_SESSION_TOKEN", awsCreds.SessionToken)
	}
	if awsCreds.Region != "" {
		os.Setenv("AWS_REGION", awsCreds.Region)
		os.Setenv("AWS_DEFAULT_REGION", awsCreds.Region)
	}

	// Clear AWS_PROFILE to prevent the SDK from using a named profile
	// that might conflict with the explicit credentials.
	os.Unsetenv("AWS_PROFILE")

	log.Debug("Exported AWS credentials to environment",
		"hasAccessKey", awsCreds.AccessKeyID != "",
		"hasSecretKey", awsCreds.SecretAccessKey != "",
		"hasSessionToken", awsCreds.SessionToken != "",
		"region", awsCreds.Region,
	)

	return nil
}

func init() {
	tokenCmd.Flags().String("cluster-name", "", "EKS cluster name (required)")
	tokenCmd.Flags().String("region", "", "AWS region (required)")
	tokenCmd.Flags().StringP("identity", "i", "", "Atmos identity to authenticate with")
	EksCmd.AddCommand(tokenCmd)
}
