# yaml-language-server: $schema=https://atmos.tools/schemas/atmos/atmos-manifest/1.0/atmos-manifest.json

import:
  - _defaults

vars:
  stage: prod

components:
  terraform:
    network:
      vars:
        address_space:
          - 10.30.0.0/16
        subnet_prefixes:
          - 10.30.1.0/24
