bases:
  - ../helm-defaults.yaml
  - ../environments.yaml
---

repositories:
# Official ingress-nginx chart rep
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx

  # Cloud Posse incubator repo of helm charts
- name: "cloudposse-incubator"
  url: "https://charts.cloudposse.com/incubator/"

releases:
# https://github.com/kubernetes/ingress-nginx/tree/master/charts/ingress-nginx
# https://github.com/kubernetes/ingress-nginx/blob/master/charts/ingress-nginx/values.yaml
- name: "ingress"
  # The ingress-nginx expects the ingress-backend to already exist, so install the backend first
  needs: ["kube-system/ingress-backend"]
  namespace: "kube-system"
  labels:
    chart: "ingress-nginx"
    repo: "stable"
    component: "ingress"
    namespace: "kube-system"
    vendor: "kubernetes"
  chart: "ingress-nginx/ingress-nginx"
  version: {{ .Values.chart_version | quote }}
  wait: true
  timeout: 300
  atomic: true
  cleanupOnFail: true
  installed: {{ .Values.installed }}
  values:
  - controller:
      image:
        {{- with index .Values "image_repository" }}
        repository: {{ quote . }}
        {{- end }}
        {{- with index .Values "image_tag" }}
        tag: {{ quote . }}
        {{- end }}
        pullPolicy: "IfNotPresent"
      replicaCount: {{ .Values.replica_count }}
      resources:
        limits:
          cpu: {{ .Values.limit_cpu | quote }}
          memory: {{ .Values.limit_memory | quote }}
        requests:
          cpu: {{ .Values.request_cpu | quote }}
          memory: {{ .Values.request_memory | quote }}
      kind: {{ .Values.kind | quote }}
      defaultBackendService: "kube-system/ingress-backend-default"
      ingressClass: {{ .Values.ingress_class | quote }}
      config:
        custom-http-errors: '{{ join "," .Values.default_client_errors }},{{ join "," .Values.default_server_errors }}'
        use-proxy-protocol: {{ .Values.use_proxy_protocol | quote }}
        use-http2: '{{ .Values.use_http2 }}'
      # publishService.enabled = true is required for the ingress to be
      # used to serve the DNS zone apex.
      # See https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/aws.md#alias
      publishService:
        enabled: true
      service:
        externalTrafficPolicy: {{ .Values.external_traffic_policy | quote }}
        annotations:
          # DNS TTL cannot be set on Alias records, get set to 60s for ELB by AWS
          external-dns.alpha.kubernetes.io/hostname: {{ printf .Values.ingress_hostname_template .Values.stage .Values.environment | quote }}
          {{- with index .Values "connection_idle_timeout" }}
          service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '{{- . -}}'
          {{- end }}
          ### Network Load Balancer to be able to get Client IP
          {{- if eq .Values.nlb_enabled true }}
          service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
          {{- end }}
          {{- if eq .Values.use_proxy_protocol true }}
          service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
          {{- end }}
      updateStrategy:
        rollingUpdate:
          maxUnavailable: 1
        type: RollingUpdate

      metrics:
        enabled: {{ .Values.metrics_enabled }}

        serviceMonitor:
          enabled: {{ .Values.metrics_enabled }}
          namespace: "kube-system"

        {{- if eq .Values.prometheus_rule_enabled true }}
        prometheusRule:
          enabled: {{ .Values.prometheus_rule_enabled }}
          rules:
          - alert: NginxIngressControllerError
            annotations:
              description: "Nginx ingress controller error"
              summary: NginxIngressControllerError
            expr: nginx_ingress_controller_requests > {{ .Values.metrics_controller_error_alert }}
            labels:
              severity: warning
        {{- end }}

    ### Extra TCP and UDP ports to forward. Format is
    ### <internet-port-number>: <namespace>/<service>:<service-port-number>
    ###
    ### Example
    ### "8080": "portal/tomcat:8080"
    ### "3025": "teleport/teleport:3025"
    ###
    ### See https://kubernetes.github.io/ingress-nginx/user-guide/exposing-tcp-udp-services/
    {{- with index .Values "ingress_tcp" }}
    tcp: {{ toYaml . | nindent  10}}
    {{- end }}
    # UDP is not practically available. See
    # https://github.com/kubernetes/enhancements/issues/1435
    # https://github.com/kubernetes/kubernetes/pull/87549
    # https://github.com/kubernetes-sigs/external-dns/issues/1210
    #  {{- with index .Values "ingress_udp" }}
    #  udp: {{ toYaml . | nindent  10}}
    #  {{- end }}

    defaultBackend:
      enabled: {{ not .Values.default_backend_installed }}
    rbac:
      create: true
    serviceAccount:
      create: true
      name: {{ .Values.service_account_name | quote }}

# The ingress-nginx expects the ingress-backend to already exist, so install the backend first
- name: "ingress-backend"
  namespace: "kube-system"
  labels:
    chart: "nginx-default-backend"
    component: "ingress"
    namespace: "kube-system"
    vendor: "cloudposse"
  chart: "cloudposse-incubator/nginx-default-backend"
  version: {{ .Values.default_backend_chart_version | quote }}
  wait: true
  timeout: 300
  atomic: true
  cleanupOnFail: true
  installed: {{ .Values.default_backend_installed }}
  values:
  - nameOverride: default
    replicaCount: {{ .Values.default_backend_replica_count }}
    resources:
      limits:
        cpu: {{ .Values.default_backend_limit_cpu | quote }}
        memory: {{ .Values.default_backend_limit_memory | quote }}
      requests:
        cpu: {{ .Values.default_backend_request_cpu | quote }}
        memory: {{ .Values.default_backend_request_memory | quote }}
    errors:
      configmap: "default"
      default:
        email: {{ printf .Values.support_email_template .Values.stage | quote }}
        site: /
      client:
      {{- range $status := .Values.default_client_errors  }}
      - "{{ $status }}"
      {{- end }}
      server:
      {{- range $status := .Values.default_server_errors  }}
      - "{{ $status }}"
      {{- end }}

