Source demo/defaults.tape
Source demo/recordings/styles/defaults.tape
Source demo/recordings/styles/quick-start-advanced.tape

Type "# In Atmos you can easily explore workflows and execute workflow commands..." Sleep 500ms Enter
Type "atmos workflow" Sleep 500ms Enter
Sleep 2s
Down Sleep 500ms
Right Sleep 500ms
Down Sleep 500ms
Right Sleep 500ms
Down Sleep 500ms
Down Sleep 500ms
Up Sleep 500ms
Up Sleep 500ms
Enter
Sleep 3s
