# Apparently first place to set Framerate, PlaybackSpeed wins
Set Framerate 24
Set PlaybackSpeed 3

Source demo/defaults.tape
Source demo/recordings/styles/defaults.tape
Source demo/recordings/styles/quick-start-advanced.tape


Type "# We will start by installing some 3rd-party components and other artifacts..." Sleep 500ms Enter
Type "atmos vendor pull" Sleep 500ms Enter
Sleep 9s

Hide
Ctrl+C
Show
