Source demo/defaults.tape
Source demo/recordings/styles/defaults.tape
Source demo/recordings/styles/quick-start-advanced.tape

Type "# In Atmos you can easily explore components, stacks, and run commands..." Sleep 500ms Enter
Type "atmos" Sleep 500ms Enter
Sleep 2s
Down Sleep 500ms
Down Sleep 500ms
Up Sleep 500ms
Up Sleep 500ms
Up Sleep 500ms
Up Sleep 500ms
Up Sleep 1s
Right Sleep 1s
Down Sleep 500ms
Right Sleep 1s
Down Sleep 500ms
Up Sleep 1s
Enter
Sleep 1s
