Source demo/defaults.tape
Source demo/recordings/styles/defaults.tape
Source demo/recordings/styles/quick-start-advanced.tape

Hide
Type "atmos vendor pull --component vpc" Sleep 500ms Enter
Sleep 6s
Type "clear" Enter Sleep 500ms
Show

Type "# Then we can learn about the VPC component" Sleep 500ms Enter
Type "atmos docs vpc" Sleep 500ms Enter
Sleep 1s
Down 25 Sleep 500ms
Down 50 Sleep 500ms
Down 75 Sleep 500ms
Sleep 2s
Type "q" Sleep 500ms Enter
