// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cloudposse/atmos/pkg/ci (interfaces: Reporter)
//
// Generated by this command:
//
//	mockgen -typed -destination=mock_reporter_test.go -package=ci github.com/cloudposse/atmos/pkg/ci Reporter
//

// Package ci is a generated GoMock package.
package ci

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockReporter is a mock of Reporter interface.
type MockReporter struct {
	ctrl     *gomock.Controller
	recorder *MockReporterMockRecorder
	isgomock struct{}
}

// MockReporterMockRecorder is the mock recorder for MockReporter.
type MockReporterMockRecorder struct {
	mock *MockReporter
}

// NewMockReporter creates a new mock instance.
func NewMockReporter(ctrl *gomock.Controller) *MockReporter {
	mock := &MockReporter{ctrl: ctrl}
	mock.recorder = &MockReporterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReporter) EXPECT() *MockReporterMockRecorder {
	return m.recorder
}

// Annotate mocks base method.
func (m *MockReporter) Annotate(annotation Annotation) (Receipt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Annotate", annotation)
	ret0, _ := ret[0].(Receipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Annotate indicates an expected call of Annotate.
func (mr *MockReporterMockRecorder) Annotate(annotation any) *MockReporterAnnotateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Annotate", reflect.TypeOf((*MockReporter)(nil).Annotate), annotation)
	return &MockReporterAnnotateCall{Call: call}
}

// MockReporterAnnotateCall wrap *gomock.Call
type MockReporterAnnotateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReporterAnnotateCall) Return(arg0 Receipt, arg1 error) *MockReporterAnnotateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReporterAnnotateCall) Do(f func(Annotation) (Receipt, error)) *MockReporterAnnotateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReporterAnnotateCall) DoAndReturn(f func(Annotation) (Receipt, error)) *MockReporterAnnotateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Base mocks base method.
func (m *MockReporter) Base() (*BaseResolution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Base")
	ret0, _ := ret[0].(*BaseResolution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Base indicates an expected call of Base.
func (mr *MockReporterMockRecorder) Base() *MockReporterBaseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Base", reflect.TypeOf((*MockReporter)(nil).Base))
	return &MockReporterBaseCall{Call: call}
}

// MockReporterBaseCall wrap *gomock.Call
type MockReporterBaseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReporterBaseCall) Return(arg0 *BaseResolution, arg1 error) *MockReporterBaseCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReporterBaseCall) Do(f func() (*BaseResolution, error)) *MockReporterBaseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReporterBaseCall) DoAndReturn(f func() (*BaseResolution, error)) *MockReporterBaseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Check mocks base method.
func (m *MockReporter) Check(ctx context.Context, req CheckRequest) (Receipt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx, req)
	ret0, _ := ret[0].(Receipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Check indicates an expected call of Check.
func (mr *MockReporterMockRecorder) Check(ctx, req any) *MockReporterCheckCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockReporter)(nil).Check), ctx, req)
	return &MockReporterCheckCall{Call: call}
}

// MockReporterCheckCall wrap *gomock.Call
type MockReporterCheckCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReporterCheckCall) Return(arg0 Receipt, arg1 error) *MockReporterCheckCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReporterCheckCall) Do(f func(context.Context, CheckRequest) (Receipt, error)) *MockReporterCheckCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReporterCheckCall) DoAndReturn(f func(context.Context, CheckRequest) (Receipt, error)) *MockReporterCheckCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Comment mocks base method.
func (m *MockReporter) Comment(ctx context.Context, req CommentRequest) (Receipt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Comment", ctx, req)
	ret0, _ := ret[0].(Receipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Comment indicates an expected call of Comment.
func (mr *MockReporterMockRecorder) Comment(ctx, req any) *MockReporterCommentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Comment", reflect.TypeOf((*MockReporter)(nil).Comment), ctx, req)
	return &MockReporterCommentCall{Call: call}
}

// MockReporterCommentCall wrap *gomock.Call
type MockReporterCommentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReporterCommentCall) Return(arg0 Receipt, arg1 error) *MockReporterCommentCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReporterCommentCall) Do(f func(context.Context, CommentRequest) (Receipt, error)) *MockReporterCommentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReporterCommentCall) DoAndReturn(f func(context.Context, CommentRequest) (Receipt, error)) *MockReporterCommentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Context mocks base method.
func (m *MockReporter) Context() (*Context, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(*Context)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Context indicates an expected call of Context.
func (mr *MockReporterMockRecorder) Context() *MockReporterContextCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockReporter)(nil).Context))
	return &MockReporterContextCall{Call: call}
}

// MockReporterContextCall wrap *gomock.Call
type MockReporterContextCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReporterContextCall) Return(arg0 *Context, arg1 error) *MockReporterContextCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReporterContextCall) Do(f func() (*Context, error)) *MockReporterContextCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReporterContextCall) DoAndReturn(f func() (*Context, error)) *MockReporterContextCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Env mocks base method.
func (m *MockReporter) Env(key, value string) (Receipt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Env", key, value)
	ret0, _ := ret[0].(Receipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Env indicates an expected call of Env.
func (mr *MockReporterMockRecorder) Env(key, value any) *MockReporterEnvCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Env", reflect.TypeOf((*MockReporter)(nil).Env), key, value)
	return &MockReporterEnvCall{Call: call}
}

// MockReporterEnvCall wrap *gomock.Call
type MockReporterEnvCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReporterEnvCall) Return(arg0 Receipt, arg1 error) *MockReporterEnvCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReporterEnvCall) Do(f func(string, string) (Receipt, error)) *MockReporterEnvCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReporterEnvCall) DoAndReturn(f func(string, string) (Receipt, error)) *MockReporterEnvCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Group mocks base method.
func (m *MockReporter) Group(title string) (func(), Receipt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Group", title)
	ret0, _ := ret[0].(func())
	ret1, _ := ret[1].(Receipt)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Group indicates an expected call of Group.
func (mr *MockReporterMockRecorder) Group(title any) *MockReporterGroupCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Group", reflect.TypeOf((*MockReporter)(nil).Group), title)
	return &MockReporterGroupCall{Call: call}
}

// MockReporterGroupCall wrap *gomock.Call
type MockReporterGroupCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReporterGroupCall) Return(end func(), receipt Receipt, err error) *MockReporterGroupCall {
	c.Call = c.Call.Return(end, receipt, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReporterGroupCall) Do(f func(string) (func(), Receipt, error)) *MockReporterGroupCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReporterGroupCall) DoAndReturn(f func(string) (func(), Receipt, error)) *MockReporterGroupCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Mask mocks base method.
func (m *MockReporter) Mask(value string) (Receipt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Mask", value)
	ret0, _ := ret[0].(Receipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Mask indicates an expected call of Mask.
func (mr *MockReporterMockRecorder) Mask(value any) *MockReporterMaskCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mask", reflect.TypeOf((*MockReporter)(nil).Mask), value)
	return &MockReporterMaskCall{Call: call}
}

// MockReporterMaskCall wrap *gomock.Call
type MockReporterMaskCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReporterMaskCall) Return(arg0 Receipt, arg1 error) *MockReporterMaskCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReporterMaskCall) Do(f func(string) (Receipt, error)) *MockReporterMaskCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReporterMaskCall) DoAndReturn(f func(string) (Receipt, error)) *MockReporterMaskCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Output mocks base method.
func (m *MockReporter) Output(key, value string) (Receipt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Output", key, value)
	ret0, _ := ret[0].(Receipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Output indicates an expected call of Output.
func (mr *MockReporterMockRecorder) Output(key, value any) *MockReporterOutputCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Output", reflect.TypeOf((*MockReporter)(nil).Output), key, value)
	return &MockReporterOutputCall{Call: call}
}

// MockReporterOutputCall wrap *gomock.Call
type MockReporterOutputCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReporterOutputCall) Return(arg0 Receipt, arg1 error) *MockReporterOutputCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReporterOutputCall) Do(f func(string, string) (Receipt, error)) *MockReporterOutputCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReporterOutputCall) DoAndReturn(f func(string, string) (Receipt, error)) *MockReporterOutputCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Path mocks base method.
func (m *MockReporter) Path(dir string) (Receipt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Path", dir)
	ret0, _ := ret[0].(Receipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Path indicates an expected call of Path.
func (mr *MockReporterMockRecorder) Path(dir any) *MockReporterPathCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Path", reflect.TypeOf((*MockReporter)(nil).Path), dir)
	return &MockReporterPathCall{Call: call}
}

// MockReporterPathCall wrap *gomock.Call
type MockReporterPathCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReporterPathCall) Return(arg0 Receipt, arg1 error) *MockReporterPathCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReporterPathCall) Do(f func(string) (Receipt, error)) *MockReporterPathCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReporterPathCall) DoAndReturn(f func(string) (Receipt, error)) *MockReporterPathCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RenderComment mocks base method.
func (m *MockReporter) RenderComment(name string, data any) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenderComment", name, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RenderComment indicates an expected call of RenderComment.
func (mr *MockReporterMockRecorder) RenderComment(name, data any) *MockReporterRenderCommentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderComment", reflect.TypeOf((*MockReporter)(nil).RenderComment), name, data)
	return &MockReporterRenderCommentCall{Call: call}
}

// MockReporterRenderCommentCall wrap *gomock.Call
type MockReporterRenderCommentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReporterRenderCommentCall) Return(arg0 string, arg1 error) *MockReporterRenderCommentCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReporterRenderCommentCall) Do(f func(string, any) (string, error)) *MockReporterRenderCommentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReporterRenderCommentCall) DoAndReturn(f func(string, any) (string, error)) *MockReporterRenderCommentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RenderSummary mocks base method.
func (m *MockReporter) RenderSummary(name string, data any) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenderSummary", name, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RenderSummary indicates an expected call of RenderSummary.
func (mr *MockReporterMockRecorder) RenderSummary(name, data any) *MockReporterRenderSummaryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderSummary", reflect.TypeOf((*MockReporter)(nil).RenderSummary), name, data)
	return &MockReporterRenderSummaryCall{Call: call}
}

// MockReporterRenderSummaryCall wrap *gomock.Call
type MockReporterRenderSummaryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReporterRenderSummaryCall) Return(arg0 string, arg1 error) *MockReporterRenderSummaryCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReporterRenderSummaryCall) Do(f func(string, any) (string, error)) *MockReporterRenderSummaryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReporterRenderSummaryCall) DoAndReturn(f func(string, any) (string, error)) *MockReporterRenderSummaryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SARIF mocks base method.
func (m *MockReporter) SARIF(ctx context.Context, report SARIFReport) (Receipt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SARIF", ctx, report)
	ret0, _ := ret[0].(Receipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SARIF indicates an expected call of SARIF.
func (mr *MockReporterMockRecorder) SARIF(ctx, report any) *MockReporterSARIFCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SARIF", reflect.TypeOf((*MockReporter)(nil).SARIF), ctx, report)
	return &MockReporterSARIFCall{Call: call}
}

// MockReporterSARIFCall wrap *gomock.Call
type MockReporterSARIFCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReporterSARIFCall) Return(arg0 Receipt, arg1 error) *MockReporterSARIFCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReporterSARIFCall) Do(f func(context.Context, SARIFReport) (Receipt, error)) *MockReporterSARIFCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReporterSARIFCall) DoAndReturn(f func(context.Context, SARIFReport) (Receipt, error)) *MockReporterSARIFCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Summary mocks base method.
func (m *MockReporter) Summary(markdown string) (Receipt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Summary", markdown)
	ret0, _ := ret[0].(Receipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Summary indicates an expected call of Summary.
func (mr *MockReporterMockRecorder) Summary(markdown any) *MockReporterSummaryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Summary", reflect.TypeOf((*MockReporter)(nil).Summary), markdown)
	return &MockReporterSummaryCall{Call: call}
}

// MockReporterSummaryCall wrap *gomock.Call
type MockReporterSummaryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReporterSummaryCall) Return(arg0 Receipt, arg1 error) *MockReporterSummaryCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReporterSummaryCall) Do(f func(string) (Receipt, error)) *MockReporterSummaryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReporterSummaryCall) DoAndReturn(f func(string) (Receipt, error)) *MockReporterSummaryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateCheck mocks base method.
func (m *MockReporter) UpdateCheck(ctx context.Context, req CheckRequest) (Receipt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCheck", ctx, req)
	ret0, _ := ret[0].(Receipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCheck indicates an expected call of UpdateCheck.
func (mr *MockReporterMockRecorder) UpdateCheck(ctx, req any) *MockReporterUpdateCheckCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCheck", reflect.TypeOf((*MockReporter)(nil).UpdateCheck), ctx, req)
	return &MockReporterUpdateCheckCall{Call: call}
}

// MockReporterUpdateCheckCall wrap *gomock.Call
type MockReporterUpdateCheckCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReporterUpdateCheckCall) Return(arg0 Receipt, arg1 error) *MockReporterUpdateCheckCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReporterUpdateCheckCall) Do(f func(context.Context, CheckRequest) (Receipt, error)) *MockReporterUpdateCheckCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReporterUpdateCheckCall) DoAndReturn(f func(context.Context, CheckRequest) (Receipt, error)) *MockReporterUpdateCheckCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// WithOutput mocks base method.
func (m *MockReporter) WithOutput(w io.Writer) Reporter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithOutput", w)
	ret0, _ := ret[0].(Reporter)
	return ret0
}

// WithOutput indicates an expected call of WithOutput.
func (mr *MockReporterMockRecorder) WithOutput(w any) *MockReporterWithOutputCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithOutput", reflect.TypeOf((*MockReporter)(nil).WithOutput), w)
	return &MockReporterWithOutputCall{Call: call}
}

// MockReporterWithOutputCall wrap *gomock.Call
type MockReporterWithOutputCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReporterWithOutputCall) Return(arg0 Reporter) *MockReporterWithOutputCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReporterWithOutputCall) Do(f func(io.Writer) Reporter) *MockReporterWithOutputCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReporterWithOutputCall) DoAndReturn(f func(io.Writer) Reporter) *MockReporterWithOutputCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
