// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cloudposse/atmos/pkg/ci/internal/plugin (interfaces: Plugin,ComponentConfigurationResolver)
//
// Generated by this command:
//
//	mockgen -typed -destination=mock_plugin_test.go -package=ci github.com/cloudposse/atmos/pkg/ci/internal/plugin Plugin,ComponentConfigurationResolver
//

// Package ci is a generated GoMock package.
package ci

import (
	embed "embed"
	reflect "reflect"

	plugin "github.com/cloudposse/atmos/pkg/ci/internal/plugin"
	provider "github.com/cloudposse/atmos/pkg/ci/internal/provider"
	schema "github.com/cloudposse/atmos/pkg/schema"
	gomock "go.uber.org/mock/gomock"
)

// MockPlugin is a mock of Plugin interface.
type MockPlugin struct {
	ctrl     *gomock.Controller
	recorder *MockPluginMockRecorder
	isgomock struct{}
}

// MockPluginMockRecorder is the mock recorder for MockPlugin.
type MockPluginMockRecorder struct {
	mock *MockPlugin
}

// NewMockPlugin creates a new mock instance.
func NewMockPlugin(ctrl *gomock.Controller) *MockPlugin {
	mock := &MockPlugin{ctrl: ctrl}
	mock.recorder = &MockPluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlugin) EXPECT() *MockPluginMockRecorder {
	return m.recorder
}

// BuildTemplateContext mocks base method.
func (m *MockPlugin) BuildTemplateContext(info *schema.ConfigAndStacksInfo, ciCtx *provider.Context, output, command string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildTemplateContext", info, ciCtx, output, command)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildTemplateContext indicates an expected call of BuildTemplateContext.
func (mr *MockPluginMockRecorder) BuildTemplateContext(info, ciCtx, output, command any) *MockPluginBuildTemplateContextCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildTemplateContext", reflect.TypeOf((*MockPlugin)(nil).BuildTemplateContext), info, ciCtx, output, command)
	return &MockPluginBuildTemplateContextCall{Call: call}
}

// MockPluginBuildTemplateContextCall wrap *gomock.Call
type MockPluginBuildTemplateContextCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPluginBuildTemplateContextCall) Return(arg0 any, arg1 error) *MockPluginBuildTemplateContextCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPluginBuildTemplateContextCall) Do(f func(*schema.ConfigAndStacksInfo, *provider.Context, string, string) (any, error)) *MockPluginBuildTemplateContextCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPluginBuildTemplateContextCall) DoAndReturn(f func(*schema.ConfigAndStacksInfo, *provider.Context, string, string) (any, error)) *MockPluginBuildTemplateContextCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetArtifactKey mocks base method.
func (m *MockPlugin) GetArtifactKey(info *schema.ConfigAndStacksInfo, command string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArtifactKey", info, command)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetArtifactKey indicates an expected call of GetArtifactKey.
func (mr *MockPluginMockRecorder) GetArtifactKey(info, command any) *MockPluginGetArtifactKeyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArtifactKey", reflect.TypeOf((*MockPlugin)(nil).GetArtifactKey), info, command)
	return &MockPluginGetArtifactKeyCall{Call: call}
}

// MockPluginGetArtifactKeyCall wrap *gomock.Call
type MockPluginGetArtifactKeyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPluginGetArtifactKeyCall) Return(arg0 string) *MockPluginGetArtifactKeyCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPluginGetArtifactKeyCall) Do(f func(*schema.ConfigAndStacksInfo, string) string) *MockPluginGetArtifactKeyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPluginGetArtifactKeyCall) DoAndReturn(f func(*schema.ConfigAndStacksInfo, string) string) *MockPluginGetArtifactKeyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetDefaultTemplates mocks base method.
func (m *MockPlugin) GetDefaultTemplates() embed.FS {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultTemplates")
	ret0, _ := ret[0].(embed.FS)
	return ret0
}

// GetDefaultTemplates indicates an expected call of GetDefaultTemplates.
func (mr *MockPluginMockRecorder) GetDefaultTemplates() *MockPluginGetDefaultTemplatesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultTemplates", reflect.TypeOf((*MockPlugin)(nil).GetDefaultTemplates))
	return &MockPluginGetDefaultTemplatesCall{Call: call}
}

// MockPluginGetDefaultTemplatesCall wrap *gomock.Call
type MockPluginGetDefaultTemplatesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPluginGetDefaultTemplatesCall) Return(arg0 embed.FS) *MockPluginGetDefaultTemplatesCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPluginGetDefaultTemplatesCall) Do(f func() embed.FS) *MockPluginGetDefaultTemplatesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPluginGetDefaultTemplatesCall) DoAndReturn(f func() embed.FS) *MockPluginGetDefaultTemplatesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetHookBindings mocks base method.
func (m *MockPlugin) GetHookBindings() []plugin.HookBinding {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHookBindings")
	ret0, _ := ret[0].([]plugin.HookBinding)
	return ret0
}

// GetHookBindings indicates an expected call of GetHookBindings.
func (mr *MockPluginMockRecorder) GetHookBindings() *MockPluginGetHookBindingsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHookBindings", reflect.TypeOf((*MockPlugin)(nil).GetHookBindings))
	return &MockPluginGetHookBindingsCall{Call: call}
}

// MockPluginGetHookBindingsCall wrap *gomock.Call
type MockPluginGetHookBindingsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPluginGetHookBindingsCall) Return(arg0 []plugin.HookBinding) *MockPluginGetHookBindingsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPluginGetHookBindingsCall) Do(f func() []plugin.HookBinding) *MockPluginGetHookBindingsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPluginGetHookBindingsCall) DoAndReturn(f func() []plugin.HookBinding) *MockPluginGetHookBindingsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetOutputVariables mocks base method.
func (m *MockPlugin) GetOutputVariables(result *plugin.OutputResult, command string) map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOutputVariables", result, command)
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// GetOutputVariables indicates an expected call of GetOutputVariables.
func (mr *MockPluginMockRecorder) GetOutputVariables(result, command any) *MockPluginGetOutputVariablesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOutputVariables", reflect.TypeOf((*MockPlugin)(nil).GetOutputVariables), result, command)
	return &MockPluginGetOutputVariablesCall{Call: call}
}

// MockPluginGetOutputVariablesCall wrap *gomock.Call
type MockPluginGetOutputVariablesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPluginGetOutputVariablesCall) Return(arg0 map[string]string) *MockPluginGetOutputVariablesCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPluginGetOutputVariablesCall) Do(f func(*plugin.OutputResult, string) map[string]string) *MockPluginGetOutputVariablesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPluginGetOutputVariablesCall) DoAndReturn(f func(*plugin.OutputResult, string) map[string]string) *MockPluginGetOutputVariablesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetType mocks base method.
func (m *MockPlugin) GetType() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetType")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetType indicates an expected call of GetType.
func (mr *MockPluginMockRecorder) GetType() *MockPluginGetTypeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetType", reflect.TypeOf((*MockPlugin)(nil).GetType))
	return &MockPluginGetTypeCall{Call: call}
}

// MockPluginGetTypeCall wrap *gomock.Call
type MockPluginGetTypeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPluginGetTypeCall) Return(arg0 string) *MockPluginGetTypeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPluginGetTypeCall) Do(f func() string) *MockPluginGetTypeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPluginGetTypeCall) DoAndReturn(f func() string) *MockPluginGetTypeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ParseOutput mocks base method.
func (m *MockPlugin) ParseOutput(output, command string) (*plugin.OutputResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseOutput", output, command)
	ret0, _ := ret[0].(*plugin.OutputResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseOutput indicates an expected call of ParseOutput.
func (mr *MockPluginMockRecorder) ParseOutput(output, command any) *MockPluginParseOutputCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseOutput", reflect.TypeOf((*MockPlugin)(nil).ParseOutput), output, command)
	return &MockPluginParseOutputCall{Call: call}
}

// MockPluginParseOutputCall wrap *gomock.Call
type MockPluginParseOutputCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPluginParseOutputCall) Return(arg0 *plugin.OutputResult, arg1 error) *MockPluginParseOutputCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPluginParseOutputCall) Do(f func(string, string) (*plugin.OutputResult, error)) *MockPluginParseOutputCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPluginParseOutputCall) DoAndReturn(f func(string, string) (*plugin.OutputResult, error)) *MockPluginParseOutputCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockComponentConfigurationResolver is a mock of ComponentConfigurationResolver interface.
type MockComponentConfigurationResolver struct {
	ctrl     *gomock.Controller
	recorder *MockComponentConfigurationResolverMockRecorder
	isgomock struct{}
}

// MockComponentConfigurationResolverMockRecorder is the mock recorder for MockComponentConfigurationResolver.
type MockComponentConfigurationResolverMockRecorder struct {
	mock *MockComponentConfigurationResolver
}

// NewMockComponentConfigurationResolver creates a new mock instance.
func NewMockComponentConfigurationResolver(ctrl *gomock.Controller) *MockComponentConfigurationResolver {
	mock := &MockComponentConfigurationResolver{ctrl: ctrl}
	mock.recorder = &MockComponentConfigurationResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockComponentConfigurationResolver) EXPECT() *MockComponentConfigurationResolverMockRecorder {
	return m.recorder
}

// ResolveComponentPlanfilePath mocks base method.
func (m *MockComponentConfigurationResolver) ResolveComponentPlanfilePath(atmosConfig *schema.AtmosConfiguration, info *schema.ConfigAndStacksInfo) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveComponentPlanfilePath", atmosConfig, info)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveComponentPlanfilePath indicates an expected call of ResolveComponentPlanfilePath.
func (mr *MockComponentConfigurationResolverMockRecorder) ResolveComponentPlanfilePath(atmosConfig, info any) *MockComponentConfigurationResolverResolveComponentPlanfilePathCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveComponentPlanfilePath", reflect.TypeOf((*MockComponentConfigurationResolver)(nil).ResolveComponentPlanfilePath), atmosConfig, info)
	return &MockComponentConfigurationResolverResolveComponentPlanfilePathCall{Call: call}
}

// MockComponentConfigurationResolverResolveComponentPlanfilePathCall wrap *gomock.Call
type MockComponentConfigurationResolverResolveComponentPlanfilePathCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockComponentConfigurationResolverResolveComponentPlanfilePathCall) Return(arg0 string, arg1 error) *MockComponentConfigurationResolverResolveComponentPlanfilePathCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockComponentConfigurationResolverResolveComponentPlanfilePathCall) Do(f func(*schema.AtmosConfiguration, *schema.ConfigAndStacksInfo) (string, error)) *MockComponentConfigurationResolverResolveComponentPlanfilePathCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockComponentConfigurationResolverResolveComponentPlanfilePathCall) DoAndReturn(f func(*schema.AtmosConfiguration, *schema.ConfigAndStacksInfo) (string, error)) *MockComponentConfigurationResolverResolveComponentPlanfilePathCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
