{{- if .Values.hooks.readyMarker }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ready
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/resource-policy": keep
data:
  ready: "true"
{{- end }}
