/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

const {stackConfiguration} = require('./sidebars/stacks');
const continuousIntegration = require('./sidebars/ci');
const {componentLibraryItems} = require('./sidebars/component-library');

// Visual separators in the Reference index, not another navigation level.
const referenceGroup = (label) => ({
    type: 'html',
    value: `<h3 class="reference-group-label">${label}</h3>`,
    defaultStyle: false,
    customProps: {navigationGroup: label},
});

module.exports = {
    tutorials: [
        {
            type: 'category',
            label: 'Tutorials Index Page',
            link: {
                type: 'doc',
                id: 'tutorials/tutorials'
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'tutorials',
                }
            ]
        }
    ],
    community: [
        {
            type: 'category',
            label: 'Community',
            className: 'sidebar-title',
            collapsible: true,
            collapsed: true,
            link: {type: 'doc', id: 'community/community'},
            items: ['community/slack', 'community/office-hours']
        },
        {
            type: 'category',
            label: 'Contribute',
            className: 'sidebar-title',
            collapsible: true,
            collapsed: true,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'contribute',
                }
            ]
        }
    ],
    docs: [
        {type: 'doc', id: 'learn/index', label: 'Learn', customProps: {navigationOverview: true}},
        {
            type: 'category',
            label: 'Get Started',
            description: 'Install Atmos, explore its features, and migrate existing infrastructure.',
            className: 'sidebar-title',
            collapsible: true,
            collapsed: true,
            link: {type: 'doc', id: 'intro/index'},
            items: [
                'quick-start/install-atmos',
                'intro/features',
                'intro/use-cases',
                'intro/faq',
                {
                    type: 'category',
                    label: 'Migration Guides',
                    collapsible: true,
                    collapsed: false,
                    items: [
                        'migration/native-terraform',
                        'migration/terragrunt',
                        'migration/terraform-workspaces',
                        'migration/terramate',
                        {
                            type: 'category',
                            label: 'Task Runners',
                            collapsible: true,
                            collapsed: true,
                            items: [
                                'migration/makefile',
                                'migration/justfile',
                                'migration/taskfile',
                            ]
                        }
                    ]
                },
            ]
        },

        {
            type: 'category',
            label: 'Learn Atmos',
            description: 'Understand the concepts, YAML configuration, and stacks.',
            className: 'sidebar-title',
            collapsible: true,
            collapsed: true,
            link: {type: 'doc', id: 'learn/why-atmos'},
            items: [
                'learn/mindset',
                'learn/concepts-overview',
                'learn/yaml-guide',
                'learn/stacks/learn-stacks',
            ]
        },
        {
            type: 'category',
            label: 'Your First Stack',
            description: 'Build a stack with imports, inheritance, and connected components.',
            className: 'sidebar-title',
            collapsible: true,
            collapsed: true,
            link: {type: 'doc', id: 'learn/first-stack'},
            items: [
                'learn/imports-basics',
                'learn/inheritance-basics',
                'learn/organizing-stacks',
                'learn/connecting-components',
                'learn/next-steps',
            ]
        },
        {
            type: 'category',
            label: 'Quick Start',
            description: 'Follow a hands-on tutorial to deploy infrastructure with Atmos.',
            className: 'sidebar-title',
            collapsible: true,
            collapsed: true,
            items: [
                {
                    type: 'category',
                    label: 'Simple Tutorial',
                    collapsible: true,
                    collapsed: true,
                    link: {type: 'doc', id: 'quick-start/simple/simple'},
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'quick-start/simple',
                        },
                    ]
                },
                {
                    type: 'category',
                    label: 'Advanced Tutorial',
                    collapsible: true,
                    collapsed: true,
                    link: {type: 'doc', id: 'quick-start/advanced/advanced'},
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'quick-start/advanced',
                        },
                    ]
                },
            ]
        },
        {
            type: 'category',
            label: 'Best Practices',
            description: 'Organize infrastructure with proven conventions and design patterns.',
            className: 'sidebar-title',
            collapsible: true,
            collapsed: true,
            link: {type: 'doc', id: 'best-practices/best-practices'},
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'best-practices',
                },
                {
                    type: 'category',
                    label: 'Use Design Patterns',
                    collapsible: true,
                    collapsed: true,
                    link: {type: 'doc', id: 'design-patterns/design-patterns'},
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'design-patterns',
                        },
                    ]
                }
            ]
        },
        {
            type: 'category',
            label: 'Troubleshoot',
            description: 'Resolve common errors and investigate performance issues.',
            className: 'sidebar-title',
            collapsible: true,
            collapsed: true,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'troubleshoot',
                },
            ]
        }
    ],
    cli: [
        {type: 'doc', id: 'reference-overview', label: 'Reference', customProps: {navigationOverview: true}},
        referenceGroup('CLI essentials'),
        {
            type: 'category',
            label: 'Commands',
            className: 'sidebar-title',
            collapsible: true,
            collapsed: true,
            link: {type: 'doc', id: 'cli/commands/commands'},
            items: [
                {type: 'doc', id: 'cli/cli', label: 'atmos (Interactive)'},
                {
                    type: 'autogenerated',
                    dirName: 'cli/commands',
                },
            ]
        },
        {type: 'doc', id: 'cli/global-flags', label: 'Global Flags'},
        {type: 'doc', id: 'cli/environment-variables', label: 'Environment Variables'},
        {type: 'doc', id: 'cli/versioning', label: 'Versioning'},
        referenceGroup('Capabilities'),
        continuousIntegration,
        {
            type: 'category',
            label: 'Atmos AI & MCP',
            link: {type: 'doc', id: 'ai/ai'},
            items: [
                {type: 'link', label: 'Agent Skills', href: '/ai/skills'},
                {type: 'doc', id: 'mcp/mcp', label: 'MCP'},
            ]
        },
        {type: 'doc', id: 'pro/pro', label: 'Atmos Pro'},
        {
            type: 'category',
            label: 'Editor Integration',
            link: {type: 'doc', id: 'projects/setup-editor/index'},
            items: [
                {type: 'doc', id: 'projects/setup-editor/setup-ai-assistants', label: 'AI Assistants'},
                {type: 'doc', id: 'ai/claude-code-integration', label: 'Claude Code'},
                {type: 'doc', id: 'ai/mcp-server', label: 'MCP Server'},
                {
                    type: 'category',
                    label: 'LSP',
                    link: {type: 'doc', id: 'lsp/lsp'},
                    items: [
                        {type: 'doc', id: 'lsp/lsp-server', label: 'LSP Server'},
                        {type: 'doc', id: 'lsp/lsp-client', label: 'LSP Client'},
                    ]
                },
            ]
        },
        referenceGroup('Configuration'),
        {
            type: 'category',
            label: 'CLI Configuration',
            className: 'sidebar-title',
            collapsible: true,
            collapsed: true,
            link: {type: 'doc', id: 'cli/configuration/configuration'},
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'cli/configuration',
                },
            ]
        },
        stackConfiguration,
        {
            type: 'category',
            label: 'Component Library',
            className: 'sidebar-title',
            collapsible: true,
            collapsed: true,
            link: {type: 'doc', id: 'components/components-overview'},
            items: componentLibraryItems(),
        },


        referenceGroup('Automation'),
        {
            type: 'category',
            label: 'Scripting',
            className: 'sidebar-title',
            collapsible: true,
            collapsed: true,
            link: {type: 'doc', id: 'automation/automation'},
            items: [
                {type: 'doc', id: 'automation/language'},
                {
                    type: 'category',
                    label: 'Language Reference',
                    link: {type: 'doc', id: 'automation/reference/index'},
                    collapsible: true,
                    collapsed: true,
                    items: [
                        {type: 'doc', id: 'automation/reference/lexical-elements'},
                        {type: 'doc', id: 'automation/reference/data-types'},
                        {type: 'doc', id: 'automation/reference/expressions-operators'},
                        {type: 'doc', id: 'automation/reference/statements'},
                        {type: 'doc', id: 'automation/reference/builtin-functions'},
                        {type: 'doc', id: 'automation/reference/methods'},
                        {type: 'doc', id: 'automation/reference/execution-model'},
                        {type: 'doc', id: 'automation/reference/differences-from-python'},
                    ]
                },
                {type: 'doc', id: 'automation/standalone-cli-apps'},
                {type: 'doc', id: 'automation/custom-commands'},
                {type: 'doc', id: 'automation/workflows'},
                {type: 'doc', id: 'automation/lifecycle-hooks'},
                {type: 'doc', id: 'automation/testing'},
            ]
        },
        {
            type: 'category',
            label: 'Workflows',
            className: 'sidebar-title',
            collapsible: true,
            collapsed: true,
            link: {type: 'doc', id: 'workflows/workflows/index'},
            items: [
                {
                    type: 'category',
                    label: 'workflows',
                    collapsed: true,
                    link: {type: 'doc', id: 'workflows/workflows/workflow/index'},
                    items: [
                        {
                            type: 'category',
                            label: '<name>',
                            link: {type: 'doc', id: 'workflows/name'},
                            customProps: {title: 'Workflow names'},
                            collapsed: false,
                            items: [
                                {type: 'doc', id: 'workflows/workflows/workflow/stack', label: 'stack'},
                                {type: 'doc', id: 'workflows/workflows/workflow/env', label: 'env'},
                                {type: 'doc', id: 'workflows/workflows/workflow/working-directory', label: 'working_directory'},
                                {type: 'doc', id: 'workflows/workflows/workflow/dependencies', label: 'dependencies'},
                                {type: 'doc', id: 'workflows/workflows/workflow/container', label: 'container'},
                                {type: 'doc', id: 'workflows/workflows/workflow/output', label: 'output'},
                                {type: 'doc', id: 'workflows/workflows/workflow/show', label: 'show'},
                                {type: 'link', label: 'steps', href: '/steps', customProps: {navigationReference: true}},
                            ],
                        },
                    ],
                },
            ]
        },

        {
            type: 'category',
            label: 'Steps',
            className: 'sidebar-title',
            link: {type: 'doc', id: 'steps/index'},
            items: [
                {
                    type: 'category',
                    label: 'Step types',
                    link: {type: 'doc', id: 'steps/type'},
                    items: [{type: 'autogenerated', dirName: 'steps/type'}],
                },
                {
                    type: 'category',
                    label: 'Step configuration',
                    link: {type: 'doc', id: 'steps/configuration'},
                    items: [
                        {type: 'doc', id: 'steps/artifacts', label: 'artifacts'},
                        {type: 'doc', id: 'steps/container', label: 'container'},
                        {type: 'doc', id: 'steps/continue', label: 'continue'},
                        {type: 'doc', id: 'steps/env', label: 'env'},
                        {type: 'doc', id: 'steps/identity', label: 'identity'},
                        {type: 'doc', id: 'steps/inputs', label: 'inputs'},
                        {type: 'doc', id: 'steps/interactive', label: 'interactive'},
                        {type: 'doc', id: 'steps/output', label: 'output'},
                        {type: 'doc', id: 'steps/outputs', label: 'outputs'},
                        {type: 'doc', id: 'steps/preconditions', label: 'preconditions'},
                        {type: 'doc', id: 'steps/retry', label: 'retry'},
                        {type: 'doc', id: 'steps/show', label: 'show'},
                        {type: 'doc', id: 'steps/tty', label: 'tty'},
                        {type: 'doc', id: 'steps/working-directory', label: 'working_directory'},
                    ],
                },
                {
                    type: 'category',
                    label: 'Using steps',
                    items: [
                        {type: 'link', label: 'Workflows', href: '/workflows'},
                        {type: 'link', label: 'Custom commands', href: '/cli/configuration/commands/steps'},
                        {type: 'link', label: 'Lifecycle hooks', href: '/stacks/hooks#kind-step-run-a-step-type'},
                    ],
                },
            ],
        },

        {
            type: 'category',
            label: 'Vendoring',
            className: 'sidebar-title',
            collapsible: true,
            collapsed: true,
            link: {type: 'doc', id: 'vendor/vendor'},
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'vendor',
                },
            ]
        },

        {
            type: 'category',
            label: 'Functions',
            className: 'sidebar-title',
            collapsible: true,
            collapsed: true,
            link: {type: 'doc', id: 'functions/index'},
            items: [
                {
                    type: 'category',
                    label: 'YAML Functions',
                    link: {type: 'doc', id: 'functions/yaml/index'},
                    collapsible: true,
                    collapsed: true,
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'functions/yaml',
                        }
                    ]
                },
                {
                    type: 'category',
                    label: 'Template Functions',
                    link: {type: 'doc', id: 'functions/template/index'},
                    collapsible: true,
                    collapsed: true,
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'functions/template',
                        }
                    ]
                },
                {
                    type: 'category',
                    label: 'Automation Functions',
                    link: {type: 'doc', id: 'functions/automation/index'},
                    collapsible: true,
                    collapsed: true,
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'functions/automation',
                        }
                    ]
                }
            ]
        },

        {
            type: 'category',
            label: 'Validation',
            className: 'sidebar-title',
            collapsible: true,
            collapsed: true,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'validation',
                },
            ]
        },

        referenceGroup('Guides & resources'),
        {
            type: 'category',
            label: 'How-To Guides',
            className: 'sidebar-title',
            collapsible: true,
            collapsed: true,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'howto',
                },
                {
                    type: 'category',
                    label: 'Sharing State',
                    collapsible: true,
                    collapsed: true,
                    link: {type: 'doc', id: 'tutorials/sharing-state/sharing-state'},
                    items: [
                        {type: 'doc', id: 'tutorials/sharing-state/terraform-state', label: '!terraform.state (Recommended)'},
                        {type: 'doc', id: 'tutorials/sharing-state/terraform-output', label: '!terraform.output'},
                        {type: 'doc', id: 'tutorials/sharing-state/remote-state-module', label: 'Remote State Module'},
                        {type: 'doc', id: 'tutorials/sharing-state/stores', label: '!store'},
                    ]
                },
                {type: 'doc', id: 'templates/templates', label: 'Template Configurations'},
                {type: 'doc', id: 'templates/datasources', label: 'Use Data Sources'},
                {
                    type: 'category',
                    label: 'Design Patterns',
                    collapsible: true,
                    collapsed: true,
                    link: {type: 'doc', id: 'design-patterns/design-patterns'},
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'design-patterns',
                        },
                    ]
                }
            ]
        },

        {type: 'doc', id: 'projects/layout', label: 'Project Layout'},
        {
            type: 'category',
            label: 'Resources',
            className: 'sidebar-title',
            collapsible: true,
            collapsed: true,
            items: [
                {type: 'link', href: '/media-kit', label: 'Media Kit'},
                {
                    type: 'autogenerated',
                    dirName: 'reference',
                },
                {
                    type: 'category',
                    label: 'Cheat Sheets',
                    collapsible: true,
                    collapsed: true,
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'cheatsheets',
                        },
                    ]
                },
                {
                    type: 'category',
                    label: 'Terraform Maturity Journey',
                    collapsible: true,
                    collapsed: true,
                    link: {type: 'doc', id: 'intro/why-atmos/why-atmos'},
                    // This is a sequence; keep the overview only as the category link.
                    items: [
                        'intro/why-atmos/stage-0',
                        'intro/why-atmos/stage-1',
                        'intro/why-atmos/stage-2',
                        'intro/why-atmos/stage-3',
                        'intro/why-atmos/stage-4',
                        'intro/why-atmos/stage-5',
                        'intro/why-atmos/stage-6',
                        'intro/why-atmos/stage-7',
                        'intro/why-atmos/stage-8',
                        'intro/why-atmos/stage-9',
                        'intro/why-atmos/stage-10',
                        'intro/why-atmos/nirvana',
                    ]
                },
                {
                    type: 'category',
                    label: 'Glossary',
                    collapsible: true,
                    collapsed: true,
                    link: {type: 'doc', id: 'glossary/glossary'},
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'glossary',
                        },
                    ]
                },
                {
                    type: 'category',
                    label: 'Deprecated',
                    collapsible: true,
                    collapsed: true,
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'deprecated',
                        },
                    ]
                }
            ]
        },
    ]
};

// Mobile menus render in the navbar, outside DocsSidebarProvider. Carry the
// sidebar identity on section data so desktop and mobile use the same control.
for (const [name, items] of Object.entries(module.exports)) {
    for (const item of items) {
        if (typeof item === 'object' && item.type === 'category') {
            item.customProps = {...item.customProps, navigationSidebar: name};
        }
    }
}
