/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

module.exports = {
    tutorials: [
        {
          type: 'category',
          label: 'Tutorials Index Page',
          link: {
            type: 'doc',
            id: 'tutorials/tutorials'
          },
          items: [
            {
                type: 'autogenerated',
                dirName: 'tutorials',
            }
          ]
        }
    ],
    community: [
        {
            type: 'category',
            label: 'Community',
            className: 'sidebar-title',
            collapsible: false,
            collapsed: false,
            link: {type: 'doc', id: 'community/community'},
            items: [ 'community/slack', 'community/office-hours' ]
        },
        {
          type: 'category',
          label: 'Contribute',
          className: 'sidebar-title',
          collapsible: false,
          collapsed: false,
          items: [
            {
                type: 'autogenerated',
                dirName: 'contribute',
            }
          ]
        }
    ],
    docs: [

        {
            type: 'category',
            label: 'Get Started',
            className: 'sidebar-title',
            collapsible: false,
            collapsed: false,
            link: {type: 'doc', id: 'intro/index'},
            items: [
                'quick-start/install-atmos',
                'intro/features',
                'intro/use-cases',
                'intro/faq',
                {
                    type: 'category',
                    label: 'Migration Guides',
                    collapsible: true,
                    collapsed: false,
                    items: [
                        'migration/native-terraform',
                        'migration/terragrunt',
                        'migration/terraform-workspaces'
                    ]
                },
            ]
        },

        {
            type: 'category',
            label: 'Learn Atmos',
            className: 'sidebar-title',
            collapsible: false,
            collapsed: false,
            link: {type: 'doc', id: 'learn/why-atmos'},
            items: [
                'learn/mindset',
                'learn/concepts-overview',
                'learn/yaml-guide',
                'learn/stacks/learn-stacks',
            ]
        },
        {
            type: 'category',
            label: 'Your First Stack',
            className: 'sidebar-title',
            collapsible: false,
            collapsed: false,
            link: {type: 'doc', id: 'learn/first-stack'},
            items: [
                'learn/imports-basics',
                'learn/inheritance-basics',
                'learn/organizing-stacks',
                'learn/connecting-components',
                'learn/next-steps',
            ]
        },
        {
            type: 'category',
            label: 'Quick Start',
            className: 'sidebar-title',
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'category',
                    label: 'Simple Tutorial',
                    collapsible: true,
                    collapsed: true,
                    link: {type: 'doc', id: 'quick-start/simple/simple'},
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'quick-start/simple',
                        },
                    ]
                },
                {
                    type: 'category',
                    label: 'Advanced Tutorial',
                    collapsible: true,
                    collapsed: true,
                    link: {type: 'doc', id: 'quick-start/advanced/advanced'},
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'quick-start/advanced',
                        },
                    ]
                },
            ]
        },
        {
            type: 'category',
            label: 'Best Practices',
            className: 'sidebar-title',
            collapsible: false,
            collapsed: false,
            link: {type: 'doc', id: 'best-practices/best-practices'},
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'best-practices',
                },
                {
                    type: 'category',
                    label: 'Use Design Patterns',
                    collapsible: true,
                    collapsed: true,
                    link: {type: 'doc', id: 'design-patterns/design-patterns'},
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'design-patterns',
                        },
                    ]
                }
            ]
        },
        {
            type: 'category',
            label: 'Troubleshoot',
            className: 'sidebar-title',
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'troubleshoot',
                },
            ]
        }
    ],
    cli: [
        {
            type: 'doc',
            id: 'cli/cli',
            label: 'atmos (Interactive)',
            className: 'sidebar-title',
        },
        {
            type: 'category',
            label: 'CLI',
            className: 'sidebar-title',
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'doc', id: 'cli/global-flags', label: 'Global Flags'},
                {type: 'doc', id: 'cli/environment-variables', label: 'Environment Variables'},
                {type: 'doc', id: 'cli/versioning', label: 'Versioning'},
                {type: 'doc', id: 'projects/layout', label: 'Folder Structure'},
                {type: 'doc', id: 'projects/setup-editor', label: 'Setup Editor (IDE)'},
            ]
        },
        {
            type: 'category',
            label: 'Commands',
            className: 'sidebar-title',
            collapsible: false,
            collapsed: false,
            link: {type: 'doc', id: 'cli/commands/commands'},
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'cli/commands',
                },
            ]
        },
        {
            type: 'category',
            label: 'CLI Configuration',
            className: 'sidebar-title',
            collapsible: false,
            collapsed: false,
            link: {type: 'doc', id: 'cli/configuration/configuration'},
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'cli/configuration',
                },
            ]
        },
        {
            type: 'category',
            label: 'Component Library',
            className: 'sidebar-title',
            collapsible: false,
            collapsed: false,
            link: {type: 'doc', id: 'components/components-overview'},
            items: [
                {
                    type: 'category',
                    label: 'Terraform/OpenTofu',
                    collapsible: true,
                    collapsed: true,
                    link: {type: 'doc', id: 'components/terraform/terraform'},
                    items: [
                        {type: 'doc', id: 'components/terraform/stack-config', label: 'Stack Configuration'},
                        {type: 'doc', id: 'components/terraform/root-modules', label: 'Root Modules'},
                        {type: 'doc', id: 'components/terraform/backends', label: 'State Backends'},
                        {type: 'doc', id: 'components/terraform/workspaces', label: 'Workspaces'},
                        {type: 'doc', id: 'components/terraform/providers', label: 'Provider Generation'},
                        {type: 'doc', id: 'components/terraform/planfiles', label: 'Planfiles'},
                        {type: 'doc', id: 'components/terraform/brownfield', label: 'Brownfield'},
                    ]
                },
                {
                    type: 'doc',
                    id: 'components/helmfile',
                    label: 'Helmfile',
                },
                {
                    type: 'doc',
                    id: 'components/packer',
                    label: 'Packer',
                },
            ]
        },

        {
            type: 'category',
            label: 'Stack Configuration',
            className: 'sidebar-title',
            collapsible: false,
            collapsed: false,
            link: {type: 'doc', id: 'stacks/stacks'},
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'stacks',
                },
            ]
        },

        {
            type: 'category',
            label: 'Vendor',
            className: 'sidebar-title',
            collapsible: false,
            collapsed: false,
            link: {type: 'doc', id: 'vendor/vendor'},
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'vendor',
                },
            ]
        },

        {
            type: 'category',
            label: 'How-To Guides',
            className: 'sidebar-title',
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'howto',
                },
                {
                    type: 'category',
                    label: 'Sharing State',
                    collapsible: true,
                    collapsed: true,
                    link: {type: 'doc', id: 'tutorials/sharing-state/sharing-state'},
                    items: [
                        {type: 'doc', id: 'tutorials/sharing-state/terraform-state', label: '!terraform.state (Recommended)'},
                        {type: 'doc', id: 'tutorials/sharing-state/terraform-output', label: '!terraform.output'},
                        {type: 'doc', id: 'tutorials/sharing-state/remote-state-module', label: 'Remote State Module'},
                        {type: 'doc', id: 'tutorials/sharing-state/stores', label: '!store'},
                    ]
                },
                {type: 'doc', id: 'templates/templates', label: 'Template Configurations'},
                {type: 'doc', id: 'templates/datasources', label: 'Use Data Sources'},
                {
                    type: 'category',
                    label: 'Design Patterns',
                    collapsible: true,
                    collapsed: true,
                    link: {type: 'doc', id: 'design-patterns/design-patterns'},
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'design-patterns',
                        },
                    ]
                }
            ]
        },

        {
            type: 'category',
            label: 'Functions',
            className: 'sidebar-title',
            collapsible: false,
            collapsed: false,
            link: {type: 'doc', id: 'functions/index'},
            items: [
                {
                    type: 'category',
                    label: 'YAML Functions',
                    link: {type: 'doc', id: 'functions/yaml/index'},
                    collapsible: true,
                    collapsed: false,
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'functions/yaml',
                        }
                    ]
                },
                {
                    type: 'category',
                    label: 'Template Functions',
                    link: {type: 'doc', id: 'functions/template/index'},
                    collapsible: true,
                    collapsed: false,
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'functions/template',
                        }
                    ]
                }
            ]
        },

        {
            type: 'category',
            label: 'Workflows',
            className: 'sidebar-title',
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'workflows',
                },
            ]
        },

        {
            type: 'category',
            label: 'Validation',
            className: 'sidebar-title',
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'validation',
                },
            ]
        },

        {
            type: 'category',
            label: 'GitHub Actions',
            className: 'sidebar-title',
            collapsible: false,
            collapsed: false,
            items: [
                    {
                        type: 'autogenerated',
                        dirName: 'integrations/github-actions',
                    }
            ]
        },
        {
            type: 'category',
            label: 'Resources',
            className: 'sidebar-title',
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'reference',
                },
                {
                    type: 'category',
                    label: 'Cheat Sheets',
                    collapsible: true,
                    collapsed: true,
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'cheatsheets',
                        },
                    ]
                },
                {
                    type: 'category',
                    label: 'Terraform Maturity Journey',
                    collapsible: true,
                    collapsed: true,
                    link: {type: 'doc', id: 'intro/why-atmos/why-atmos'},
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'intro/why-atmos',
                        },
                    ]
                },
                {
                    type: 'category',
                    label: 'Glossary',
                    collapsible: true,
                    collapsed: true,
                    link: {type: 'doc', id: 'glossary/glossary'},
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'glossary',
                        },
                    ]
                }
            ]
        },
    ]
};
