# yaml-language-server: $schema=https://atmos.tools/schemas/atmos/atmos-manifest/1.0/atmos-manifest.json

import:
  - _defaults

vars:
  stage: prod

components:
  terraform:
    foundation:
      vars:
        force_destroy: false
        secret_payload: prod-local-secret
