package step

import (
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

// builtInStepTypes is captured by TestMain after production init functions run,
// but before tests can register temporary handlers.
var builtInStepTypes []string

// registeredStepTypesForDocumentation snapshots the canonical public registry.
func registeredStepTypesForDocumentation() []string {
	handlers := List()
	types := make([]string, 0, len(handlers))
	for name := range handlers {
		types = append(types, name)
	}
	sort.Strings(types)
	return types
}

func TestStepDocumentationCoversRegisteredTypes(t *testing.T) {
	t.Parallel()

	if len(builtInStepTypes) == 0 {
		t.Fatal("documentation inventory requires initialized production step handlers")
	}

	root := filepath.Clean(filepath.Join("..", "..", ".."))
	stepsRoot := filepath.Join(root, "website", "docs", "steps")
	typeRoot := filepath.Join(stepsRoot, "type")
	index := readDocumentationFile(t, filepath.Join(stepsRoot, "type.mdx"))
	catalog := readDocumentationFile(t, filepath.Join(stepsRoot, "_partials", "_type-catalog.mdx"))
	sidebar := readDocumentationFile(t, filepath.Join(root, "website", "sidebars.js"))

	if !strings.Contains(index, "import StepTypeCatalog from './_partials/_type-catalog.mdx'") ||
		!strings.Contains(index, "<StepTypeCatalog />") {
		t.Error("public type index must render the shared step type catalog")
	}
	if !strings.Contains(sidebar, "{type: 'autogenerated', dirName: 'steps/type'}") {
		t.Error("documentation sidebar must include the step type directory")
	}

	// wait-all is documented with wait because both types operate on the same
	// background-service model. Every other canonical registry type owns a page.
	documents := map[string]string{
		"alert": "alert", "archive": "archive", "atmos": "atmos", "cancel": "cancel",
		"cast": "cast", "choose": "choose", "clear": "clear", "confirm": "confirm",
		"container": "container", "emulator": "emulator", "env": "env", "exec": "exec",
		"exit": "exit", "file": "file", "filter": "filter", "format": "format",
		"hint": "hint", "http": "http", "input": "input", "join": "join", "junit": "junit",
		"linebreak": "linebreak", "log": "log", "markdown": "markdown", "matrix": "matrix",
		"pager": "pager", "parallel": "parallel", "require": "require", "say": "say",
		"script": "script", "shell": "shell", "sleep": "sleep", "spin": "spin",
		"stage": "stage", "store": "store", "style": "style", "table": "table", "test": "test",
		"tflint": "tflint", "title": "title",
		"toast": "toast", "wait": "wait", "wait-all": "wait", "workdir": "workdir", "write": "write",
	}

	for _, stepType := range builtInStepTypes {
		doc, ok := documents[stepType]
		if !ok {
			t.Fatalf("registered step type %q has no documentation inventory entry", stepType)
		}
		if _, err := os.Stat(filepath.Join(typeRoot, doc+".mdx")); err != nil {
			t.Fatalf("registered step type %q is missing %s.mdx: %v", stepType, doc, err)
		}
		if !strings.Contains(catalog, "](/steps/type/"+doc+")") {
			t.Errorf("registered step type %q is missing from the public type index", stepType)
		}
	}

	for alias, canonical := range map[string]string{"assert": "require", "webhook": "http"} {
		content := readDocumentationFile(t, filepath.Join(typeRoot, canonical+".mdx"))
		if !strings.Contains(content, "`"+alias+"`") {
			t.Errorf("alias %q is not documented on %s.mdx", alias, canonical)
		}
	}
}

func readDocumentationFile(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read documentation file %s: %v", path, err)
	}
	return string(data)
}

func TestAutomationStepCatalogueCoversRegistry(t *testing.T) {
	t.Parallel()
	if len(builtInStepTypes) == 0 {
		t.Fatal("automation catalogue requires registered handlers")
	}
	page := readDocumentationFile(t, filepath.Join("..", "..", "..", "website", "docs", "functions", "automation", "steps.run.mdx"))
	for _, name := range builtInStepTypes {
		attr := "steps." + strings.ReplaceAll(name, "-", "_")
		if !strings.Contains(page, attr) {
			t.Errorf("missing automation step documentation for %s", attr)
		}
	}
}
