// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mock_interfaces.go -package=initcmd
//

// Package initcmd is a generated GoMock package.
package initcmd

import (
	reflect "reflect"

	engine "github.com/cloudposse/atmos/pkg/generator/engine"
	merge "github.com/cloudposse/atmos/pkg/generator/merge"
	templates "github.com/cloudposse/atmos/pkg/generator/templates"
	gomock "go.uber.org/mock/gomock"
)

// MockInitUI is a mock of InitUI interface.
type MockInitUI struct {
	ctrl     *gomock.Controller
	recorder *MockInitUIMockRecorder
	isgomock struct{}
}

// MockInitUIMockRecorder is the mock recorder for MockInitUI.
type MockInitUIMockRecorder struct {
	mock *MockInitUI
}

// NewMockInitUI creates a new mock instance.
func NewMockInitUI(ctrl *gomock.Controller) *MockInitUI {
	mock := &MockInitUI{ctrl: ctrl}
	mock.recorder = &MockInitUIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInitUI) EXPECT() *MockInitUIMockRecorder {
	return m.recorder
}

// ConfirmUpdateInstead mocks base method.
func (m *MockInitUI) ConfirmUpdateInstead(targetPath string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmUpdateInstead", targetPath)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConfirmUpdateInstead indicates an expected call of ConfirmUpdateInstead.
func (mr *MockInitUIMockRecorder) ConfirmUpdateInstead(targetPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmUpdateInstead", reflect.TypeOf((*MockInitUI)(nil).ConfirmUpdateInstead), targetPath)
}

// ExecuteWithBaseRef mocks base method.
func (m *MockInitUI) ExecuteWithBaseRef(embedsConfig *templates.Configuration, targetPath string, force, update, useDefaults bool, baseRef string, cmdTemplateValues map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteWithBaseRef", embedsConfig, targetPath, force, update, useDefaults, baseRef, cmdTemplateValues)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecuteWithBaseRef indicates an expected call of ExecuteWithBaseRef.
func (mr *MockInitUIMockRecorder) ExecuteWithBaseRef(embedsConfig, targetPath, force, update, useDefaults, baseRef, cmdTemplateValues any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteWithBaseRef", reflect.TypeOf((*MockInitUI)(nil).ExecuteWithBaseRef), embedsConfig, targetPath, force, update, useDefaults, baseRef, cmdTemplateValues)
}

// ExecuteWithInteractiveFlowAndBaseRefResult mocks base method.
func (m *MockInitUI) ExecuteWithInteractiveFlowAndBaseRefResult(embedsConfig *templates.Configuration, targetPath string, force, update, useDefaults bool, baseRef string, cmdTemplateValues map[string]any) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteWithInteractiveFlowAndBaseRefResult", embedsConfig, targetPath, force, update, useDefaults, baseRef, cmdTemplateValues)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteWithInteractiveFlowAndBaseRefResult indicates an expected call of ExecuteWithInteractiveFlowAndBaseRefResult.
func (mr *MockInitUIMockRecorder) ExecuteWithInteractiveFlowAndBaseRefResult(embedsConfig, targetPath, force, update, useDefaults, baseRef, cmdTemplateValues any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteWithInteractiveFlowAndBaseRefResult", reflect.TypeOf((*MockInitUI)(nil).ExecuteWithInteractiveFlowAndBaseRefResult), embedsConfig, targetPath, force, update, useDefaults, baseRef, cmdTemplateValues)
}

// PromptForTemplate mocks base method.
func (m *MockInitUI) PromptForTemplate(templateType string, arg1 any) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PromptForTemplate", templateType, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PromptForTemplate indicates an expected call of PromptForTemplate.
func (mr *MockInitUIMockRecorder) PromptForTemplate(templateType, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PromptForTemplate", reflect.TypeOf((*MockInitUI)(nil).PromptForTemplate), templateType, arg1)
}

// ResolveTargetPath mocks base method.
func (m *MockInitUI) ResolveTargetPath(embedsConfig *templates.Configuration, targetPath string, update, useDefaults bool, cmdTemplateValues map[string]any) (string, map[string]any, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveTargetPath", embedsConfig, targetPath, update, useDefaults, cmdTemplateValues)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(map[string]any)
	ret2, _ := ret[2].(bool)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// ResolveTargetPath indicates an expected call of ResolveTargetPath.
func (mr *MockInitUIMockRecorder) ResolveTargetPath(embedsConfig, targetPath, update, useDefaults, cmdTemplateValues any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveTargetPath", reflect.TypeOf((*MockInitUI)(nil).ResolveTargetPath), embedsConfig, targetPath, update, useDefaults, cmdTemplateValues)
}

// SetConflictStrategy mocks base method.
func (m *MockInitUI) SetConflictStrategy(strategy merge.ConflictStrategy) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetConflictStrategy", strategy)
}

// SetConflictStrategy indicates an expected call of SetConflictStrategy.
func (mr *MockInitUIMockRecorder) SetConflictStrategy(strategy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetConflictStrategy", reflect.TypeOf((*MockInitUI)(nil).SetConflictStrategy), strategy)
}

// SetMergeDriver mocks base method.
func (m *MockInitUI) SetMergeDriver(driver merge.Driver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetMergeDriver", driver)
}

// SetMergeDriver indicates an expected call of SetMergeDriver.
func (mr *MockInitUIMockRecorder) SetMergeDriver(driver any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMergeDriver", reflect.TypeOf((*MockInitUI)(nil).SetMergeDriver), driver)
}

// SetRenderedBaseSource mocks base method.
func (m *MockInitUI) SetRenderedBaseSource(cfg *templates.Configuration, values map[string]any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetRenderedBaseSource", cfg, values)
}

// SetRenderedBaseSource indicates an expected call of SetRenderedBaseSource.
func (mr *MockInitUIMockRecorder) SetRenderedBaseSource(cfg, values any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRenderedBaseSource", reflect.TypeOf((*MockInitUI)(nil).SetRenderedBaseSource), cfg, values)
}

// SetSkipHooks mocks base method.
func (m *MockInitUI) SetSkipHooks(skip func(string) bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSkipHooks", skip)
}

// SetSkipHooks indicates an expected call of SetSkipHooks.
func (mr *MockInitUIMockRecorder) SetSkipHooks(skip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSkipHooks", reflect.TypeOf((*MockInitUI)(nil).SetSkipHooks), skip)
}

// SetUpdateStrategy mocks base method.
func (m *MockInitUI) SetUpdateStrategy(strategy engine.UpdateStrategy) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetUpdateStrategy", strategy)
}

// SetUpdateStrategy indicates an expected call of SetUpdateStrategy.
func (mr *MockInitUIMockRecorder) SetUpdateStrategy(strategy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUpdateStrategy", reflect.TypeOf((*MockInitUI)(nil).SetUpdateStrategy), strategy)
}
