// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cloudposse/atmos/pkg/telemetry (interfaces: TelemetryClientProviderMock)
//
// Generated by this command:
//
//      mockgen . TelemetryClientProviderMock
//

// Package mock_telemetry is a generated GoMock package.

package mock_telemetry

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	posthog_go "github.com/posthog/posthog-go"
)

// MockTelemetryClientProviderMock is a mock of TelemetryClientProviderMock interface.
type MockTelemetryClientProviderMock struct {
	ctrl     *gomock.Controller
	recorder *MockTelemetryClientProviderMockMockRecorder
	isgomock struct{}
}

// MockTelemetryClientProviderMockMockRecorder is the mock recorder for MockTelemetryClientProviderMock.
type MockTelemetryClientProviderMockMockRecorder struct {
	mock *MockTelemetryClientProviderMock
}

// NewMockTelemetryClientProviderMock creates a new mock instance.
func NewMockTelemetryClientProviderMock(ctrl *gomock.Controller) *MockTelemetryClientProviderMock {
	mock := &MockTelemetryClientProviderMock{ctrl: ctrl}
	mock.recorder = &MockTelemetryClientProviderMockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTelemetryClientProviderMock) EXPECT() *MockTelemetryClientProviderMockMockRecorder {
	return m.recorder
}

// NewMockClient mocks base method.
func (m *MockTelemetryClientProviderMock) NewMockClient(arg0 string, arg1 posthog_go.Config) (posthog_go.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewMockClient", arg0, arg1)
	ret0, _ := ret[0].(posthog_go.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewMockClient indicates an expected call of NewMockClient.
func (mr *MockTelemetryClientProviderMockMockRecorder) NewMockClient(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewMockClient", reflect.TypeOf((*MockTelemetryClientProviderMock)(nil).NewMockClient), arg0, arg1)
}
