// Code generated by MockGen. DO NOT EDIT.
// Source: ./telemetry_client_provider_interface.go
//
// Generated by this command:
//
//	mockgen --package mock_telemetry --source ./telemetry_client_provider_interface.go TelemetryClientProviderMock
//

// Package mock_telemetry is a generated GoMock package.
package mock_telemetry

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	posthog_go "github.com/posthog/posthog-go"
)

// MockTelemetryClientProviderMock is a mock of TelemetryClientProviderMock interface.
type MockTelemetryClientProviderMock struct {
	ctrl     *gomock.Controller
	recorder *MockTelemetryClientProviderMockMockRecorder
	isgomock struct{}
}

// MockTelemetryClientProviderMockMockRecorder is the mock recorder for MockTelemetryClientProviderMock.
type MockTelemetryClientProviderMockMockRecorder struct {
	mock *MockTelemetryClientProviderMock
}

// NewMockTelemetryClientProviderMock creates a new mock instance.
func NewMockTelemetryClientProviderMock(ctrl *gomock.Controller) *MockTelemetryClientProviderMock {
	mock := &MockTelemetryClientProviderMock{ctrl: ctrl}
	mock.recorder = &MockTelemetryClientProviderMockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTelemetryClientProviderMock) EXPECT() *MockTelemetryClientProviderMockMockRecorder {
	return m.recorder
}

// NewMockClient mocks base method.
func (m *MockTelemetryClientProviderMock) NewMockClient(token string, config *posthog_go.Config) (posthog_go.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewMockClient", token, config)
	ret0, _ := ret[0].(posthog_go.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewMockClient indicates an expected call of NewMockClient.
func (mr *MockTelemetryClientProviderMockMockRecorder) NewMockClient(token, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewMockClient", reflect.TypeOf((*MockTelemetryClientProviderMock)(nil).NewMockClient), token, config)
}
