// Code generated by MockGen. DO NOT EDIT.
// Source: artifactory_store.go
//
// Generated by this command:
//
//	mockgen -source=artifactory_store.go -destination=mock_artifactory_store.go -package=providers
//

// Package providers is a generated GoMock package.
package providers

import (
	reflect "reflect"

	artifactory "github.com/jfrog/jfrog-client-go/artifactory"
	services "github.com/jfrog/jfrog-client-go/artifactory/services"
	content "github.com/jfrog/jfrog-client-go/utils/io/content"
	gomock "go.uber.org/mock/gomock"
)

// MockArtifactoryClient is a mock of ArtifactoryClient interface.
type MockArtifactoryClient struct {
	ctrl     *gomock.Controller
	recorder *MockArtifactoryClientMockRecorder
	isgomock struct{}
}

// MockArtifactoryClientMockRecorder is the mock recorder for MockArtifactoryClient.
type MockArtifactoryClientMockRecorder struct {
	mock *MockArtifactoryClient
}

// NewMockArtifactoryClient creates a new mock instance.
func NewMockArtifactoryClient(ctrl *gomock.Controller) *MockArtifactoryClient {
	mock := &MockArtifactoryClient{ctrl: ctrl}
	mock.recorder = &MockArtifactoryClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArtifactoryClient) EXPECT() *MockArtifactoryClientMockRecorder {
	return m.recorder
}

// DownloadFiles mocks base method.
func (m *MockArtifactoryClient) DownloadFiles(arg0 ...services.DownloadParams) (int, int, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DownloadFiles", varargs...)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DownloadFiles indicates an expected call of DownloadFiles.
func (mr *MockArtifactoryClientMockRecorder) DownloadFiles(arg0 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadFiles", reflect.TypeOf((*MockArtifactoryClient)(nil).DownloadFiles), arg0...)
}

// SearchFiles mocks base method.
func (m *MockArtifactoryClient) SearchFiles(arg0 services.SearchParams) (*content.ContentReader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchFiles", arg0)
	ret0, _ := ret[0].(*content.ContentReader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchFiles indicates an expected call of SearchFiles.
func (mr *MockArtifactoryClientMockRecorder) SearchFiles(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchFiles", reflect.TypeOf((*MockArtifactoryClient)(nil).SearchFiles), arg0)
}

// UploadFiles mocks base method.
func (m *MockArtifactoryClient) UploadFiles(arg0 artifactory.UploadServiceOptions, arg1 ...services.UploadParams) (int, int, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UploadFiles", varargs...)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UploadFiles indicates an expected call of UploadFiles.
func (mr *MockArtifactoryClientMockRecorder) UploadFiles(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFiles", reflect.TypeOf((*MockArtifactoryClient)(nil).UploadFiles), varargs...)
}
