// Code generated by MockGen. DO NOT EDIT.
// Source: google_secret_manager_store.go
//
// Generated by this command:
//
//	mockgen -source=google_secret_manager_store.go -destination=mock_google_secret_manager_store.go -package=providers
//

// Package providers is a generated GoMock package.
package providers

import (
	context "context"
	reflect "reflect"

	secretmanagerpb "cloud.google.com/go/secretmanager/apiv1/secretmanagerpb"
	gax "github.com/googleapis/gax-go/v2"
	gomock "go.uber.org/mock/gomock"
)

// MockSecretIterator is a mock of SecretIterator interface.
type MockSecretIterator struct {
	ctrl     *gomock.Controller
	recorder *MockSecretIteratorMockRecorder
	isgomock struct{}
}

// MockSecretIteratorMockRecorder is the mock recorder for MockSecretIterator.
type MockSecretIteratorMockRecorder struct {
	mock *MockSecretIterator
}

// NewMockSecretIterator creates a new mock instance.
func NewMockSecretIterator(ctrl *gomock.Controller) *MockSecretIterator {
	mock := &MockSecretIterator{ctrl: ctrl}
	mock.recorder = &MockSecretIteratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretIterator) EXPECT() *MockSecretIteratorMockRecorder {
	return m.recorder
}

// Next mocks base method.
func (m *MockSecretIterator) Next() (*secretmanagerpb.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Next")
	ret0, _ := ret[0].(*secretmanagerpb.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Next indicates an expected call of Next.
func (mr *MockSecretIteratorMockRecorder) Next() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Next", reflect.TypeOf((*MockSecretIterator)(nil).Next))
}

// MockGSMClient is a mock of GSMClient interface.
type MockGSMClient struct {
	ctrl     *gomock.Controller
	recorder *MockGSMClientMockRecorder
	isgomock struct{}
}

// MockGSMClientMockRecorder is the mock recorder for MockGSMClient.
type MockGSMClientMockRecorder struct {
	mock *MockGSMClient
}

// NewMockGSMClient creates a new mock instance.
func NewMockGSMClient(ctrl *gomock.Controller) *MockGSMClient {
	mock := &MockGSMClient{ctrl: ctrl}
	mock.recorder = &MockGSMClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGSMClient) EXPECT() *MockGSMClientMockRecorder {
	return m.recorder
}

// AccessSecretVersion mocks base method.
func (m *MockGSMClient) AccessSecretVersion(ctx context.Context, req *secretmanagerpb.AccessSecretVersionRequest, opts ...gax.CallOption) (*secretmanagerpb.AccessSecretVersionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AccessSecretVersion", varargs...)
	ret0, _ := ret[0].(*secretmanagerpb.AccessSecretVersionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AccessSecretVersion indicates an expected call of AccessSecretVersion.
func (mr *MockGSMClientMockRecorder) AccessSecretVersion(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccessSecretVersion", reflect.TypeOf((*MockGSMClient)(nil).AccessSecretVersion), varargs...)
}

// AddSecretVersion mocks base method.
func (m *MockGSMClient) AddSecretVersion(ctx context.Context, req *secretmanagerpb.AddSecretVersionRequest, opts ...gax.CallOption) (*secretmanagerpb.SecretVersion, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddSecretVersion", varargs...)
	ret0, _ := ret[0].(*secretmanagerpb.SecretVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddSecretVersion indicates an expected call of AddSecretVersion.
func (mr *MockGSMClientMockRecorder) AddSecretVersion(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSecretVersion", reflect.TypeOf((*MockGSMClient)(nil).AddSecretVersion), varargs...)
}

// Close mocks base method.
func (m *MockGSMClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockGSMClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockGSMClient)(nil).Close))
}

// CreateSecret mocks base method.
func (m *MockGSMClient) CreateSecret(ctx context.Context, req *secretmanagerpb.CreateSecretRequest, opts ...gax.CallOption) (*secretmanagerpb.Secret, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateSecret", varargs...)
	ret0, _ := ret[0].(*secretmanagerpb.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSecret indicates an expected call of CreateSecret.
func (mr *MockGSMClientMockRecorder) CreateSecret(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSecret", reflect.TypeOf((*MockGSMClient)(nil).CreateSecret), varargs...)
}

// DeleteSecret mocks base method.
func (m *MockGSMClient) DeleteSecret(ctx context.Context, req *secretmanagerpb.DeleteSecretRequest, opts ...gax.CallOption) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteSecret", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSecret indicates an expected call of DeleteSecret.
func (mr *MockGSMClientMockRecorder) DeleteSecret(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSecret", reflect.TypeOf((*MockGSMClient)(nil).DeleteSecret), varargs...)
}

// GetSecretVersion mocks base method.
func (m *MockGSMClient) GetSecretVersion(ctx context.Context, req *secretmanagerpb.GetSecretVersionRequest, opts ...gax.CallOption) (*secretmanagerpb.SecretVersion, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetSecretVersion", varargs...)
	ret0, _ := ret[0].(*secretmanagerpb.SecretVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecretVersion indicates an expected call of GetSecretVersion.
func (mr *MockGSMClientMockRecorder) GetSecretVersion(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretVersion", reflect.TypeOf((*MockGSMClient)(nil).GetSecretVersion), varargs...)
}

// ListSecrets mocks base method.
func (m *MockGSMClient) ListSecrets(ctx context.Context, req *secretmanagerpb.ListSecretsRequest, opts ...gax.CallOption) SecretIterator {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListSecrets", varargs...)
	ret0, _ := ret[0].(SecretIterator)
	return ret0
}

// ListSecrets indicates an expected call of ListSecrets.
func (mr *MockGSMClientMockRecorder) ListSecrets(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSecrets", reflect.TypeOf((*MockGSMClient)(nil).ListSecrets), varargs...)
}
