// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mock_interfaces_test.go -package=devcontainer
//

// Package devcontainer is a generated GoMock package.
package devcontainer

import (
	context "context"
	io "io"
	reflect "reflect"

	schema "github.com/cloudposse/atmos/pkg/schema"
	gomock "go.uber.org/mock/gomock"
)

// MockConfigProvider is a mock of ConfigProvider interface.
type MockConfigProvider struct {
	ctrl     *gomock.Controller
	recorder *MockConfigProviderMockRecorder
	isgomock struct{}
}

// MockConfigProviderMockRecorder is the mock recorder for MockConfigProvider.
type MockConfigProviderMockRecorder struct {
	mock *MockConfigProvider
}

// NewMockConfigProvider creates a new mock instance.
func NewMockConfigProvider(ctrl *gomock.Controller) *MockConfigProvider {
	mock := &MockConfigProvider{ctrl: ctrl}
	mock.recorder = &MockConfigProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigProvider) EXPECT() *MockConfigProviderMockRecorder {
	return m.recorder
}

// GetDevcontainerConfig mocks base method.
func (m *MockConfigProvider) GetDevcontainerConfig(config *schema.AtmosConfiguration, name string) (*DevcontainerConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDevcontainerConfig", config, name)
	ret0, _ := ret[0].(*DevcontainerConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDevcontainerConfig indicates an expected call of GetDevcontainerConfig.
func (mr *MockConfigProviderMockRecorder) GetDevcontainerConfig(config, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDevcontainerConfig", reflect.TypeOf((*MockConfigProvider)(nil).GetDevcontainerConfig), config, name)
}

// ListDevcontainers mocks base method.
func (m *MockConfigProvider) ListDevcontainers(config *schema.AtmosConfiguration) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDevcontainers", config)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDevcontainers indicates an expected call of ListDevcontainers.
func (mr *MockConfigProviderMockRecorder) ListDevcontainers(config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDevcontainers", reflect.TypeOf((*MockConfigProvider)(nil).ListDevcontainers), config)
}

// LoadAtmosConfig mocks base method.
func (m *MockConfigProvider) LoadAtmosConfig() (*schema.AtmosConfiguration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadAtmosConfig")
	ret0, _ := ret[0].(*schema.AtmosConfiguration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadAtmosConfig indicates an expected call of LoadAtmosConfig.
func (mr *MockConfigProviderMockRecorder) LoadAtmosConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadAtmosConfig", reflect.TypeOf((*MockConfigProvider)(nil).LoadAtmosConfig))
}

// MockRuntimeProvider is a mock of RuntimeProvider interface.
type MockRuntimeProvider struct {
	ctrl     *gomock.Controller
	recorder *MockRuntimeProviderMockRecorder
	isgomock struct{}
}

// MockRuntimeProviderMockRecorder is the mock recorder for MockRuntimeProvider.
type MockRuntimeProviderMockRecorder struct {
	mock *MockRuntimeProvider
}

// NewMockRuntimeProvider creates a new mock instance.
func NewMockRuntimeProvider(ctrl *gomock.Controller) *MockRuntimeProvider {
	mock := &MockRuntimeProvider{ctrl: ctrl}
	mock.recorder = &MockRuntimeProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuntimeProvider) EXPECT() *MockRuntimeProviderMockRecorder {
	return m.recorder
}

// Attach mocks base method.
func (m *MockRuntimeProvider) Attach(ctx context.Context, atmosConfig *schema.AtmosConfiguration, name string, opts AttachOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Attach", ctx, atmosConfig, name, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Attach indicates an expected call of Attach.
func (mr *MockRuntimeProviderMockRecorder) Attach(ctx, atmosConfig, name, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Attach", reflect.TypeOf((*MockRuntimeProvider)(nil).Attach), ctx, atmosConfig, name, opts)
}

// Exec mocks base method.
func (m *MockRuntimeProvider) Exec(ctx context.Context, atmosConfig *schema.AtmosConfiguration, name string, cmd []string, opts ExecOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exec", ctx, atmosConfig, name, cmd, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Exec indicates an expected call of Exec.
func (mr *MockRuntimeProviderMockRecorder) Exec(ctx, atmosConfig, name, cmd, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockRuntimeProvider)(nil).Exec), ctx, atmosConfig, name, cmd, opts)
}

// ListRunning mocks base method.
func (m *MockRuntimeProvider) ListRunning(ctx context.Context) ([]ContainerInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRunning", ctx)
	ret0, _ := ret[0].([]ContainerInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRunning indicates an expected call of ListRunning.
func (mr *MockRuntimeProviderMockRecorder) ListRunning(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRunning", reflect.TypeOf((*MockRuntimeProvider)(nil).ListRunning), ctx)
}

// Logs mocks base method.
func (m *MockRuntimeProvider) Logs(ctx context.Context, atmosConfig *schema.AtmosConfiguration, name string, opts LogsOptions) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logs", ctx, atmosConfig, name, opts)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Logs indicates an expected call of Logs.
func (mr *MockRuntimeProviderMockRecorder) Logs(ctx, atmosConfig, name, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logs", reflect.TypeOf((*MockRuntimeProvider)(nil).Logs), ctx, atmosConfig, name, opts)
}

// Rebuild mocks base method.
func (m *MockRuntimeProvider) Rebuild(ctx context.Context, atmosConfig *schema.AtmosConfiguration, name string, opts RebuildOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rebuild", ctx, atmosConfig, name, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rebuild indicates an expected call of Rebuild.
func (mr *MockRuntimeProviderMockRecorder) Rebuild(ctx, atmosConfig, name, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rebuild", reflect.TypeOf((*MockRuntimeProvider)(nil).Rebuild), ctx, atmosConfig, name, opts)
}

// Remove mocks base method.
func (m *MockRuntimeProvider) Remove(ctx context.Context, atmosConfig *schema.AtmosConfiguration, name string, opts RemoveOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, atmosConfig, name, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockRuntimeProviderMockRecorder) Remove(ctx, atmosConfig, name, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockRuntimeProvider)(nil).Remove), ctx, atmosConfig, name, opts)
}

// Start mocks base method.
func (m *MockRuntimeProvider) Start(ctx context.Context, atmosConfig *schema.AtmosConfiguration, name string, opts StartOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, atmosConfig, name, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockRuntimeProviderMockRecorder) Start(ctx, atmosConfig, name, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockRuntimeProvider)(nil).Start), ctx, atmosConfig, name, opts)
}

// Stop mocks base method.
func (m *MockRuntimeProvider) Stop(ctx context.Context, atmosConfig *schema.AtmosConfiguration, name string, opts StopOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx, atmosConfig, name, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockRuntimeProviderMockRecorder) Stop(ctx, atmosConfig, name, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockRuntimeProvider)(nil).Stop), ctx, atmosConfig, name, opts)
}

// MockUIProvider is a mock of UIProvider interface.
type MockUIProvider struct {
	ctrl     *gomock.Controller
	recorder *MockUIProviderMockRecorder
	isgomock struct{}
}

// MockUIProviderMockRecorder is the mock recorder for MockUIProvider.
type MockUIProviderMockRecorder struct {
	mock *MockUIProvider
}

// NewMockUIProvider creates a new mock instance.
func NewMockUIProvider(ctrl *gomock.Controller) *MockUIProvider {
	mock := &MockUIProvider{ctrl: ctrl}
	mock.recorder = &MockUIProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUIProvider) EXPECT() *MockUIProviderMockRecorder {
	return m.recorder
}

// Confirm mocks base method.
func (m *MockUIProvider) Confirm(message string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Confirm", message)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Confirm indicates an expected call of Confirm.
func (mr *MockUIProviderMockRecorder) Confirm(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Confirm", reflect.TypeOf((*MockUIProvider)(nil).Confirm), message)
}

// Error mocks base method.
func (m *MockUIProvider) Error() io.Writer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Error")
	ret0, _ := ret[0].(io.Writer)
	return ret0
}

// Error indicates an expected call of Error.
func (mr *MockUIProviderMockRecorder) Error() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockUIProvider)(nil).Error))
}

// IsInteractive mocks base method.
func (m *MockUIProvider) IsInteractive() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsInteractive")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsInteractive indicates an expected call of IsInteractive.
func (mr *MockUIProviderMockRecorder) IsInteractive() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsInteractive", reflect.TypeOf((*MockUIProvider)(nil).IsInteractive))
}

// Output mocks base method.
func (m *MockUIProvider) Output() io.Writer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Output")
	ret0, _ := ret[0].(io.Writer)
	return ret0
}

// Output indicates an expected call of Output.
func (mr *MockUIProviderMockRecorder) Output() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Output", reflect.TypeOf((*MockUIProvider)(nil).Output))
}

// Prompt mocks base method.
func (m *MockUIProvider) Prompt(message string, options []string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prompt", message, options)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Prompt indicates an expected call of Prompt.
func (mr *MockUIProviderMockRecorder) Prompt(message, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prompt", reflect.TypeOf((*MockUIProvider)(nil).Prompt), message, options)
}
