// Code generated by MockGen. DO NOT EDIT.
// Source: git.go
//
// Generated by this command:
//
//	mockgen -source=git.go -destination=mock_git.go -package=git -mock_names=GitRepoInterface=MockGitRepoInterface
//

// Package git is a generated GoMock package.
package git

import (
	reflect "reflect"

	git "github.com/go-git/go-git/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockGitRepoInterface is a mock of GitRepoInterface interface.
type MockGitRepoInterface struct {
	ctrl     *gomock.Controller
	recorder *MockGitRepoInterfaceMockRecorder
	isgomock struct{}
}

// MockGitRepoInterfaceMockRecorder is the mock recorder for MockGitRepoInterface.
type MockGitRepoInterfaceMockRecorder struct {
	mock *MockGitRepoInterface
}

// NewMockGitRepoInterface creates a new mock instance.
func NewMockGitRepoInterface(ctrl *gomock.Controller) *MockGitRepoInterface {
	mock := &MockGitRepoInterface{ctrl: ctrl}
	mock.recorder = &MockGitRepoInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitRepoInterface) EXPECT() *MockGitRepoInterfaceMockRecorder {
	return m.recorder
}

// GetCurrentCommitSHA mocks base method.
func (m *MockGitRepoInterface) GetCurrentCommitSHA() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentCommitSHA")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentCommitSHA indicates an expected call of GetCurrentCommitSHA.
func (mr *MockGitRepoInterfaceMockRecorder) GetCurrentCommitSHA() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentCommitSHA", reflect.TypeOf((*MockGitRepoInterface)(nil).GetCurrentCommitSHA))
}

// GetLocalRepoInfo mocks base method.
func (m *MockGitRepoInterface) GetLocalRepoInfo() (*RepoInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLocalRepoInfo")
	ret0, _ := ret[0].(*RepoInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLocalRepoInfo indicates an expected call of GetLocalRepoInfo.
func (mr *MockGitRepoInterfaceMockRecorder) GetLocalRepoInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLocalRepoInfo", reflect.TypeOf((*MockGitRepoInterface)(nil).GetLocalRepoInfo))
}

// GetRepoInfo mocks base method.
func (m *MockGitRepoInterface) GetRepoInfo(repo *git.Repository) (RepoInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepoInfo", repo)
	ret0, _ := ret[0].(RepoInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepoInfo indicates an expected call of GetRepoInfo.
func (mr *MockGitRepoInterfaceMockRecorder) GetRepoInfo(repo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepoInfo", reflect.TypeOf((*MockGitRepoInterface)(nil).GetRepoInfo), repo)
}
