name: "Deploy Preview"

on:
  workflow_run:
    workflows: [Website Deploy Preview]
    types:
      - completed

env:
  AWS_REGION: us-east-2
  IAM_ROLE_ARN: arn:aws:iam::068007702576:role/cplive-plat-ue2-dev-atmos-docs-gha
  IAM_ROLE_SESSION_NAME: cloudposse-atmos-ci-deploy-pr-${{ github.event.workflow_run.pull_requests.0.number }}
  S3_BUCKET_NAME: cplive-plat-ue2-dev-atmos-docs-origin
  PR_NUMBER: ${{ github.event.workflow_run.pull_requests.0.number }}
  DEPLOYMENT_HOST: pr-${{ github.event.workflow_run.pull_requests.0.number }}.atmos-docs.ue2.dev.plat.cloudposse.org
  ALGOLIA_INDEX_NAME: atmos-preview.tools
  ALGOLIA_APP_ID: 32YOERUX83

# These permissions are needed to interact with the GitHub's OIDC Token endpoint
permissions:
  id-token: write
  contents: read

jobs:
  website-deploy-preview:
    # Do not deploy the website to the preview environment if the PR has the label 'website-no-deploy' or the workflow run failed
    if: ${{ github.event.workflow_run.conclusion == 'success' && !contains(github.event.workflow_run.pull_requests.*.labels.*.name, 'website-no-deploy')  }}
    runs-on: ubuntu-latest
    environment:
      name: preview
      url: https://${{ env.DEPLOYMENT_HOST }}

    steps:
      # https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.IAM_ROLE_ARN }}
          role-session-name: ${{ env.IAM_ROLE_SESSION_NAME }}

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: website
          path: website/build
          run-id: ${{ github.event.workflow_run.id }}

      - name: Copy Website to S3 Bucket PR Folder
        run: |
          cd website/build
          aws sts get-caller-identity
          aws s3 sync . s3://${{ env.S3_BUCKET_NAME }}/pr-${{ env.PR_NUMBER }}/ --delete
          aws s3 ls s3://${{ env.S3_BUCKET_NAME }}/pr-${{ env.PR_NUMBER }}/ --recursive --human-readable --summarize

      - name: ReIndex with Algolia
        if: ${{ contains(github.event.workflow_run.pull_requests.*.labels.*.name, 'reindex') }}
        env:
          ALGOLIA_SCRAPER_API_KEY: ${{ secrets.ALGOLIA_SCRAPER_API_KEY }}
        run: |
          ./website/algolia/reindex.sh
