name: Feature release
on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "README.md"

env:
  TERRAFORM_VERSION: "1.9.7"
  OPEN_TOFU_VERSION: "1.9.1"
  HELMFILE_VERSION: "v1.1.0"

jobs:
  release:
    if: ${{ github.event_name == 'issue_comment' && contains(github.event.comment.body, '/release') }}
    uses: cloudposse/.github/.github/workflows/shared-go-auto-release.yml@main
    with:
      publish: true
      prerelease: true
      format: binary
      environment: 'feature-releases'
    secrets: inherit
