name: Feature release
on:
  pull_request:
    types: [ opened, synchronize, reopened, labeled, unlabeled ]
    paths-ignore:
      - "README.md"

permissions:
  attestations: write
  contents: write
  id-token: write
  pull-requests: write
  packages: write
  issues: write

jobs:
  release:
    if: |
      github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'release/feature')
    uses: cloudposse/.github/.github/workflows/shared-go-auto-release.yml@main
    with:
      publish: true
      prerelease: true
      format: binary
      environment: 'feature-releases'
      runs-on: '["runs-on=${{github.run_id}}", "runner=large", "tag=atmos","extras=s3-cache", "private=false"]'
      draft: ${{ github.event.pull_request.draft }}
    secrets: inherit
