name: Setup Go Cache Warmup
on:
  workflow_dispatch:
  schedule:
  # Run at 00:35 UTC (12:35 AM UTC) daily.
  # • Pacific Time (PT): 4:35 PM (previous day)
  # • Mountain Time (MT): 5:35 PM (previous day)
  # • Central Time (CT): 6:35 PM (previous day)
  # • Eastern Time (ET): 7:35 PM (previous day)
    - cron: "35 0 * * *"

jobs:
  cache-warmup:
    name: Cache warmup (${{ matrix.target }})
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: windows
          - os: macos-latest
            target: macos
    runs-on: ${{ matrix.os }}
    steps:
      - name: Add GNU tar to PATH (significantly faster than windows tar)
        if: matrix.target == 'windows'
        run: echo "C:\Program Files\Git\usr\bin" >> $Env:GITHUB_PATH

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
        id: go

      - name: Get deps
        run: make deps
