name: Tools Tests
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "tools/**"
      - ".github/workflows/test-tools.yml"
      - "go.mod"
      - "go.sum"

  push:
    branches:
      - main
      - release/v*
    paths:
      - "tools/**"
      - ".github/workflows/test-tools.yml"
      - "go.mod"
      - "go.sum"

  workflow_dispatch:
    inputs:
      enable-tmate:
        description: "Enable tmate debugging"
        required: false
        default: "false"
        type: choice
        options:
          - "false"
          - "true"
          - "on-failure"

jobs:
  # Test tools (gotcha and others)
  gotcha:
    name: "[gotcha] Test on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        exclude:
          # Skip windows on draft PRs
          - os: ${{ github.event.pull_request.draft && 'windows-latest' || 'none' }}
    env:
      GOTCHA_COMMENT_UUID: tools-test-gotcha-${{ matrix.os }}
      GOTCHA_JOB_DISCRIMINATOR: ${{ matrix.os }}
      GOTCHA_PROJECT_CONTEXT: gotcha
      # Force color output in GitHub Actions
      FORCE_COLOR: "2"
      TERM: xterm-256color

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache: true
          cache-dependency-path: |
            tools/gotcha/go.sum

      - name: Install Go dependencies
        working-directory: tools/gotcha
        run: |
          go mod download
          go mod tidy

      - name: Build gotcha
        if: ${{ ! ( matrix.os == 'windows-latest' && github.event.pull_request.draft ) }}
        working-directory: tools/gotcha
        run: |
          go build -v -o gotcha${{ matrix.os == 'windows-latest' && '.exe' || '' }} .

      - name: Run vanilla go test (debug baseline)
        if: ${{ ! ( matrix.os == 'windows-latest' && github.event.pull_request.draft ) }}
        working-directory: tools/gotcha
        run: |
          # Run vanilla go test to see what Go is reporting directly
          # This will help us understand why gotcha exits non-zero
          echo "=== Running vanilla go test ==="
          go test -v github.com/cloudposse/atmos/tools/gotcha/... || echo "Exit code: $?"
          echo "=== End vanilla go test ==="

      - name: Test gotcha with itself (dogfooding)
        if: ${{ ! ( matrix.os == 'windows-latest' && github.event.pull_request.draft ) }}
        working-directory: tools/gotcha
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Test gotcha binary on its own tests (dogfooding)
          # Use --format=github to automatically write to GITHUB_STEP_SUMMARY
          # Note: Temporarily disabled -race flag due to known race conditions in TUI tests with teatest
          # These are test-only issues, not affecting production code
          ./gotcha${{ matrix.os == 'windows-latest' && '.exe' || '' }} --cover --coverprofile=coverage.out --format=github --output=test-output.md github.com/cloudposse/atmos/tools/gotcha/...

      - name: Upload gotcha test results
        if: ${{ always() && ! ( matrix.os == 'windows-latest' && github.event.pull_request.draft ) }}
        uses: actions/upload-artifact@v4
        with:
          name: gotcha-test-results-${{ matrix.os }}
          path: |
            tools/gotcha/test-output.md
            tools/gotcha/coverage.out
          retention-days: 7

      - name: Upload gotcha coverage to Codecov
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ${{ github.repository }}
          files: tools/gotcha/coverage.out
          flags: gotcha
          name: gotcha-coverage
          verbose: true

  # Lint gotcha code
  lint-gotcha:
    name: "[gotcha] Lint"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache: true
          cache-dependency-path: |
            go.sum
            tools/gotcha/go.sum

      - name: golangci-lint for gotcha
        uses: golangci/golangci-lint-action@v6
        with:
          version: v2.4.0
          working-directory: tools/gotcha
          args: --timeout=10m
