name: vhs
on:
  pull_request:
    types: [labeled, opened, synchronize]
    paths:
      - '*.tape'
env:
  TERM: "xterm-256color"
  COLORTERM: "truecolor"
  LANG: "en_US.UTF-8"
  ATMOS_LOGS_LEVEL: "Info"

jobs:
  prepare:
    if: github.event.label.name == 'vhs'
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3

      - name: Get modified .tape files
        id: getfiles
        run: |
          if [[ "${{ github.event.label.name }}" == "vhs" ]]; then
            echo "::set-output name=files::$(ls *.tape)"
          else
            echo "::set-output name=files::$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep .tape)"
          fi

      - name: Set up matrix
        id: setupmatrix
        run: |
          echo "::set-output name=matrix::$(echo ${{ steps.getfiles.outputs.files }} | jq -R -s 'split(" ")')"

      - name: Install atmos
        uses: jaxxstorm/action-install-gh-release@v1.11.0
        with: # Grab the latest version
          repo: cloudposse/atmos
          chmod: 0755
          extension-matching: disable 
          rename-to: atmos

      - name: Setup shell rc
        run: |
          echo "alias ls='ls --color=always'" > ~/.bashrc
    outputs:
      matrix: ${{ steps.setupmatrix.outputs.matrix }}
       
  vhs:
    needs: [prepare]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{fromJson(needs.prepare.outputs.matrix)}}

    steps:
      - uses: charmbracelet/vhs-action@v1
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ matrix.file }}
          install-fonts: true

      - uses: stefanzweifel/git-auto-commit-action@v4
        id: auto-commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: "chore: update demo gif"
          commit_user_name: vhs-action 📼
          commit_user_email: actions@github.com
          commit_author: vhs-action 📼 <actions@github.com>
          file_pattern: '*.gif'

      - name: Add Image to Job Summary
        if: steps.auto-commit.outputs.changes_detected == 'true'
        run: |
          echo "## Demo GIF" >> $GITHUB_STEP_SUMMARY
          echo "![Demo GIF](https://github.com/${{ github.repository }}/blob/${{ steps.auto-commit.outputs.commit_hash }}/docs/demo.gif?raw=true)" >> $GITHUB_STEP_SUMMARY

      - name: No changes
        if: steps.auto-commit.outputs.changes_detected == 'false'
        run: |
          echo "No changes to demo" >> $GITHUB_STEP_SUMMARY
