name: "website-destroy-preview"

on:
  workflow_dispatch:

  pull_request:
    types:
      - closed

env:
  AWS_REGION: us-east-2
  IAM_ROLE_ARN: arn:aws:iam::068007702576:role/cplive-plat-ue2-dev-atmos-docs-github-action
  IAM_ROLE_SESSION_NAME: cloudposse/atmos/ci
  S3_BUCKET_NAME: cplive-plat-ue2-dev-atmos-docs-origin
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  website-destroy-preview:
    runs-on: ["self-hosted"]
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.IAM_ROLE_ARN }}
          role-session-name: ${{ env.IAM_ROLE_SESSION_NAME }}

      - name: Destroy S3 Bucket PR Folder
        run: |
          /usr/local/bin/aws sts get-caller-identity
          /usr/local/bin/aws s3 rm s3://${{ env.S3_BUCKET_NAME }}/ --recursive --exclude "*" --include "pr-${{ env.PR_NUMBER }}/*"
          /usr/local/bin/aws s3 ls s3://${{ env.S3_BUCKET_NAME }}/pr-${{ env.PR_NUMBER }}/ --recursive
