// Code generated by MockGen. DO NOT EDIT.
// Source: ../merge/yaml_processor.go
//
// Generated by this command:
//
//	mockgen -source=../merge/yaml_processor.go -destination=mock_yaml_processor_test.go -package=deferred
//

// Package deferred is a generated GoMock package.
package deferred

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockYAMLFunctionProcessor is a mock of YAMLFunctionProcessor interface.
type MockYAMLFunctionProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockYAMLFunctionProcessorMockRecorder
	isgomock struct{}
}

// MockYAMLFunctionProcessorMockRecorder is the mock recorder for MockYAMLFunctionProcessor.
type MockYAMLFunctionProcessorMockRecorder struct {
	mock *MockYAMLFunctionProcessor
}

// NewMockYAMLFunctionProcessor creates a new mock instance.
func NewMockYAMLFunctionProcessor(ctrl *gomock.Controller) *MockYAMLFunctionProcessor {
	mock := &MockYAMLFunctionProcessor{ctrl: ctrl}
	mock.recorder = &MockYAMLFunctionProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockYAMLFunctionProcessor) EXPECT() *MockYAMLFunctionProcessorMockRecorder {
	return m.recorder
}

// ProcessYAMLFunctionString mocks base method.
func (m *MockYAMLFunctionProcessor) ProcessYAMLFunctionString(value string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessYAMLFunctionString", value)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessYAMLFunctionString indicates an expected call of ProcessYAMLFunctionString.
func (mr *MockYAMLFunctionProcessorMockRecorder) ProcessYAMLFunctionString(value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessYAMLFunctionString", reflect.TypeOf((*MockYAMLFunctionProcessor)(nil).ProcessYAMLFunctionString), value)
}
