// Code generated by MockGen. DO NOT EDIT.
// Source: resolver.go
//
// Generated by this command:
//
//	mockgen -source=resolver.go -destination=mock_resolver_test.go -package=deferred
//

// Package deferred is a generated GoMock package.
package deferred

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockResolver is a mock of Resolver interface.
type MockResolver[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockResolverMockRecorder[T]
	isgomock struct{}
}

// MockResolverMockRecorder is the mock recorder for MockResolver.
type MockResolverMockRecorder[T any] struct {
	mock *MockResolver[T]
}

// NewMockResolver creates a new mock instance.
func NewMockResolver[T any](ctrl *gomock.Controller) *MockResolver[T] {
	mock := &MockResolver[T]{ctrl: ctrl}
	mock.recorder = &MockResolverMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResolver[T]) EXPECT() *MockResolverMockRecorder[T] {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockResolver[T]) Resolve() (T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve")
	ret0, _ := ret[0].(T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockResolverMockRecorder[T]) Resolve() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockResolver[T])(nil).Resolve))
}
