# yaml-language-server: $schema=https://atmos.tools/schemas/atmos/atmos-manifest/1.0/atmos-manifest.json

import:
  - _defaults

vars:
  stage: staging

components:
  terraform:
    app:
      vars:
        force_destroy: true
        queue_visibility_timeout_seconds: 45
        parameters:
          environment: staging
          log-level: info
